### PR TITLE
Batch request setup

### PR DESCRIPTION
**Pull request by jlm123hi**
A little bit of cleanup of old code and sketches of how I intend the API for batch requests to look/work.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/annotation-service/23)

### CODE REVIEW

**Comment by yachang** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[handler/metadata_schema.go, line 1 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/23#-KsKFqFCRuM4n2vv-IJv:-KsKFqFCRuM4n2vv-IJw:b-fnsckd) ([raw file](https://github.com/m-lab/annotation-service/blob/f4d854ed720ca06744bf176378069bd78620b3c1/handler/metadata_schema.go#L1)):*
> ```Go
> package handler
> ```

create a schema dir, and put this file into schema package.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/23)*

**Comment by yachang** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[handler/metadata_schema.go, line 1 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/23#-KsKFqFCRuM4n2vv-IJv:-KsKFykeqbPfOXxsIvGz:b-soofw8) ([raw file](https://github.com/m-lab/annotation-service/blob/f4d854ed720ca06744bf176378069bd78620b3c1/handler/metadata_schema.go#L1)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

create a schema dir, and put this file into schema package.
</blockquote></details>

Another choice is to move this file to etl/schema, and import that file here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/23)*

**Comment by jlm123hi** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[handler/metadata_schema.go, line 1 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/23#-KsKFqFCRuM4n2vv-IJv:-KsOaEakn--fFyS4sBaV:b-896fix) ([raw file](https://github.com/m-lab/annotation-service/blob/f4d854ed720ca06744bf176378069bd78620b3c1/handler/metadata_schema.go#L1)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

Another choice is to move this file to etl/schema, and import that file here.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/23)*

**Comment by yachang** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[handler/handler.go, line 39 at r2](https://reviewable.io:443/reviews/m-lab/annotation-service/23#-KsOkEwj7xKJpAS-rHVU:-KsOkEwj7xKJpAS-rHVV:b-7kumce) ([raw file](https://github.com/m-lab/annotation-service/blob/8c9556e1ce52fb673efa92801524fc4cce54a00e/handler/handler.go#L39)):*
> ```Go
> 	defer metrics.Metrics_activeRequests.Dec()
> 
> 	_, err := ValidateAndParse(r)
> ```

Add a //TODO here to handle returned value.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/23#-:-KsOl6_tF3-mwOfD4zlj:bnfp4nl)*

**Pull request merged**
