### PR TITLE
add metrics for RPC failures.

### PR DESCRIPTION
**Pull request by yachang**
This change is [Reviewable](https://reviewable.io/reviews/m-lab/annotation-service/257)

### CODE REVIEW

**Review by pboothe — APPROVED** [review]
Please add a new metric called `metrics.ClientErrors`/`annotation_client_errors` and use that.  

`metrics.ErrorTotal` is for server metrics and we should not overload it. 

> *[Reviewable](https://reviewable.io/reviews/m-lab/annotation-service/257#-:-LgT1Uwg9MWuHbHkjmI0:bh3u7fm)* status: 0 of 1 LGTMs obtained

___
*[api/v2/api-v2.go, line 156 at r1](https://reviewable.io/reviews/m-lab/annotation-service/257#-LgT1Wa92sO4rJ1xIA48:-LgT1WaA3MjyftXmReUF:b-w165dy) ([raw file](https://github.com/m-lab/annotation-service/blob/729bb84afe1d7cc3616f5cfacf2611cd32a1f431/api/v2/api-v2.go#L156)):*
> ```Go
> 	if err != nil {
> 		if httpResp == nil || httpResp.Body == nil {
> 			metrics.ErrorTotal.WithLabelValues("http Empty Response Error").Inc()
> ```

These metric labels are too long and wordy.  Please also use lowercase.
___
*[api/v2/api-v2.go, line 160 at r1](https://reviewable.io/reviews/m-lab/annotation-service/257#-LgT1iKD0taXUvn3qlnK:-LgT1iKD0taXUvn3qlnL:b-8or32e) ([raw file](https://github.com/m-lab/annotation-service/blob/729bb84afe1d7cc3616f5cfacf2611cd32a1f431/api/v2/api-v2.go#L160)):*
> ```Go
> 		}
> 		defer httpResp.Body.Close()
> 		if err == ErrStatusNotOK {
> ```

please log.Println the error (please do this for all errors)
___
*[api/v2/api-v2.go, line 184 at r1](https://reviewable.io/reviews/m-lab/annotation-service/257#-LgT1ZdT78cH8GumPfJz:-LgT1ZdT78cH8GumPfK-:brcc68h) ([raw file](https://github.com/m-lab/annotation-service/blob/729bb84afe1d7cc3616f5cfacf2611cd32a1f431/api/v2/api-v2.go#L184)):*
> ```Go
> 	body, err := ioutil.ReadAll(httpResp.Body)
> 	if err != nil {
> 		metrics.ErrorTotal.WithLabelValues("Cannot read http Responce Error").Inc()
> ```

Typo: responce should be response

**Review by pboothe — CHANGES_REQUESTED** [review]
Meant to "block" not "approve"

> *[Reviewable](https://reviewable.io/reviews/m-lab/annotation-service/257#-:-LgT238T5Hd2SAcAw73o:bdsg65u)* status: 0 of 1 LGTMs obtained

**Review by yachang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/annotation-service/257)* status: 0 of 1 LGTMs obtained

___
*[api/v2/api-v2.go, line 156 at r1](https://reviewable.io/reviews/m-lab/annotation-service/257#-LgT1Wa92sO4rJ1xIA48:-LgTHxSg7DtKSPpFUOuI:b-896fix) ([raw file](https://github.com/m-lab/annotation-service/blob/729bb84afe1d7cc3616f5cfacf2611cd32a1f431/api/v2/api-v2.go#L156)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

These metric labels are too long and wordy.  Please also use lowercase.
</blockquote></details>

Done.
___
*[api/v2/api-v2.go, line 160 at r1](https://reviewable.io/reviews/m-lab/annotation-service/257#-LgT1iKD0taXUvn3qlnK:-LgTIaxsCT_kcnh9bAb6:b-896fix) ([raw file](https://github.com/m-lab/annotation-service/blob/729bb84afe1d7cc3616f5cfacf2611cd32a1f431/api/v2/api-v2.go#L160)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

please log.Println the error (please do this for all errors)
</blockquote></details>

Done.
___
*[api/v2/api-v2.go, line 184 at r1](https://reviewable.io/reviews/m-lab/annotation-service/257#-LgT1ZdT78cH8GumPfJz:-LgTJbev-axkQD-Ub1Yo:b-896fix) ([raw file](https://github.com/m-lab/annotation-service/blob/729bb84afe1d7cc3616f5cfacf2611cd32a1f431/api/v2/api-v2.go#L184)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

Typo: responce should be response
</blockquote></details>

Done.

**Review by pboothe — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/annotation-service/257)* status: 0 of 1 LGTMs obtained

___
*[api/v2/api-v2.go, line 186 at r3](https://reviewable.io/reviews/m-lab/annotation-service/257#-LgTT8-y39p75UMupl-L:-LgTT8-y39p75UMupl-M:b-usdc45) ([raw file](https://github.com/m-lab/annotation-service/blob/b232dcbd87226b73b2ec77fa6db5b9265d5471be/api/v2/api-v2.go#L186)):*
> ```Go
> 	if httpResp.StatusCode != http.StatusOK {
> 		log.Println("http status not OK")
> 		metrics.ClientErrorTotal.WithLabelValues("http Status not OK").Inc()
> ```

No way to distinguish this from the earlier one with the same label.

Also Status should be lowercase status.

**Review by yachang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/annotation-service/257)* status: 0 of 1 LGTMs obtained

___
*[api/v2/api-v2.go, line 186 at r3](https://reviewable.io/reviews/m-lab/annotation-service/257#-LgTT8-y39p75UMupl-L:-LgTTuZuAyqVaC3Sf9pp:b-896fix) ([raw file](https://github.com/m-lab/annotation-service/blob/b232dcbd87226b73b2ec77fa6db5b9265d5471be/api/v2/api-v2.go#L186)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

No way to distinguish this from the earlier one with the same label.

Also Status should be lowercase status.
</blockquote></details>

Done.

**Review by pboothe — APPROVED** [review]
LGTM with one last change

> *[Reviewable](https://reviewable.io/reviews/m-lab/annotation-service/257#-:-LgTUnTo9q_Wmu26ZnsX:b-9g4rdf)* status: 0 of 1 LGTMs obtained

___
*[api/v2/api-v2.go, line 185 at r4](https://reviewable.io/reviews/m-lab/annotation-service/257#-LgTUM02-BpulD5dkM9n:-LgTUM02-BpulD5dkM9o:b3zberd) ([raw file](https://github.com/m-lab/annotation-service/blob/d9c9ac5d0b7d5f433bc20b3330846f45e38d45df/api/v2/api-v2.go#L185)):*
> ```Go
> 	// Handle other status codes
> 	if httpResp.StatusCode != http.StatusOK {
> 		log.Println("http statuscode not OK")
> ```

`log.Println("http status code is", httpResp.StatusCode)`

**Pull request merged**
