### PR TITLE
load all datasets into memory

### PR DESCRIPTION
**Pull request by yachang**
This change is [Reviewable](https://reviewable.io/reviews/m-lab/annotation-service/190)

### CODE REVIEW

**Review by gfr10598 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/annotation-service/190)* status: 0 of 1 LGTMs obtained

___
*[manager/manager.go, line 217 at r1](https://reviewable.io/reviews/m-lab/annotation-service/190#-LXPIdxW-z8Rx7ACK2PV:-LXPIdxW-z8Rx7ACK2PW:b-au6d6p) ([raw file](https://github.com/m-lab/annotation-service/blob/ef29a031430e2737de5edaa256d5bb1d7e637396/manager/manager.go#L217)):*
> ```Go
> 
> // FetchAnnotator returns the annoator in memory based on filename.
> func (am *AnnotatorMap) FetchAnnotator(key string) (api.Annotator, error) {
> ```

Please just modify GetAnnotator instead of introducing a new function.

**Review by gfr10598 — APPROVED** [review]
:lgtm: after changes.

> *[Reviewable](https://reviewable.io/reviews/m-lab/annotation-service/190#-:-LXPm6e2BkTIUCQMIXJ-:bbwmlz2)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[geoloader/filename.go, line 143 at r2](https://reviewable.io/reviews/m-lab/annotation-service/190#-LXPlkvNCMGH_fXQeAxa:-LXPlkvNCMGH_fXQeAxb:b-3wkbap) ([raw file](https://github.com/m-lab/annotation-service/blob/317ab23ab99eabafa4f64e82ae18b04e8ec593a4/geoloader/filename.go#L143)):*
> ```Go
> 		if fileDate.Before(GeoLite2StartDate) {
> 			// temporary hack to avoid legacy
> 			if !GeoLegacyRegex.MatchString(file.Name) && !GeoLegacyv6Regex.MatchString(file.Name) {
> ```

Not clear why this is necessary.  Add comment?

**Review by yachang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/annotation-service/190)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[geoloader/filename.go, line 143 at r2](https://reviewable.io/reviews/m-lab/annotation-service/190#-LXPlkvNCMGH_fXQeAxa:-LXPntIM8LH4cBR2jKjr:b-896fix) ([raw file](https://github.com/m-lab/annotation-service/blob/317ab23ab99eabafa4f64e82ae18b04e8ec593a4/geoloader/filename.go#L143)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Not clear why this is necessary.  Add comment?
</blockquote></details>

Done.
___
*[manager/manager.go, line 217 at r1](https://reviewable.io/reviews/m-lab/annotation-service/190#-LXPIdxW-z8Rx7ACK2PV:-LXPoL5f2_cYYpQnLPBF:b-896fix) ([raw file](https://github.com/m-lab/annotation-service/blob/99e1adb7e5b06169a424e3d0a7f112b9c2424da6/manager/manager.go#L217)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Please just modify GetAnnotator instead of introducing a new function.
</blockquote></details>

Done.

**Review by gfr10598 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/annotation-service/190)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[manager/manager.go, line 227 at r3](https://reviewable.io/reviews/m-lab/annotation-service/190#-LXQ5eMc3uzPo-fGkvUX:-LXQ5eMc3uzPo-fGkvUY:b-a4pvb9) ([raw file](https://github.com/m-lab/annotation-service/blob/a3d63d8d6ababff2c618fa2a2226a023bbea6111/manager/manager.go#L227)):*
> ```Go
> 
> // GetAnnotator returns the correct annotator to use for a given timestamp.
> func GetAnnotator(request *api.RequestData) (api.Annotator, error) {
> ```

I think this is a regression.  I changed all the APIs to use the date, instead of a request.  Why change it back?

**Review by gfr10598 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/annotation-service/190)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[geoloader/filename.go, line 35 at r3](https://reviewable.io/reviews/m-lab/annotation-service/190#-LXQ7WVV3wNJ5myWwF9v:-LXQ7WVV3wNJ5myWwF9w:b4yaing) ([raw file](https://github.com/m-lab/annotation-service/blob/a3d63d8d6ababff2c618fa2a2226a023bbea6111/geoloader/filename.go#L35)):*
> ```Go
> // To speed up online matching, we build another directory for IPv6 as well.
> var datasetDirV6 = &directory{}
> var datasetDirLockV6 sync.RWMutex
> ```

Might be better to use a single lock to protect both, and update them together.
___
*[geoloader/filename.go, line 65 at r3](https://reviewable.io/reviews/m-lab/annotation-service/190#-LXQ8BC99l98Or3MZGGI:-LXQ8BC99l98Or3MZGGJ:bfh1z0w) ([raw file](https://github.com/m-lab/annotation-service/blob/a3d63d8d6ababff2c618fa2a2226a023bbea6111/geoloader/filename.go#L65)):*
> ```Go
> type dateEntry struct {
> 	date      time.Time
> 	filenames []string
> ```

I guess you only need a single filename now.
I'm also thinking it would be better to store the GeoIP directly here as well.  That is a bigger refactoring, so maybe better to do it in a separate PR.
___
*[geoloader/filename.go, line 136 at r3](https://reviewable.io/reviews/m-lab/annotation-service/190#-LXQ6s-T6F3ZLT_jFSRT:-LXQ6s-T6F3ZLT_jFSRU:b-jps0r9) ([raw file](https://github.com/m-lab/annotation-service/blob/a3d63d8d6ababff2c618fa2a2226a023bbea6111/geoloader/filename.go#L136)):*
> ```Go
> func UpdateArchivedFilenames() error {
> 	old := getDirectoryV4()
> 	size := len(old.dates) + 2
> ```

Should use the max of v4 and v6 here, or use v4 to size v4, and v6 to size v6.
___
*[geoloader/filename.go, line 170 at r3](https://reviewable.io/reviews/m-lab/annotation-service/190#-LXQ6_G-3dgHzYLnMs3d:-LXQ6_G-3dgHzYLnMs3e:b-ppg8k9) ([raw file](https://github.com/m-lab/annotation-service/blob/a3d63d8d6ababff2c618fa2a2226a023bbea6111/geoloader/filename.go#L170)):*
> ```Go
> 		}
> 
> 		if !fileDate.Before(GeoLite2StartDate) && !GeoLite2Regex.MatchString(file.Name) {
> ```

This sequence of if statements is becoming hard to reason about.
___
*[geoloader/filename.go, line 183 at r3](https://reviewable.io/reviews/m-lab/annotation-service/190#-LXQ77IXBhKe_Yl2o7Lj:-LXQ77IXBhKe_Yl2o7Lk:b-njm2ad) ([raw file](https://github.com/m-lab/annotation-service/blob/a3d63d8d6ababff2c618fa2a2226a023bbea6111/geoloader/filename.go#L183)):*
> ```Go
> 			dirV6.Insert(fileDate, file.Name)
> 		}
> 		DatasetFilenames = append(DatasetFilenames, file.Name)
> ```

This will do the wrong thing when Update... is called again.  Put some more thought into this.

**Review by yachang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/annotation-service/190)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[geoloader/filename.go, line 35 at r3](https://reviewable.io/reviews/m-lab/annotation-service/190#-LXQ7WVV3wNJ5myWwF9v:-LXQB-gYCwyauwe4nGe4:b-896fix) ([raw file](https://github.com/m-lab/annotation-service/blob/a3d63d8d6ababff2c618fa2a2226a023bbea6111/geoloader/filename.go#L35)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Might be better to use a single lock to protect both, and update them together.
</blockquote></details>

Done.
___
*[geoloader/filename.go, line 65 at r3](https://reviewable.io/reviews/m-lab/annotation-service/190#-LXQ8BC99l98Or3MZGGI:-LXQAypB7TPUlVLHhLeb:b-896fix) ([raw file](https://github.com/m-lab/annotation-service/blob/a3d63d8d6ababff2c618fa2a2226a023bbea6111/geoloader/filename.go#L65)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

I guess you only need a single filename now.
I'm also thinking it would be better to store the GeoIP directly here as well.  That is a bigger refactoring, so maybe better to do it in a separate PR.

</blockquote></details>

Done.
___
*[geoloader/filename.go, line 136 at r3](https://reviewable.io/reviews/m-lab/annotation-service/190#-LXQ6s-T6F3ZLT_jFSRT:-LXQAzbeAt3sW17q2Z_n:b-896fix) ([raw file](https://github.com/m-lab/annotation-service/blob/a3d63d8d6ababff2c618fa2a2226a023bbea6111/geoloader/filename.go#L136)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Should use the max of v4 and v6 here, or use v4 to size v4, and v6 to size v6.
</blockquote></details>

Done.

**Review by yachang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/annotation-service/190)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[geoloader/filename.go, line 170 at r3](https://reviewable.io/reviews/m-lab/annotation-service/190#-LXQ6_G-3dgHzYLnMs3d:-LXQB7nTDluqgkHfn2kR:b-9mcblt) ([raw file](https://github.com/m-lab/annotation-service/blob/a3d63d8d6ababff2c618fa2a2226a023bbea6111/geoloader/filename.go#L170)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

This sequence of if statements is becoming hard to reason about.
</blockquote></details>

This is to discard all dataset that is after cutoff date, but not Geolite2, since we download legacy datasets as well after cutoff date.

**Review by yachang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/annotation-service/190)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[geoloader/filename.go, line 183 at r3](https://reviewable.io/reviews/m-lab/annotation-service/190#-LXQ77IXBhKe_Yl2o7Lj:-LXQBTPa2KSMfIaiKhgc:b-ucfknh) ([raw file](https://github.com/m-lab/annotation-service/blob/a3d63d8d6ababff2c618fa2a2226a023bbea6111/geoloader/filename.go#L183)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

This will do the wrong thing when Update... is called again.  Put some more thought into this.
</blockquote></details>

Thanks!

**Review by yachang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/annotation-service/190)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[manager/manager.go, line 227 at r3](https://reviewable.io/reviews/m-lab/annotation-service/190#-LXQ5eMc3uzPo-fGkvUX:-LXQBZN5348zc8muADkd:byx7qpx) ([raw file](https://github.com/m-lab/annotation-service/blob/a3d63d8d6ababff2c618fa2a2226a023bbea6111/manager/manager.go#L227)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

I think this is a regression.  I changed all the APIs to use the date, instead of a request.  Why change it back?
</blockquote></details>

because we need info of IPv4 or IPv6 to select an annotator now unfortunately :(

**Review by gfr10598 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/annotation-service/190)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[geoloader/filename.go, line 135 at r4](https://reviewable.io/reviews/m-lab/annotation-service/190#-LXQdbpw10IDZOJEjlbY:-LXQdbpw10IDZOJEjlbZ:b-4764pc) ([raw file](https://github.com/m-lab/annotation-service/blob/5231b42f8ed7988c20f5b2213a13573f6abfb818/geoloader/filename.go#L135)):*
> ```Go
> 		return err
> 	}
> 	DatasetFilenames = []string{}
> ```

I think you need to protect DatasetFilenames with the mutex, too.
Suggest you make it local, and access it with an exported access function.

Probably should then create all the slices, then take the lock and replace them all at once.

**Review by gfr10598 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/annotation-service/190)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[geoloader/filename.go, line 135 at r4](https://reviewable.io/reviews/m-lab/annotation-service/190#-LXQdbpw10IDZOJEjlbY:-LXQe3SxBkBZKHF8FaJK:b9x66e3) ([raw file](https://github.com/m-lab/annotation-service/blob/5231b42f8ed7988c20f5b2213a13573f6abfb818/geoloader/filename.go#L135)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

I think you need to protect DatasetFilenames with the mutex, too.
Suggest you make it local, and access it with an exported access function.

Probably should then create all the slices, then take the lock and replace them all at once.
</blockquote></details>

BTW, it would be nice to have a unit test that shows this race condition.  Let me know if you want help creating one.

**Review by yachang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/annotation-service/190)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[geoloader/filename.go, line 135 at r4](https://reviewable.io/reviews/m-lab/annotation-service/190#-LXQdbpw10IDZOJEjlbY:-LXVFtk357JEdQatnQZ_:b-896fix) ([raw file](https://github.com/m-lab/annotation-service/blob/5231b42f8ed7988c20f5b2213a13573f6abfb818/geoloader/filename.go#L135)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

BTW, it would be nice to have a unit test that shows this race condition.  Let me know if you want help creating one.
</blockquote></details>

Done.

**Pull request merged**
