### PR TITLE
add RequestInfo to GetAnnotations and metrics

### PR DESCRIPTION
**Pull request by gfr10598**
Adds optional info field to public v2.Annotator and GetAnnotations.  Plumbs the field through RequestTime metrics.
See #246

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/annotation-service/247)

### CODE REVIEW

**Review by pboothe — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/annotation-service/247)* status: 0 of 1 LGTMs obtained

___
*[handler/handler.go, line 252 at r2](https://reviewable.io/reviews/m-lab/annotation-service/247#-LfVeTv2-QRKWWmp_Iwe:-LfVeTv2-QRKWWmp_Iwf:b-z5ydgs) ([raw file](https://github.com/m-lab/annotation-service/blob/9f83cb3b744ad67adf6c1abc26c97afddb2d944b/handler/handler.go#L252)):*
> ```Go
> 			// If it isn't loading, client should probably give up instead of retrying.
> 			w.WriteHeader(http.StatusInternalServerError)
> 			metrics.RequestTimeHistogramUsec.WithLabelValues("", label, err.Error()).Observe(float64(time.Since(tStart).Nanoseconds()) / 1000)
> ```

Should this "" be reqInfo ?

**Review by gfr10598 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/annotation-service/247)* status: 0 of 1 LGTMs obtained

___
*[handler/handler.go, line 252 at r2](https://reviewable.io/reviews/m-lab/annotation-service/247#-LfVeTv2-QRKWWmp_Iwe:-LfVfFUu6aL84lszft7l:b-896fix) ([raw file](https://github.com/m-lab/annotation-service/blob/9f83cb3b744ad67adf6c1abc26c97afddb2d944b/handler/handler.go#L252)):*
<details><summary><i>Previously, pboothe (Peter Boothe) wrote…</i></summary><blockquote>

Should this "" be reqInfo ?
</blockquote></details>

Done.

**Review by pboothe — APPROVED** [review]
LGTM

**Review by pboothe — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/m-lab/annotation-service/247#-:-LfVhOZ3BpEb6NwOe8d_:bnfp4nl)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Pull request merged**
