### PR TITLE
Increase max RAM to prevent service oom

### PR DESCRIPTION
**Pull request by stephen-soltesz**
This is in response to https://github.com/m-lab/dev-tracker/issues/546 during which we discovered that the annotator was crashing due to OOM conditions.

This change increases the cpu count to 30 and uses the max allowable RAM for that CPU count.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/annotation-service/269)

### CODE REVIEW

**Review by gfr10598 — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/m-lab/annotation-service/269#-:-M-lJIev1Q70ruU6L9CR:bg7igkv)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Comment by stephen-soltesz** [comment]
https://github.com/m-lab/dev-tracker/issues/507

**Comment by stephen-soltesz** [comment]
There were build incompatibilities due requirements for go1.13 now, but the tests are still failing for a less apparent reason:

For example:

```
$ GCLOUD_PROJECT=mlab-testing go test -v -coverpkg=./... -coverprofile=coverage.cov ./...
# github.com/m-lab/annotation-service/api.test
2020/02/10 23:15:25 duplicate symbol main.init.0 (types 1 and 1) in main and $WORK/b001/_pkg_.a(_go_.o)
?   	github.com/m-lab/annotation-service	[no test files]
FAIL	github.com/m-lab/annotation-service/api [build failed]
# github.com/m-lab/annotation-service/api/v2.test
2020/02/10 23:15:26 duplicate symbol main.init.0 (types 1 and 1) in main and $WORK/b001/_pkg_.a(_go_.o)
FAIL	github.com/m-lab/annotation-service/api/v2 [build failed]
# github.com/m-lab/annotation-service/directory.test
```

Can't reproduce this on my desktop -- may be an artifact of travis or something else different locally vs travis.

**Comment by stephen-soltesz** [comment]
There are notes about the main.init errors being resolved with `go mod` however, m-lab/etl is not compatible with the go.mod conventions since it's at v2.1.3 but does not use the correct "v2" conventions (I'm not perfectly clear what those are).

**Pull request merged**
