### PR TITLE
Enable real annotation

### PR DESCRIPTION
**Pull request by jlm123hi**
This contains the last of the code needed for the first iteration of current-time annotation.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/annotation-service/35)

### CODE REVIEW

**Comment by gfr10598** [comment]
Reviewed 7 of 9 files at r1.
Review status: 7 of 9 files reviewed at latest revision, 6 unresolved discussions.

---

*[main.go, line 13 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/35#-KtMUOy5Lnd1aZpmj9v5:-KtMUOy5Lnd1aZpmj9v6:bwk4t4) ([raw file](https://github.com/m-lab/annotation-service/blob/e515c0f9ec2e663d640dc614756794eeb05708cb/main.go#L13)):*
> ```Go
> 
> func main() {
> 	log.Print("Begining Setup\n")
> ```

Beginning

---

*[handler/handler.go, line 22 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/35#-KtMUaVyk8PLzEm77vnS:-KtMUaVyk8PLzEm77vnT:blk4o) ([raw file](https://github.com/m-lab/annotation-service/blob/e515c0f9ec2e663d640dc614756794eeb05708cb/handler/handler.go#L22)):*
> ```Go
> )
> 
> // A mutex to make sure that we are not reading from the dataset while
> ```

reading from the dataset pointer while ...

---

*[handler/handler.go, line 166 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/35#-KtMUh6WRM2tVhqHwOMm:-KtMUh6WRM2tVhqHwOMn:b-5ypu2v) ([raw file](https://github.com/m-lab/annotation-service/blob/e515c0f9ec2e663d640dc614756794eeb05708cb/handler/handler.go#L166)):*
> ```Go
> func GetMetadataForSingleIP(request *schema.RequestData) *schema.MetaData {
> 	metrics.Metrics_totalLookups.Inc()
> 	if CurrentGeoDataset == nil {
> ```

Add a TODO to block until the dataset is non-nil.

---

*[handler/handler.go, line 174 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/35#-KtMUug-rY4vYGD5Fiyj:-KtMUug-rY4vYGD5Fiyk:bnqhe4u) ([raw file](https://github.com/m-lab/annotation-service/blob/e515c0f9ec2e663d640dc614756794eeb05708cb/handler/handler.go#L174)):*
> ```Go
> 	defer currentDataMutex.RUnlock()
> 	var node parser.IPNode
> 	if request.IPFormat == 4 {
> ```

This logic should be pushed down into SearchList.

---

*[parser/geo-ip.go, line 129 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/35#-KtMVTcl8a-VWcfHEo-c:-KtMVTcl8a-VWcfHEo-d:b-rieaa) ([raw file](https://github.com/m-lab/annotation-service/blob/e515c0f9ec2e663d640dc614756794eeb05708cb/parser/geo-ip.go#L129)):*
> ```Go
> 					index = -1
> 					log.Println("Couldn't get a valid Geoname id!", record)
> 					//TODO: Add a prometheus metric here
> ```

Please add this counter now.

---

*[search/geo-search.go, line 13 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/35#-KtMVaM6pis2Bz8zwmPq:-KtMVaM6pis2Bz8zwmPr:bhxayaq) ([raw file](https://github.com/m-lab/annotation-service/blob/e515c0f9ec2e663d640dc614756794eeb05708cb/search/geo-search.go#L13)):*
> ```Go
> 
> // Returns a parser.IPNode with the smallet range that includes the provided IP address
> func SearchList(list []parser.IPNode, ipLookUp string) (parser.IPNode, error) {
> ```

I'm a bit worried about merge headaches if Shelby has pending edits to this function.  Could you check with her?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/35)*

**Comment by jlm123hi** [comment]
Review status: 7 of 9 files reviewed at latest revision, 6 unresolved discussions.

---

*[handler/handler.go, line 22 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/35#-KtMUaVyk8PLzEm77vnS:-KtMWW03UYCiSwOcZn9R:b-cgkpxp) ([raw file](https://github.com/m-lab/annotation-service/blob/e515c0f9ec2e663d640dc614756794eeb05708cb/handler/handler.go#L22)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

reading from the dataset pointer while ...
</blockquote></details>

... trying to update it. It's the next line, wrapped due to the column width.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/35)*

**Comment by jlm123hi** [comment]
Review status: 5 of 9 files reviewed at latest revision, 6 unresolved discussions.

---

*[main.go, line 13 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/35#-KtMUOy5Lnd1aZpmj9v5:-KtM_Lq4AnWD_uR-o49d:b-896fix) ([raw file](https://github.com/m-lab/annotation-service/blob/e515c0f9ec2e663d640dc614756794eeb05708cb/main.go#L13)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Beginning
</blockquote></details>

Done.

---

*[handler/handler.go, line 166 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/35#-KtMUh6WRM2tVhqHwOMm:-KtM_61StjEIDZXbzKFa:b-896fix) ([raw file](https://github.com/m-lab/annotation-service/blob/e515c0f9ec2e663d640dc614756794eeb05708cb/handler/handler.go#L166)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Add a TODO to block until the dataset is non-nil.
</blockquote></details>

Done.

---

*[handler/handler.go, line 174 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/35#-KtMUug-rY4vYGD5Fiyj:-KtMZxftd6yZMxuKAQfz:b-75v6h) ([raw file](https://github.com/m-lab/annotation-service/blob/e515c0f9ec2e663d640dc614756794eeb05708cb/handler/handler.go#L174)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

This logic should be pushed down into SearchList.
</blockquote></details>

Added a todo because we are waiting on binary search.

---

*[parser/geo-ip.go, line 129 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/35#-KtMVTcl8a-VWcfHEo-c:-KtMYWJhknoEk8uQCke7:b-z0ltcr) ([raw file](https://github.com/m-lab/annotation-service/blob/e515c0f9ec2e663d640dc614756794eeb05708cb/parser/geo-ip.go#L129)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Please add this counter now.
</blockquote></details>

Ignored as discussed in person. Added a todo above the search function.

---

*[search/geo-search.go, line 13 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/35#-KtMVaM6pis2Bz8zwmPq:-KtM_BfGEMDvWG2ZeQ66:b-z2r5ea) ([raw file](https://github.com/m-lab/annotation-service/blob/e515c0f9ec2e663d640dc614756794eeb05708cb/search/geo-search.go#L13)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

I'm a bit worried about merge headaches if Shelby has pending edits to this function.  Could you check with her?
</blockquote></details>

Talked in person.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/35)*

**Comment by gfr10598** [comment]
Review status: 5 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[handler/handler.go, line 22 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/35#-KtMUaVyk8PLzEm77vnS:-KtMaCMQNIdP7SUqXAg_:b-gmt4gv) ([raw file](https://github.com/m-lab/annotation-service/blob/e515c0f9ec2e663d640dc614756794eeb05708cb/handler/handler.go#L22)):*
<details><summary><i>Previously, jlm123hi (Joseph Marques) wrote…</i></summary><blockquote>

... trying to update it. It's the next line, wrapped due to the column width.
</blockquote></details>

key word is "pointer"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/35)*

**Comment by gfr10598** [comment]
:lgtm: after comment fix.

---

Review status: 5 of 9 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/35#-:-KtMaYP8OMssLGzHjYR-:bnv0oy5)*

**Comment by jlm123hi** [comment]
Review status: 5 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[handler/handler.go, line 22 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/35#-KtMUaVyk8PLzEm77vnS:-KtMb1ahkt7kic0dTk_M:biyo5xq) ([raw file](https://github.com/m-lab/annotation-service/blob/e515c0f9ec2e663d640dc614756794eeb05708cb/handler/handler.go#L22)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

key word is "pointer"
</blockquote></details>

My bad, I totally misunderstood what you meant.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/35)*

**Pull request merged**
