### PR TITLE
Fix the merged CA bug that use 20180601 for the first several years

### PR DESCRIPTION
**Pull request by yachang**
This change is [Reviewable](https://reviewable.io/reviews/m-lab/annotation-service/265)

### CODE REVIEW

**Review by gfr10598 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/annotation-service/265)* status: 0 of 1 LGTMs obtained

___
*[directory/directory.go, line 41 at r4](https://reviewable.io/reviews/m-lab/annotation-service/265#-Lk9VXTN7XsNB-cNAQPn:-Lk9VXTN7XsNB-cNAQPo:bub79gu) ([raw file](https://github.com/m-lab/annotation-service/blob/505786bebdcf039ab707c0d463579c445a7dc2b5/directory/directory.go#L41)):*
> ```Go
> // CompositeAnnotator wraps several annotators, and calls to Annotate() are forwarded to all of them.
> type CompositeAnnotator struct {
> 	// date of the component annotators.  This is precomputed, and returned by AnnotatorDate()
> ```

I think we need a better comment here, making it clear what the date means.
___
*[directory/directory.go, line 109 at r4](https://reviewable.io/reviews/m-lab/annotation-service/265#-Lk9Vs9a9qGPKlaHJi9d:-Lk9Vs9a9qGPKlaHJi9e:bk5qq7v) ([raw file](https://github.com/m-lab/annotation-service/blob/505786bebdcf039ab707c0d463579c445a7dc2b5/directory/directory.go#L109)):*
> ```Go
> 		return nil
> 	}
> 	ca := CompositeAnnotator{date: computerEarliestDate(annotators), annotators: annotators}
> ```

So here is my concern...
We use this date to choose the annotator to use.  Let's say that on July25, the most recent annotators are:
geo:  July 1, July 15
asn:  July 8, July 20, July 23

I think we end up with these composite annotators
date:  July1, geo: July1, asn: July8
date: July8, geo: July15, asn: July8
date: July15, geo: July15, asn: July20
date: July15, geo: July15, asn: July23

So, which dataset should we use?   Ideally, should use the one with July23 data in it.

Then, on July 26, we download a new geo annotator, and we add:
date: July 20, geo: July26, asn: July20

Then on July 27, Gardener reprocesses the July 25 data.  I uses the new July 20 annotator, which has a geo dataset from July 26.  So we are re-annotating July 25 with a dataset that did not exist on July 25.

How about instead, we actually tag each dataset with a start date and end date.  Then a composite dataset should be used for the interval that is the intersection of the component dataset intervals.  Then the 2018/06/01 dataset would look like:
download: 2018/06/01
start: 0001/01/01
end: 2018/07/01

And it would be used for all dates prior to 2018/07/01.
The bookkeeping is slightly more complicated, and in particular, we would have to update the end date of the most recent dataset when we download a new one.  But this would relieve the ambiguity about what the dates mean, so everything would be clear and easy to understand.

**Review by gfr10598 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/annotation-service/265)* status: 0 of 1 LGTMs obtained

___
*[directory/directory.go, line 109 at r4](https://reviewable.io/reviews/m-lab/annotation-service/265#-Lk9Vs9a9qGPKlaHJi9d:-Lk9YmvL8phtIOHra8vX:b-kreevw) ([raw file](https://github.com/m-lab/annotation-service/blob/505786bebdcf039ab707c0d463579c445a7dc2b5/directory/directory.go#L109)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

So here is my concern...
We use this date to choose the annotator to use.  Let's say that on July25, the most recent annotators are:
geo:  July 1, July 15
asn:  July 8, July 20, July 23

I think we end up with these composite annotators
date:  July1, geo: July1, asn: July8
date: July8, geo: July15, asn: July8
date: July15, geo: July15, asn: July20
date: July15, geo: July15, asn: July23

So, which dataset should we use?   Ideally, should use the one with July23 data in it.

Then, on July 26, we download a new geo annotator, and we add:
date: July 20, geo: July26, asn: July20

Then on July 27, Gardener reprocesses the July 25 data.  I uses the new July 20 annotator, which has a geo dataset from July 26.  So we are re-annotating July 25 with a dataset that did not exist on July 25.

How about instead, we actually tag each dataset with a start date and end date.  Then a composite dataset should be used for the interval that is the intersection of the component dataset intervals.  Then the 2018/06/01 dataset would look like:
download: 2018/06/01
start: 0001/01/01
end: 2018/07/01

And it would be used for all dates prior to 2018/07/01.
The bookkeeping is slightly more complicated, and in particular, we would have to update the end date of the most recent dataset when we download a new one.  But this would relieve the ambiguity about what the dates mean, so everything would be clear and easy to understand.

</blockquote></details>

BTW, I've thought for a while we should add the dataset date to the annotation, so that we know exactly what dataset was used for each annotation.  This would have made debugging this a lot easier, and might be useful to users to better understand any annotations that seem wrong or contradictory.

**Review by yachang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/annotation-service/265)* status: 0 of 1 LGTMs obtained

___
*[directory/directory.go, line 109 at r4](https://reviewable.io/reviews/m-lab/annotation-service/265#-Lk9Vs9a9qGPKlaHJi9d:-Lk9_ZfrArxEFGveEmTc:beqf80c) ([raw file](https://github.com/m-lab/annotation-service/blob/505786bebdcf039ab707c0d463579c445a7dc2b5/directory/directory.go#L109)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

BTW, I've thought for a while we should add the dataset date to the annotation, so that we know exactly what dataset was used for each annotation.  This would have made debugging this a lot easier, and might be useful to users to better understand any annotations that seem wrong or contradictory.
</blockquote></details>

The question is essentially: For a given date, do we have an optimal CA for it? 

The absolute optimal case is that we could have separate annotator selector for each type of annotation, which guaranteed each dataset used is optimal.

For current design which bundles different annotators together, the CA is optimal for the annotator that hold the earliest date (ASN_v4 in this case, and very close to geo for most of time after 2013). As long as ASN_v4 is more "dense" (or frequent than other annotation type, such as geo), the final output is very close to choose optimal annotator separately for each data type.

Your example is about the special handling of the last several CA, which was actually missing (I can add a TODO) in current implementation (I mentioned that in unittest, which has 3 entries in output instead of 4)

I like the idea to print out dates of all annotators in a CA. Will update the code for PrintAll(). But adding range of dates of CA and changing the logic for CA selection is a little bit overkill IMHO, given the fact that the sandbox Geolocation coverage back to 100% for 2017 after reprocessing and the difference between 2 months Geo Dataset is quite small based on my experience.

**Review by yachang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/annotation-service/265)* status: 0 of 1 LGTMs obtained

___
*[directory/directory.go, line 109 at r4](https://reviewable.io/reviews/m-lab/annotation-service/265#-Lk9Vs9a9qGPKlaHJi9d:-Lk9d0jI5a4C3LTxmDE5:b-7ejty1) ([raw file](https://github.com/m-lab/annotation-service/blob/505786bebdcf039ab707c0d463579c445a7dc2b5/directory/directory.go#L109)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

The question is essentially: For a given date, do we have an optimal CA for it? 

The absolute optimal case is that we could have separate annotator selector for each type of annotation, which guaranteed each dataset used is optimal.

For current design which bundles different annotators together, the CA is optimal for the annotator that hold the earliest date (ASN_v4 in this case, and very close to geo for most of time after 2013). As long as ASN_v4 is more "dense" (or frequent than other annotation type, such as geo), the final output is very close to choose optimal annotator separately for each data type.

Your example is about the special handling of the last several CA, which was actually missing (I can add a TODO) in current implementation (I mentioned that in unittest, which has 3 entries in output instead of 4)

I like the idea to print out dates of all annotators in a CA. Will update the code for PrintAll(). But adding range of dates of CA and changing the logic for CA selection is a little bit overkill IMHO, given the fact that the sandbox Geolocation coverage back to 100% for 2017 after reprocessing and the difference between 2 months Geo Dataset is quite small based on my experience.
</blockquote></details>

BTW: special handling of most recent dataset is low priority IMO, since Gardener will reprocess the data anyway when that dataset is not the latest any more.

**Review by gfr10598 — CHANGES_REQUESTED** [review]
:lgtm: 

> Reviewed 2 of 4 files at r4, 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/m-lab/annotation-service/265#-:-LkAMh4J3meeqkLsky2N:bg7igkv)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[directory/directory.go, line 109 at r4](https://reviewable.io/reviews/m-lab/annotation-service/265#-Lk9Vs9a9qGPKlaHJi9d:-Lk9q-8_5czkw08rZx6u:b-h9oxya) ([raw file](https://github.com/m-lab/annotation-service/blob/505786bebdcf039ab707c0d463579c445a7dc2b5/directory/directory.go#L109)):*
> The absolute optimal case is that we could have separate annotator selector for each type of annotation, which guaranteed each dataset used is optimal.
> For current design which bundles different annotators together, the CA is optimal for the annotator that hold 

The whole point of the composite annotators is to have all possible "optimal" annotators.  They shouldn't be a compromise.

Not convinced this is ideal, but let's get it into staging and discuss additional changes on monday.

**Review by gfr10598 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/annotation-service/265)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[directory/directory.go, line 41 at r4](https://reviewable.io/reviews/m-lab/annotation-service/265#-Lk9VXTN7XsNB-cNAQPn:-LkAMyGX2Tl4MAac1_B-:b3xsrgy) ([raw file](https://github.com/m-lab/annotation-service/blob/505786bebdcf039ab707c0d463579c445a7dc2b5/directory/directory.go#L41)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

I think we need a better comment here, making it clear what the date means.
</blockquote></details>

Can you do this first?

**Review by yachang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/annotation-service/265)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[directory/directory.go, line 41 at r4](https://reviewable.io/reviews/m-lab/annotation-service/265#-Lk9VXTN7XsNB-cNAQPn:-LkAR58z9YWiPgptMXYx:b-896fix) ([raw file](https://github.com/m-lab/annotation-service/blob/505786bebdcf039ab707c0d463579c445a7dc2b5/directory/directory.go#L41)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Can you do this first?
</blockquote></details>

Done.

**Pull request merged**
