### PR TITLE
Batch request implementation

### PR DESCRIPTION
**Pull request by jlm123hi**
The implementation and tests for batch validation.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/annotation-service/25)

### CODE REVIEW

**Comment by yachang** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[handler/handler.go, line 103 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/25#-KsPxK0upI5MvSeZHMX2:-KsPxK0upI5MvSeZHMX3:b-bwpemf) ([raw file](https://github.com/m-lab/annotation-service/blob/1657577abb57c93d836f1083ed3dd5c3ee9526ca/handler/handler.go#L103)):*
> ```Go
> 	responseMap := make(map[string]*schema.MetaData)
> 	for _, data := range dataSlice {
> 		responseMap[data.IP+strconv.FormatInt(data.Timestamp.Unix(), 36)] = GetMetadataForSingleIP(&data)
> ```

make 36 a const above

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/25)*

**Comment by yachang** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[handler/handler.go, line 154 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/25#-KsPxubn-jLqyjkuP0GN:-KsPxubn-jLqyjkuP0GO:b-l0qso7) ([raw file](https://github.com/m-lab/annotation-service/blob/1657577abb57c93d836f1083ed3dd5c3ee9526ca/handler/handler.go#L154)):*
> ```Go
> 	currentDataMutex.RLock()
> 	defer currentDataMutex.RUnlock()
> 	// Fake response
> ```

Will you update test code when you replace the fake response? If so, add a TODO in test file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/25)*

**Comment by jlm123hi** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[handler/handler.go, line 103 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/25#-KsPxK0upI5MvSeZHMX2:-KsPzFReCmvBCcYW970m:b-896fix) ([raw file](https://github.com/m-lab/annotation-service/blob/1657577abb57c93d836f1083ed3dd5c3ee9526ca/handler/handler.go#L103)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

make 36 a const above
</blockquote></details>

Done.

---

*[handler/handler.go, line 154 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/25#-KsPxubn-jLqyjkuP0GN:-KsPzIKF8j92SYdmoJRt:b-896fix) ([raw file](https://github.com/m-lab/annotation-service/blob/1657577abb57c93d836f1083ed3dd5c3ee9526ca/handler/handler.go#L154)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

Will you update test code when you replace the fake response? If so, add a TODO in test file.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/25)*

**Comment by yachang** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/25#-:-KsPzlr5jlvtPFGcdRRH:bnfp4nl)*

**Pull request merged**
