### PR TITLE
Location

### PR DESCRIPTION
**Pull request by shelbychen97**
reads from a zip reader 
creates a geolocation list

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/annotation-service/17)

### CODE REVIEW

**Comment by yachang** [comment]
Review status: 0 of 14 files reviewed at latest revision, 1 unresolved discussion.

---

*[parser/geo-ip.go, line 26 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/17#-KrqnWgxnB4A3y6p5iuI:-KrqnWgyP-Gyg-onw37a:b3cah1q) ([raw file](https://github.com/m-lab/annotation-service/blob/8b51c0313a67d03989deed375a0cf9d9a5fff35f/parser/geo-ip.go#L26)):*
> ```Go
> // Creates list for location databases
> func CreateLocationList(reader io.Reader) ([]LocationNode, map[int]int, error) {
> 	idMap := make(map[int]int, 200000)
> ```

make 200000 as a const at the top

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/17)*

**Comment by yachang** [comment]
Review status: 0 of 14 files reviewed at latest revision, 2 unresolved discussions.

---

*[parser/geo-ip.go, line 34 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/17#-KrqnocMT13WXYzrgsQb:-KrqnocMT13WXYzrgsQc:b-5d92d8) ([raw file](https://github.com/m-lab/annotation-service/blob/8b51c0313a67d03989deed375a0cf9d9a5fff35f/parser/geo-ip.go#L34)):*
> ```Go
> 	if err == io.EOF {
> 		log.Println("Empty file")
> 		return nil, nil, errors.New("Corrupted Data")
> ```

error message can be "empty input data"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/17)*

**Comment by yachang** [comment]
Review status: 0 of 14 files reviewed at latest revision, 3 unresolved discussions.

---

*[parser/geo-ip.go, line 43 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/17#-KrqoFTisJ6NFq2nOjWq:-KrqoFTisJ6NFq2nOjWr:b-dso88x) ([raw file](https://github.com/m-lab/annotation-service/blob/8b51c0313a67d03989deed375a0cf9d9a5fff35f/parser/geo-ip.go#L43)):*
> ```Go
> 		if len(record) != LocationNumColumns {
> 			log.Println("Incorrect number of columns in Location list")
> 			return nil, nil, errors.New("Corrupted Data")
> ```


errors.New("Corrupted Data: wrong number of columns")

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/17)*

**Comment by yachang** [comment]
Review status: 0 of 14 files reviewed at latest revision, 4 unresolved discussions.

---

*[parser/geo-ip.go, line 50 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/17#-KrqoM4mrW3Fz7APLisE:-KrqoM4mrW3Fz7APLisF:blesnyb) ([raw file](https://github.com/m-lab/annotation-service/blob/8b51c0313a67d03989deed375a0cf9d9a5fff35f/parser/geo-ip.go#L50)):*
> ```Go
> 			if len(record[0]) > 0 {
> 				log.Println("Geoname was a number")
> 				return nil, nil, errors.New("Corrupted Data")
> ```

errors.New("Corrupted Data: geoname should be a number")

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/17)*

**Comment by yachang** [comment]
Review status: 0 of 14 files reviewed at latest revision, 5 unresolved discussions.

---

*[parser/geo-ip.go, line 59 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/17#-KrqoSX9hUNRHMVwmaPz:-KrqoSX9hUNRHMVwmaQ-:b-7ropln) ([raw file](https://github.com/m-lab/annotation-service/blob/8b51c0313a67d03989deed375a0cf9d9a5fff35f/parser/geo-ip.go#L59)):*
> ```Go
> 			if len(record[11]) > 0 {
> 				log.Println("MetroCode is not a number")
> 				return nil, nil, errors.New("Corrupted Data")
> ```

ditto

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/17)*

**Comment by yachang** [comment]
Review status: 0 of 14 files reviewed at latest revision, 6 unresolved discussions.

---

*[parser/geo-ip.go, line 54 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/17#-KrqoUmPRysyoMpNkXAH:-KrqoUmPRysyoMpNkXAI:bptu2fx) ([raw file](https://github.com/m-lab/annotation-service/blob/8b51c0313a67d03989deed375a0cf9d9a5fff35f/parser/geo-ip.go#L54)):*
> ```Go
> 		}
> 		newNode.ContinentCode = record[2]
> 		newNode.CountryName = record[5]
> ```

validity check for the above 2 fields.  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/17)*

**Comment by yachang** [comment]
Review status: 0 of 14 files reviewed at latest revision, 7 unresolved discussions.

---

*[parser/geo-ip_test.go, line 61 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/17#-KrqpK_LPYUc4Iuc-vIH:-KrqpK_LPYUc4Iuc-vII:bug7fwq) ([raw file](https://github.com/m-lab/annotation-service/blob/8b51c0313a67d03989deed375a0cf9d9a5fff35f/parser/geo-ip_test.go#L61)):*
> ```Go
> 			locationList, idMap, err = parser.CreateLocationList(rc)
> 			if err != nil {
> 				log.Println(err)
> ```

The test should break here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/17)*

**Comment by shelbychen97** [comment]
Review status: 0 of 14 files reviewed at latest revision, 7 unresolved discussions.

---

*[parser/geo-ip.go, line 26 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/17#-KrqnWgxnB4A3y6p5iuI:-KrqqbS8hgtXHnMLc7AE:b-896fix) ([raw file](https://github.com/m-lab/annotation-service/blob/8b51c0313a67d03989deed375a0cf9d9a5fff35f/parser/geo-ip.go#L26)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

make 200000 as a const at the top
</blockquote></details>

Done.

---

*[parser/geo-ip.go, line 34 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/17#-KrqnocMT13WXYzrgsQb:-KrqqeiBT6pXXl1AHIJt:b-896fix) ([raw file](https://github.com/m-lab/annotation-service/blob/8b51c0313a67d03989deed375a0cf9d9a5fff35f/parser/geo-ip.go#L34)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

error message can be "empty input data"
</blockquote></details>

Done.

---

*[parser/geo-ip.go, line 43 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/17#-KrqoFTisJ6NFq2nOjWq:-KrqtJFhtmAXRHHm7Tzr:b-896fix) ([raw file](https://github.com/m-lab/annotation-service/blob/8b51c0313a67d03989deed375a0cf9d9a5fff35f/parser/geo-ip.go#L43)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

errors.New("Corrupted Data: wrong number of columns")
</blockquote></details>

Done.

---

*[parser/geo-ip.go, line 50 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/17#-KrqoM4mrW3Fz7APLisE:-KrqtIRhoG10wVRH3OGW:b-896fix) ([raw file](https://github.com/m-lab/annotation-service/blob/8b51c0313a67d03989deed375a0cf9d9a5fff35f/parser/geo-ip.go#L50)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

errors.New("Corrupted Data: geoname should be a number")
</blockquote></details>

Done.

---

*[parser/geo-ip.go, line 54 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/17#-KrqoUmPRysyoMpNkXAH:-KrqtHvqkab02_1FUZeC:b-896fix) ([raw file](https://github.com/m-lab/annotation-service/blob/8b51c0313a67d03989deed375a0cf9d9a5fff35f/parser/geo-ip.go#L54)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

validity check for the above 2 fields.  
</blockquote></details>

Done.

---

*[parser/geo-ip.go, line 59 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/17#-KrqoSX9hUNRHMVwmaPz:-KrqtHML8ncQ_dUqmGdv:b-896fix) ([raw file](https://github.com/m-lab/annotation-service/blob/8b51c0313a67d03989deed375a0cf9d9a5fff35f/parser/geo-ip.go#L59)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

---

*[parser/geo-ip_test.go, line 61 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/17#-KrqpK_LPYUc4Iuc-vIH:-Krr-Wcb6N6OLUQO9dhs:b-896fix) ([raw file](https://github.com/m-lab/annotation-service/blob/8b51c0313a67d03989deed375a0cf9d9a5fff35f/parser/geo-ip_test.go#L61)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

The test should break here.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/17)*

**Comment by yachang** [comment]
Review status: 0 of 14 files reviewed at latest revision, 8 unresolved discussions.

---

*[parser/geo-ip.go, line 14 at r3](https://reviewable.io:443/reviews/m-lab/annotation-service/17#-Ks44IFrXG8ohk8v34u6:-Ks44IFrXG8ohk8v34u7:b-3wikq2) ([raw file](https://github.com/m-lab/annotation-service/blob/f8cd117734ecb6d1a8895c357057537d5600eae2/parser/geo-ip.go#L14)):*
> ```Go
> )
> 
> const mapMax = 200000
> ```

const naming by golang style

uses camel-case. The first letter is uppercase or lowercase depending on whether you want to export the constant.

So make mapMax and LocationNumColumns the same naming style here. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/17)*

**Comment by yachang** [comment]
Review status: 0 of 14 files reviewed at latest revision, 8 unresolved discussions.

---

*[parser/geo-ip.go, line 34 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/17#-KrqnocMT13WXYzrgsQb:-Ks45UNRdnOeLFksl_Id:b-y3epze) ([raw file](https://github.com/m-lab/annotation-service/blob/8b51c0313a67d03989deed375a0cf9d9a5fff35f/parser/geo-ip.go#L34)):*
<details><summary><i>Previously, shelbychen97 (Shelby Chen ) wrote…</i></summary><blockquote>

Done.
</blockquote></details>


errors.New("empty input Data")

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/17)*

**Comment by shelbychen97** [comment]
Review status: 0 of 14 files reviewed at latest revision, 5 unresolved discussions.

---

*[parser/geo-ip.go, line 34 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/17#-KrqnocMT13WXYzrgsQb:-Ks4mgDJb2oq7-4_6X2L:beyjxml) ([raw file](https://github.com/m-lab/annotation-service/blob/8b51c0313a67d03989deed375a0cf9d9a5fff35f/parser/geo-ip.go#L34)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

errors.New("empty input Data")
</blockquote></details>

Done. -- question: what is the convention for errors? should it be 
"empty Input Data" or "Empty Input Data"?

---

*[parser/geo-ip.go, line 54 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/17#-KrqoUmPRysyoMpNkXAH:-Ks4oDqH4G-LSjAwTN1L:b-896fix) ([raw file](https://github.com/m-lab/annotation-service/blob/8b51c0313a67d03989deed375a0cf9d9a5fff35f/parser/geo-ip.go#L54)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

if match {
...
}
</blockquote></details>

Done.

---

*[parser/geo-ip.go, line 14 at r3](https://reviewable.io:443/reviews/m-lab/annotation-service/17#-Ks44IFrXG8ohk8v34u6:-Ks4lVbz-oU-H7Hg7qDl:b-896fix) ([raw file](https://github.com/m-lab/annotation-service/blob/f8cd117734ecb6d1a8895c357057537d5600eae2/parser/geo-ip.go#L14)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

const naming by golang style

uses camel-case. The first letter is uppercase or lowercase depending on whether you want to export the constant.

So make mapMax and LocationNumColumns the same naming style here. 
</blockquote></details>

Done.

---

*[parser/geo-ip_test.go, line 97 at r3](https://reviewable.io:443/reviews/m-lab/annotation-service/17#-Ks46cWS4NwsMQYXGFeh:-Ks4mauLt342tFlR3QjU:baj16hq) ([raw file](https://github.com/m-lab/annotation-service/blob/f8cd117734ecb6d1a8895c357057537d5600eae2/parser/geo-ip_test.go#L97)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

check the error message here if error is not nil
</blockquote></details>

More clarification about this comment would be helpful. If error is nil, the test should fail. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/17)*

**Comment by yachang** [comment]
Review status: 0 of 14 files reviewed at latest revision, 3 unresolved discussions.

---

*[parser/geo-ip.go, line 34 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/17#-KrqnocMT13WXYzrgsQb:-Ks5HonM-c5QMN6OB04i:bemkemq) ([raw file](https://github.com/m-lab/annotation-service/blob/8b51c0313a67d03989deed375a0cf9d9a5fff35f/parser/geo-ip.go#L34)):*
<details><summary><i>Previously, shelbychen97 (Shelby Chen ) wrote…</i></summary><blockquote>

Done. -- question: what is the convention for errors? should it be 
"empty Input Data" or "Empty Input Data"?
</blockquote></details>

"Empty Input Data"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/17)*

**Comment by yachang** [comment]
Review status: 0 of 14 files reviewed at latest revision, 2 unresolved discussions.

---

*[parser/geo-ip_test.go, line 97 at r3](https://reviewable.io:443/reviews/m-lab/annotation-service/17#-Ks46cWS4NwsMQYXGFeh:-Ks5Hzuz2Fhg6ymaYnhx:bjujj6p) ([raw file](https://github.com/m-lab/annotation-service/blob/f8cd117734ecb6d1a8895c357057537d5600eae2/parser/geo-ip_test.go#L97)):*
<details><summary><i>Previously, shelbychen97 (Shelby Chen ) wrote…</i></summary><blockquote>

More clarification about this comment would be helpful. If error is nil, the test should fail. 
</blockquote></details>

The error should be something not nil, but it could be many different kinds of error.

I would like to see the expected error indicating there is a missing row. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/17)*

**Comment by yachang** [comment]
:lgtm:

---

Review status: 0 of 14 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/17#-:-Ks5cL-3wKeIWXYwcLFp:bnfp4nl)*

**Pull request merged**
