### PR TITLE
Geolatest

### PR DESCRIPTION
**Pull request by shelbychen97**
Make parser compatible with GeoLatest zip files
Creates GeoLite1 IPv4 lists

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/annotation-service/24)

### CODE REVIEW

**Comment by yachang** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[parser/geo-ip.go, line 22 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/24#-KsJepLPl3MEhDCaxfi5:-KsJepLQe2s4lqx0IEP4:bmhgbc) ([raw file](https://github.com/m-lab/annotation-service/blob/04b0b61508d60c76408c29e07e7d0fbea8134834/parser/geo-ip.go#L22)):*
> ```Go
> const mapMax = 200000
> 
> // IPNode IPv4 and Block IPv6 databases
> ```

The document here is confusing:

You delete "IPAdress string", which mean that for both IP v4 and Ip v6, it is represented by block?

Please clarify

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/24)*

**Comment by yachang** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[parser/geo-ip.go, line 54 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/24#-KsJgPxS6xup2-wKiEcn:-KsJgPxS6xup2-wKiEco:b-37146) ([raw file](https://github.com/m-lab/annotation-service/blob/04b0b61508d60c76408c29e07e7d0fbea8134834/parser/geo-ip.go#L54)):*
> ```Go
> 	}
> 
> 	if file == "GeoLiteCity-Blocks.csv" {
> ```

Make the file name a const string

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/24)*

**Comment by yachang** [comment]
Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[parser/geo-ip.go, line 93 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/24#-KsJi3foNp24DMccqfe7:-KsJi3foNp24DMccqfe8:b-qun77t) ([raw file](https://github.com/m-lab/annotation-service/blob/04b0b61508d60c76408c29e07e7d0fbea8134834/parser/geo-ip.go#L93)):*
> ```Go
> 			newNode.LocationIndex = index
> 			list = append(list, newNode)
> 		} else if file == "GeoLite2-City-Blocks-IPv4.csv" || file == "GeoLite2-City-Blocks-IPv6.csv" {
> ```

use switch as top level logic

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/24)*

**Comment by yachang** [comment]
Review status: 0 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[parser/geo-ip.go, line 19 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/24#-KsJiWEzzrcvyGxA9fVW:-KsJiWEzzrcvyGxA9fVX:b6u35bw) ([raw file](https://github.com/m-lab/annotation-service/blob/04b0b61508d60c76408c29e07e7d0fbea8134834/parser/geo-ip.go#L19)):*
> ```Go
> const ipNumColumnsGlite2 = 10
> const locationNumColumnsGlite2 = 13
> const ipNumColumnsGliteLatest = 3
> ```

Update README as well

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/24)*

**Comment by yachang** [comment]
Review status: 0 of 5 files reviewed at latest revision, 5 unresolved discussions.

---

*[parser/geo-ip.go, line 126 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/24#-KsJjdfn_vDBFO-6eSXR:-KsJjdfn_vDBFO-6eSXS:b62ljr4) ([raw file](https://github.com/m-lab/annotation-service/blob/04b0b61508d60c76408c29e07e7d0fbea8134834/parser/geo-ip.go#L126)):*
> ```Go
> }
> 
> // Converts integer to IPv4
> ```

validity check?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/24)*

**Comment by yachang** [comment]
Review status: 0 of 5 files reviewed at latest revision, 6 unresolved discussions.

---

*[parser/geo-ip.go, line 133 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/24#-KsJkDUAwkeaTJKAKRTY:-KsJkDUAwkeaTJKAKRTZ:b-zxw4m) ([raw file](https://github.com/m-lab/annotation-service/blob/04b0b61508d60c76408c29e07e7d0fbea8134834/parser/geo-ip.go#L133)):*
> ```Go
> }
> 
> // Finds the smallest and largest net.IP from a CIDR range
> ```

more specific documentation for cidr, bound, better give some sample strings.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/24)*

**Comment by yachang** [comment]
Review status: 0 of 5 files reviewed at latest revision, 7 unresolved discussions.

---

*[parser/geo-ip.go, line 136 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/24#-KsJk__mYinGFq7UWs_u:-KsJk__mYinGFq7UWs_v:b30y66g) ([raw file](https://github.com/m-lab/annotation-service/blob/04b0b61508d60c76408c29e07e7d0fbea8134834/parser/geo-ip.go#L136)):*
> ```Go
> func RangeCIDR(cidr, bound string) net.IP {
> 	ip, ipnet, _ := net.ParseCIDR(cidr)
> 	if bound == "low" {
> ```

if the bound can be "low" or not, it can be bool type, instead of string

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/24)*

**Comment by yachang** [comment]
Review status: 0 of 5 files reviewed at latest revision, 8 unresolved discussions.

---

*[parser/geo-ip.go, line 153 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/24#-KsJktg8gi32k-HI00sD:-KsJktg8gi32k-HI00sE:bu3gior) ([raw file](https://github.com/m-lab/annotation-service/blob/04b0b61508d60c76408c29e07e7d0fbea8134834/parser/geo-ip.go#L153)):*
> ```Go
> 	return ip
> }
> ```

missing documentation

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/24)*

**Comment by shelbychen97** [comment]
Review status: 0 of 6 files reviewed at latest revision, 8 unresolved discussions.

---

*[parser/geo-ip.go, line 19 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/24#-KsJiWEzzrcvyGxA9fVW:-KsKk-c7p3xubDX5cx0g:b-896fix) ([raw file](https://github.com/m-lab/annotation-service/blob/04b0b61508d60c76408c29e07e7d0fbea8134834/parser/geo-ip.go#L19)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

Update README as well
</blockquote></details>

Done.

---

*[parser/geo-ip.go, line 22 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/24#-KsJepLPl3MEhDCaxfi5:-KsKZAMyEsE2yR29pFrX:b-896fix) ([raw file](https://github.com/m-lab/annotation-service/blob/04b0b61508d60c76408c29e07e7d0fbea8134834/parser/geo-ip.go#L22)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

The document here is confusing:

You delete "IPAdress string", which mean that for both IP v4 and Ip v6, it is represented by block?

Please clarify
</blockquote></details>

Done.

---

*[parser/geo-ip.go, line 54 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/24#-KsJgPxS6xup2-wKiEcn:-KsKZKSwWoI83Rq8dTI2:b-896fix) ([raw file](https://github.com/m-lab/annotation-service/blob/04b0b61508d60c76408c29e07e7d0fbea8134834/parser/geo-ip.go#L54)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

Make the file name a const string
</blockquote></details>

Done.

---

*[parser/geo-ip.go, line 93 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/24#-KsJi3foNp24DMccqfe7:-KsJvi_VnA4Hrj7WzQ7g:b-896fix) ([raw file](https://github.com/m-lab/annotation-service/blob/04b0b61508d60c76408c29e07e7d0fbea8134834/parser/geo-ip.go#L93)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

use switch as top level logic
</blockquote></details>

Done.

---

*[parser/geo-ip.go, line 126 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/24#-KsJjdfn_vDBFO-6eSXR:-KsKed_LJaBPSe7lgGvA:b-896fix) ([raw file](https://github.com/m-lab/annotation-service/blob/04b0b61508d60c76408c29e07e7d0fbea8134834/parser/geo-ip.go#L126)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

validity check?
</blockquote></details>

Done.

---

*[parser/geo-ip.go, line 133 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/24#-KsJkDUAwkeaTJKAKRTY:-KsKeeUBr_iOIb34KdYz:b-896fix) ([raw file](https://github.com/m-lab/annotation-service/blob/04b0b61508d60c76408c29e07e7d0fbea8134834/parser/geo-ip.go#L133)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

more specific documentation for cidr, bound, better give some sample strings.
</blockquote></details>

Done.

---

*[parser/geo-ip.go, line 136 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/24#-KsJk__mYinGFq7UWs_u:-KsKSQa3t4TwMV9eadbM:b-896fix) ([raw file](https://github.com/m-lab/annotation-service/blob/04b0b61508d60c76408c29e07e7d0fbea8134834/parser/geo-ip.go#L136)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

if the bound can be "low" or not, it can be bool type, instead of string
</blockquote></details>

Done.

---

*[parser/geo-ip.go, line 153 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/24#-KsJktg8gi32k-HI00sD:-KsKetgxagQWoFknFS56:b-896fix) ([raw file](https://github.com/m-lab/annotation-service/blob/04b0b61508d60c76408c29e07e7d0fbea8134834/parser/geo-ip.go#L153)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

missing documentation
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/24)*

**Comment by yachang** [comment]
Review status: 0 of 6 files reviewed at latest revision, 5 unresolved discussions.

---

*[parser/geo-ip.go, line 139 at r2](https://reviewable.io:443/reviews/m-lab/annotation-service/24#-KsOgJAND327FL4zjUlI:-KsOgJAOEFgIRgCz4W2J:b-gzsytg) ([raw file](https://github.com/m-lab/annotation-service/blob/8e83a7852aabc176212185cbfbcbb1fad5917256/parser/geo-ip.go#L139)):*
> ```Go
> 		log.Println("Provided IP should be a number")
> 		return nil, errors.New("Inputed string cannot be converted to a number")
> 	}
> ```

Not all integer can be converted to IP address.

For IP v4, there is a range, check that range.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/24)*

**Comment by yachang** [comment]
Review status: 0 of 6 files reviewed at latest revision, 6 unresolved discussions.

---

*[parser/geo-ip.go, line 134 at r3](https://reviewable.io:443/reviews/m-lab/annotation-service/24#-KsOyYH7Dd8Y3nK2ZMT7:-KsOyYH7Dd8Y3nK2ZMT8:b-t42za9) ([raw file](https://github.com/m-lab/annotation-service/blob/09fc21ed83cb583bff4bf5ce0ca3258e13eca555/parser/geo-ip.go#L134)):*
> ```Go
> }
> 
> // Converts integer to net.IP
> ```

nit pick: to IP v4 addess

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/24)*

**Comment by yachang** [comment]
:lgtm:

---

Review status: 0 of 6 files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/24#-:-KsOydF4fnqSniw9IyRB:bnfp4nl)*

**Pull request merged**
