### PR TITLE
creates list from .csv file 

### PR DESCRIPTION
**Pull request by shelbychen97**
parses CSV file and returns a list of nodes

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/annotation-service/7)

### CODE REVIEW

**Comment by gfr10598** [comment]
Review status: 0 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[geo-ip.go, line 1 at r6](https://reviewable.io:443/reviews/m-lab/annotation-service/7#-KqUdNPmnSzbTIeEH_Nx:-KqUdNPmnSzbTIeEH_Ny:btz4wpn) ([raw file](https://github.com/m-lab/annotation-service/blob/38df76133dcc343b9d3ee5d846f4c631331b231c/geo-ip.go#L1)):*
> ```Go
> package annotator
> ```

Let's make this package loader

---

*[geo-ip.go, line 28 at r6](https://reviewable.io:443/reviews/m-lab/annotation-service/7#-KqUdUIXubGrq8Tec5wS:-KqUdUIY7-xJTzzdb1z5:b-45c5x7) ([raw file](https://github.com/m-lab/annotation-service/blob/38df76133dcc343b9d3ee5d846f4c631331b231c/geo-ip.go#L28)):*
> ```Go
> 
> //Reads file from given reader and creates a node list
> func createList(reader io.Reader) ([]Node, error) {
> ```

Export this by naming it CreateList

---

*[geo-ip_test.go, line 1 at r6](https://reviewable.io:443/reviews/m-lab/annotation-service/7#-KqUdX_9xH69hc6ssL0r:-KqUdX_9xH69hc6ssL0s:bhexfin) ([raw file](https://github.com/m-lab/annotation-service/blob/38df76133dcc343b9d3ee5d846f4c631331b231c/geo-ip_test.go#L1)):*
> ```Go
> package annotator
> ```

Make this package loader_test

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/7)*

**Comment by gfr10598** [comment]
Reviewed 2 of 7 files at r1, 1 of 1 files at r2, 2 of 2 files at r4, 3 of 3 files at r6.
Review status: 8 of 9 files reviewed at latest revision, 4 unresolved discussions.

---

*[annotator.yaml, line 1 at r6](https://reviewable.io:443/reviews/m-lab/annotation-service/7#-KqUdoXcwCjyXG82voWY:-KqUbtzIzUkoGxzfBFti:b-u56vkk) ([raw file](https://github.com/m-lab/annotation-service/blob/38df76133dcc343b9d3ee5d846f4c631331b231c/annotator.yaml#L1)):*
> ```YAML
> runtime: go
> ```

Can we drop this file for this PR?  Or is it required?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/7)*

**Comment by shelbychen97** [comment]
Review status: 5 of 8 files reviewed at latest revision, 4 unresolved discussions.

---

*[loader/geo-ip.go, line 1 at r6](https://reviewable.io:443/reviews/m-lab/annotation-service/7#-KqUdNPmnSzbTIeEH_Nx:-KqUnauJzr2YonCYdhGU:b-896fix) ([raw file](https://github.com/m-lab/annotation-service/blob/38df76133dcc343b9d3ee5d846f4c631331b231c/loader/geo-ip.go#L1)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Let's make this package loader
</blockquote></details>

Done.

---

*[loader/geo-ip.go, line 28 at r6](https://reviewable.io:443/reviews/m-lab/annotation-service/7#-KqUdUIXubGrq8Tec5wS:-KqUnbinWC82xRsLS2kM:b-896fix) ([raw file](https://github.com/m-lab/annotation-service/blob/38df76133dcc343b9d3ee5d846f4c631331b231c/loader/geo-ip.go#L28)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Export this by naming it CreateList
</blockquote></details>

Done.

---

*[annotator.yaml, line 1 at r6](https://reviewable.io:443/reviews/m-lab/annotation-service/7#-KqUdoXcwCjyXG82voWY:-KqUncTUV8QqaiTUR9O6:b-896fix) ([raw file](https://github.com/m-lab/annotation-service/blob/38df76133dcc343b9d3ee5d846f4c631331b231c/annotator.yaml#L1)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Can we drop this file for this PR?  Or is it required?
</blockquote></details>

Done.

---

*[geo-ip_test.go, line 1 at r6](https://reviewable.io:443/reviews/m-lab/annotation-service/7#-KqUdX_9xH69hc6ssL0r:-KqUno4cDoe6EoApG6Pq:b-896fix) ([raw file](https://github.com/m-lab/annotation-service/blob/38df76133dcc343b9d3ee5d846f4c631331b231c/geo-ip_test.go#L1)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Make this package loader_test
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/7)*

**Comment by gfr10598** [comment]
:lgtm:

---

Reviewed 1 of 7 files at r1, 5 of 7 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/7#-:-KqUob8UwZsTdPXcg_UJ:bnfp4nl)*

**Pull request merged**
