### PR TITLE
Linear Search glite2

### PR DESCRIPTION
**Pull request by shelbychen97**
- tests for GeoLite2 IPv4 and IPv6 databases 
- tests for overlapping ranges

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/annotation-service/28)

### CODE REVIEW

**Comment by yachang** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[parser/geo-ip.go, line 105 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/28#-KseGUvSVjX-5InzpsC3:-KseGUvTJ6yaBa4hRjvl:b-1a4dkz) ([raw file](https://github.com/m-lab/annotation-service/blob/9cb03da43f7522a172ee5c6cff1bb682589d813d/parser/geo-ip.go#L105)):*
> ```Go
> 			newNode.IPAddressHigh = highIp
> 			var index int
> 			index, err = validateGeoId(record[1], idMap)
> ```

Is there any way to check record[1] format before this line? 

Also add documentation for logic behind this and following 3 lines.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/28)*

**Comment by yachang** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[parser/geo-ip.go, line 183 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/28#-KseH6x-G85uZsWdRSlT:-KseH6x-G85uZsWdRSlU:b-2vnyuc) ([raw file](https://github.com/m-lab/annotation-service/blob/9cb03da43f7522a172ee5c6cff1bb682589d813d/parser/geo-ip.go#L183)):*
> ```Go
> 	geonameId, err := strconv.Atoi(gnid)
> 	if err != nil {
> 		return 0, errors.New("Corrupted Data: geonameID should be a number")
> ```

Add documentation, such as sample data for input params.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/28)*

**Comment by yachang** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[parser/geo-ip.go, line 182 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/28#-KseHy11KRYrNq081hNg:-KseHy11KRYrNq081hNh:b-mgez9q) ([raw file](https://github.com/m-lab/annotation-service/blob/9cb03da43f7522a172ee5c6cff1bb682589d813d/parser/geo-ip.go#L182)):*
> ```Go
> func validateGeoId(gnid string, idMap map[int]int) (int, error) {
> 	geonameId, err := strconv.Atoi(gnid)
> 	if err != nil {
> ```

why do you delete logging here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/28)*

**Comment by yachang** [comment]
Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[parser/geo-ip.go, line 243 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/28#-KseIOfprC2Cxm9c2-4S:-KseIOfprC2Cxm9c2-4T:b1wzrk4) ([raw file](https://github.com/m-lab/annotation-service/blob/9cb03da43f7522a172ee5c6cff1bb682589d813d/parser/geo-ip.go#L243)):*
> ```Go
> 		if err != nil {
> 			if len(record[0]) > 0 {
> 				log.Println("GeonameID should be a number ", record[0])
> ```

You miss %s here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/28)*

**Comment by yachang** [comment]
Review status: 0 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[parser/geo-ip.go, line 259 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/28#-KseIfeX8yQg7mxdU_ur:-KseIfeX8yQg7mxdU_us:b-7ropln) ([raw file](https://github.com/m-lab/annotation-service/blob/9cb03da43f7522a172ee5c6cff1bb682589d813d/parser/geo-ip.go#L259)):*
> ```Go
> 			newNode.CountryName = record[5]
> 		} else {
> 			log.Println("Country name should be letters only : ", record[5])
> ```

ditto

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/28)*

**Comment by yachang** [comment]
Review status: 0 of 4 files reviewed at latest revision, 6 unresolved discussions.

---

*[parser/geo-ip.go, line 276 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/28#-KseJLdY4H9lKaufDSes:-KseJLdY4H9lKaufDSet:bp5a80c) ([raw file](https://github.com/m-lab/annotation-service/blob/9cb03da43f7522a172ee5c6cff1bb682589d813d/parser/geo-ip.go#L276)):*
> ```Go
> }
> 
> // Returns nil of two nodes are equal
> ```

typo: if

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/28)*

**Comment by gfr10598** [comment]
*[parser/geo-ip.go, line 243 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/28#-KseIOfprC2Cxm9c2-4S:-KseKzT8N9lprJgaTMoJ:b-68h42a) ([raw file](https://github.com/m-lab/annotation-service/blob/9cb03da43f7522a172ee5c6cff1bb682589d813d/parser/geo-ip.go#L243)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

You miss %s here
</blockquote></details>

This is correct.  Println vs Printf

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/28)*

**Comment by gfr10598** [comment]
*[parser/geo-ip.go, line 276 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/28#-KseLPjdsn168eaRSG_Q:-KseLPjdsn168eaRSG_R:br57jxd) ([raw file](https://github.com/m-lab/annotation-service/blob/9cb03da43f7522a172ee5c6cff1bb682589d813d/parser/geo-ip.go#L276)):*
> ```Go
> }
> 
> // Returns nil of two nodes are equal
> ```

This should go in _test file?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/28)*

**Comment by gfr10598** [comment]
*[parser/geo-ip.go, line 276 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/28#-KseLPjdsn168eaRSG_Q:-KseLkG_v3g-QjThV6p9:bxt8vu9) ([raw file](https://github.com/m-lab/annotation-service/blob/9cb03da43f7522a172ee5c6cff1bb682589d813d/parser/geo-ip.go#L276)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

This should go in _test file?
</blockquote></details>

Ah - I see it is used in two different test files.  Just add a comment here about that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/28)*

**Comment by gfr10598** [comment]
Review status: 0 of 4 files reviewed at latest revision, 9 unresolved discussions.

---

*[parser/geo-ip.go, line 18 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/28#-KseJHMoqzs1kZEG-wnS:-KseJHMoqzs1kZEG-wnT:b-7e85x1) ([raw file](https://github.com/m-lab/annotation-service/blob/9cb03da43f7522a172ee5c6cff1bb682589d813d/parser/geo-ip.go#L18)):*
> ```Go
> )
> 
> const ipNumColumnsGlite2 = 10
> ```

Make this a const block:
const (
  locationNum...
  ...
)

---

*[parser/geo-ip.go, line 20 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/28#-KseJdIdM9O-ap3w10wm:-KseJdIdM9O-ap3w10wn:bhm5bs) ([raw file](https://github.com/m-lab/annotation-service/blob/9cb03da43f7522a172ee5c6cff1bb682589d813d/parser/geo-ip.go#L20)):*
> ```Go
> const ipNumColumnsGlite2 = 10
> const locationNumColumnsGlite2 = 13
> const locationNumColumnsGliteLatest = 9
> ```

What is the meaning of the Latest suffix?  Is this just GLite1 ?
It might make sense to group together constants related to GLite1 and GLite2 separately.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/28)*

**Comment by yachang** [comment]
Review status: 0 of 4 files reviewed at latest revision, 10 unresolved discussions.

---

*[parser/geo-ip_test.go, line 283 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/28#-KseM2MyM-yeQffDsyju:-KseM2MyM-yeQffDsyjv:bhl6dnm) ([raw file](https://github.com/m-lab/annotation-service/blob/9cb03da43f7522a172ee5c6cff1bb682589d813d/parser/geo-ip_test.go#L283)):*
> ```Go
> }
> 
> func isEqualLocLists(list, listComp []parser.LocationNode) error {
> ```

Add func documentation

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/28)*

**Comment by yachang** [comment]
Review status: 0 of 4 files reviewed at latest revision, 11 unresolved discussions.

---

*[search/geo-search.go, line 19 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/28#-KseM66TiePNfd67zQMJ:-KseM66TiePNfd67zQMK:b-kvk2ln) ([raw file](https://github.com/m-lab/annotation-service/blob/9cb03da43f7522a172ee5c6cff1bb682589d813d/search/geo-search.go#L19)):*
> ```Go
> 	if userIP == nil {
> 		log.Println("Inputed IP string could not be parsed to net.IP")
> 		return lastNode, errors.New("Ivalid search IP")
> ```

Invalid IP

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/28)*

**Comment by shelbychen97** [comment]
Review status: 0 of 4 files reviewed at latest revision, 11 unresolved discussions.

---

*[parser/geo-ip.go, line 18 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/28#-KseJHMoqzs1kZEG-wnS:-KsegOceTIwLC6ZXyzwC:b-896fix) ([raw file](https://github.com/m-lab/annotation-service/blob/9cb03da43f7522a172ee5c6cff1bb682589d813d/parser/geo-ip.go#L18)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Make this a const block:
const (
  locationNum...
  ...
)
</blockquote></details>

Done.

---

*[parser/geo-ip.go, line 20 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/28#-KseJdIdM9O-ap3w10wm:-KsegMGvXq-u9oInmLmQ:b-3y8lgz) ([raw file](https://github.com/m-lab/annotation-service/blob/9cb03da43f7522a172ee5c6cff1bb682589d813d/parser/geo-ip.go#L20)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

What is the meaning of the Latest suffix?  Is this just GLite1 ?
It might make sense to group together constants related to GLite1 and GLite2 separately.

</blockquote></details>

Latest = GLite1 

---

*[parser/geo-ip.go, line 105 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/28#-KseGUvSVjX-5InzpsC3:-KseZRU3-9eTHzxfsE4a:b-561gb0) ([raw file](https://github.com/m-lab/annotation-service/blob/9cb03da43f7522a172ee5c6cff1bb682589d813d/parser/geo-ip.go#L105)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

Is there any way to check record[1] format before this line? 

Also add documentation for logic behind this and following 3 lines.
</blockquote></details>

Validation is done inside the validateGeoId method

---

*[parser/geo-ip.go, line 182 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/28#-KseHy11KRYrNq081hNg:-KsebGkPUGWz97-WpAmG:b-hmjdjg) ([raw file](https://github.com/m-lab/annotation-service/blob/9cb03da43f7522a172ee5c6cff1bb682589d813d/parser/geo-ip.go#L182)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

why do you delete logging here?
</blockquote></details>

Added back 

---

*[parser/geo-ip.go, line 183 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/28#-KseH6x-G85uZsWdRSlT:-KsegEHIU6PY6v1D9uM5:b-896fix) ([raw file](https://github.com/m-lab/annotation-service/blob/9cb03da43f7522a172ee5c6cff1bb682589d813d/parser/geo-ip.go#L183)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

Add documentation, such as sample data for input params.
</blockquote></details>

Done.

---

*[parser/geo-ip.go, line 259 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/28#-KseIfeX8yQg7mxdU_ur:-Kseg9XlJc-kUVv_RvTj:bpm1di5) ([raw file](https://github.com/m-lab/annotation-service/blob/9cb03da43f7522a172ee5c6cff1bb682589d813d/parser/geo-ip.go#L259)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

ditto
</blockquote></details>

no %s needed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/28)*

**Comment by gfr10598** [comment]
*[parser/geo-ip.go, line 20 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/28#-KseJdIdM9O-ap3w10wm:-KsiRDBA5yI7Q-jRuQc7:brsg97g) ([raw file](https://github.com/m-lab/annotation-service/blob/9cb03da43f7522a172ee5c6cff1bb682589d813d/parser/geo-ip.go#L20)):*
<details><summary><i>Previously, shelbychen97 (Shelby Chen ) wrote…</i></summary><blockquote>

Latest = GLite1 
</blockquote></details>

I'd suggest replacing it with GLite1 then.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/28)*

**Comment by yachang** [comment]
Review status: 0 of 4 files reviewed at latest revision, 11 unresolved discussions.

---

*[parser/geo-ip.go, line 190 at r2](https://reviewable.io:443/reviews/m-lab/annotation-service/28#-KsiSYwHlEBueevxYRCV:-KsiSYwHlEBueevxYRCW:bag1y00) ([raw file](https://github.com/m-lab/annotation-service/blob/b24ec544a5b9e02d7331290e845b23a5e99ab0bd/parser/geo-ip.go#L190)):*
> ```Go
> //	17:     4,
> // }
> // validateGeoId("17",locationIdMap) would return 2.
> ```

return (2, nil) ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/28)*

**Comment by gfr10598** [comment]
Review status: 0 of 4 files reviewed at latest revision, 13 unresolved discussions.

---

*[parser/geo-ip.go, line 156 at r2](https://reviewable.io:443/reviews/m-lab/annotation-service/28#-KsiRmP0NNJocYUzb4_0:-KsiRmP0NNJocYUzb4_1:bxucbit) ([raw file](https://github.com/m-lab/annotation-service/blob/b24ec544a5b9e02d7331290e845b23a5e99ab0bd/parser/geo-ip.go#L156)):*
> ```Go
> 	binary.BigEndian.PutUint32(ip, uint32(num))
> 	// Matches the Golang's internal IPv4 structure
> 	ip = append([]byte{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0xff, 0xff}, ip...)
> ```

Check net library to see if there is a function that does this for you.

---

*[parser/geo-ip.go, line 191 at r2](https://reviewable.io:443/reviews/m-lab/annotation-service/28#-KsiRclpyhYLWpU_EE3x:-KsiRclpyhYLWpU_EE3y:bg12ija) ([raw file](https://github.com/m-lab/annotation-service/blob/b24ec544a5b9e02d7331290e845b23a5e99ab0bd/parser/geo-ip.go#L191)):*
> ```Go
> // }
> // validateGeoId("17",locationIdMap) would return 2.
> func validateGeoId(gnid string, idMap map[int]int) (int, error) {
> ```

rename to lookupGeoId.  It does validation, but its primary function is lookup.

Also please add a TODO to add error metrics.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/28)*

**Comment by shelbychen97** [comment]
Review status: 0 of 4 files reviewed at latest revision, 12 unresolved discussions.

---

*[parser/geo-ip.go, line 20 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/28#-KseJdIdM9O-ap3w10wm:-KsiX_v2f4GhnvtaUJHc:b-896fix) ([raw file](https://github.com/m-lab/annotation-service/blob/9cb03da43f7522a172ee5c6cff1bb682589d813d/parser/geo-ip.go#L20)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

I'd suggest replacing it with GLite1 then.
</blockquote></details>

Done.

---

*[parser/geo-ip.go, line 156 at r2](https://reviewable.io:443/reviews/m-lab/annotation-service/28#-KsiRmP0NNJocYUzb4_0:-KsiZ5tfzpTO3uacIZEr:b6hznlf) ([raw file](https://github.com/m-lab/annotation-service/blob/b24ec544a5b9e02d7331290e845b23a5e99ab0bd/parser/geo-ip.go#L156)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Check net library to see if there is a function that does this for you.
</blockquote></details>

In person help with this would be great 

---

*[parser/geo-ip.go, line 190 at r2](https://reviewable.io:443/reviews/m-lab/annotation-service/28#-KsiSYwHlEBueevxYRCV:-KsiZTmvjE8HtXcw6uqg:b-896fix) ([raw file](https://github.com/m-lab/annotation-service/blob/b24ec544a5b9e02d7331290e845b23a5e99ab0bd/parser/geo-ip.go#L190)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

return (2, nil) ?
</blockquote></details>

Done.

---

*[parser/geo-ip.go, line 191 at r2](https://reviewable.io:443/reviews/m-lab/annotation-service/28#-KsiRclpyhYLWpU_EE3x:-KsiZTK2KXerjJKJCk3x:b-896fix) ([raw file](https://github.com/m-lab/annotation-service/blob/b24ec544a5b9e02d7331290e845b23a5e99ab0bd/parser/geo-ip.go#L191)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

rename to lookupGeoId.  It does validation, but its primary function is lookup.

Also please add a TODO to add error metrics.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/28)*

**Comment by gfr10598** [comment]
*[parser/geo-ip.go, line 156 at r2](https://reviewable.io:443/reviews/m-lab/annotation-service/28#-KsiRmP0NNJocYUzb4_0:-KsicLQSIbKt4Pq_uMpy:bxsfg15) ([raw file](https://github.com/m-lab/annotation-service/blob/b24ec544a5b9e02d7331290e845b23a5e99ab0bd/parser/geo-ip.go#L156)):*
<details><summary><i>Previously, shelbychen97 (Shelby Chen ) wrote…</i></summary><blockquote>

In person help with this would be great 
</blockquote></details>

Hmm - sorry WFH today.  Can do a VC if you like.

Start by skimming through the functions available here, and see if they are useful in your code.
https://golang.org/pkg/net/#IP

In general, when there are *standard* library functions that do what you need, it is better to use them rather than writing your own code.  This primarily avoids bugs (particularly in edge cases), and also, usually, makes code more readable, because when you write explicit code, people may guess that you are doing something special that the standard library call can't do for you.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/28)*

**Comment by gfr10598** [comment]
Review status: 0 of 4 files reviewed at latest revision, 13 unresolved discussions.

---

*[parser/geo-ip.go, line 70 at r3](https://reviewable.io:443/reviews/m-lab/annotation-service/28#-KsidRRhiHwX-Cb21fMZ:-KsidRRhiHwX-Cb21fM_:bnvtzgn) ([raw file](https://github.com/m-lab/annotation-service/blob/a996b9b7db2b2e3ee5b1bc9789aa2c0cbfbae127/parser/geo-ip.go#L70)):*
> ```Go
> 		}
> 	}
> 	for {
> ```

We talked about making separate functions for Geo1 and Geo2.   But for now, try a simpler refactoring - just reverse the order here of the switch and for statements:

switch {
case strings.HasPrefix(...):
    for {
        record, err := r.Read()
        ...
    }
case strings.HasPrefix(...):
    for {
        record, err := r.Read()
        ...
    }

Later extraction of the individual functions will be trivial.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/28)*

**Comment by shelbychen97** [comment]
Review status: 0 of 4 files reviewed at latest revision, 12 unresolved discussions.

---

*[parser/geo-ip.go, line 156 at r2](https://reviewable.io:443/reviews/m-lab/annotation-service/28#-KsiRmP0NNJocYUzb4_0:-KsjAXL4C7X-YH5dQYDw:bne60h9) ([raw file](https://github.com/m-lab/annotation-service/blob/b24ec544a5b9e02d7331290e845b23a5e99ab0bd/parser/geo-ip.go#L156)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Hmm - sorry WFH today.  Can do a VC if you like.

Start by skimming through the functions available here, and see if they are useful in your code.
https://golang.org/pkg/net/#IP

In general, when there are *standard* library functions that do what you need, it is better to use them rather than writing your own code.  This primarily avoids bugs (particularly in edge cases), and also, usually, makes code more readable, because when you write explicit code, people may guess that you are doing something special that the standard library call can't do for you.

</blockquote></details>

I think i found something that works! 

---

*[parser/geo-ip.go, line 70 at r3](https://reviewable.io:443/reviews/m-lab/annotation-service/28#-KsidRRhiHwX-Cb21fMZ:-KsjAWn8O5cSQtSKdQF6:b-896fix) ([raw file](https://github.com/m-lab/annotation-service/blob/a996b9b7db2b2e3ee5b1bc9789aa2c0cbfbae127/parser/geo-ip.go#L70)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

We talked about making separate functions for Geo1 and Geo2.   But for now, try a simpler refactoring - just reverse the order here of the switch and for statements:

switch {
case strings.HasPrefix(...):
    for {
        record, err := r.Read()
        ...
    }
case strings.HasPrefix(...):
    for {
        record, err := r.Read()
        ...
    }

Later extraction of the individual functions will be trivial.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/28)*

**Comment by gfr10598** [comment]
Review status: 0 of 4 files reviewed at latest revision, 10 unresolved discussions.

---

*[parser/geo-ip.go, line 156 at r2](https://reviewable.io:443/reviews/m-lab/annotation-service/28#-KsiRmP0NNJocYUzb4_0:-KsjHug3ic-TXX7JMZE8:b9a3l07) ([raw file](https://github.com/m-lab/annotation-service/blob/b24ec544a5b9e02d7331290e845b23a5e99ab0bd/parser/geo-ip.go#L156)):*
<details><summary><i>Previously, shelbychen97 (Shelby Chen ) wrote…</i></summary><blockquote>

I think i found something that works! 
</blockquote></details>

Looks good!

---

*[parser/geo-ip.go, line 70 at r3](https://reviewable.io:443/reviews/m-lab/annotation-service/28#-KsidRRhiHwX-Cb21fMZ:-KsjJ3Zvt0o8QqIzn7PI:bszm2f7) ([raw file](https://github.com/m-lab/annotation-service/blob/a996b9b7db2b2e3ee5b1bc9789aa2c0cbfbae127/parser/geo-ip.go#L70)):*
<details><summary><i>Previously, shelbychen97 (Shelby Chen ) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Much better!

---

*[parser/geo-ip.go, line 62 at r4](https://reviewable.io:443/reviews/m-lab/annotation-service/28#-KsjICln2PMPTJ5fhMNT:-KsjICln2PMPTJ5fhMNU:b-2267l5) ([raw file](https://github.com/m-lab/annotation-service/blob/a617d2a8801921080f8ae3d060811971e19ecd4e/parser/geo-ip.go#L62)):*
> ```Go
> 	switch {
> 	case strings.HasPrefix(file, gLite1Prefix):
> 		_, err := r.Read()
> ```

Comment what this Read does.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/28)*

**Comment by shelbychen97** [comment]
Review status: 0 of 4 files reviewed at latest revision, 8 unresolved discussions.

---

*[parser/geo-ip.go, line 62 at r4](https://reviewable.io:443/reviews/m-lab/annotation-service/28#-KsjICln2PMPTJ5fhMNT:-KsjOVrQ3IorXDNKIH4J:b-896fix) ([raw file](https://github.com/m-lab/annotation-service/blob/a617d2a8801921080f8ae3d060811971e19ecd4e/parser/geo-ip.go#L62)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Comment what this Read does.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/28)*

**Comment by gfr10598** [comment]
:lgtm:  - once Ya has responded on all her comments, and you expand on the second line comment.

Nice job turning these reviews around quickly!

---

Reviewed 1 of 4 files at r1, 1 of 3 files at r2, 1 of 2 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[parser/geo-ip.go, line 62 at r4](https://reviewable.io:443/reviews/m-lab/annotation-service/28#-KsjICln2PMPTJ5fhMNT:-KsjOgax_HGVxJE3aXIM:b-36x97d) ([raw file](https://github.com/m-lab/annotation-service/blob/a617d2a8801921080f8ae3d060811971e19ecd4e/parser/geo-ip.go#L62)):*
<details><summary><i>Previously, shelbychen97 (Shelby Chen ) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Please expand - what does the second line contain?  Should we verify that it has the expected contents?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/28#-:-KsjOviUK398S23cpBD3:b-8tzgoy)*

**Comment by shelbychen97** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[parser/geo-ip.go, line 156 at r2](https://reviewable.io:443/reviews/m-lab/annotation-service/28#-KsiRmP0NNJocYUzb4_0:-KsjOYqXk3VI8h9prk5-:b-896fix) ([raw file](https://github.com/m-lab/annotation-service/blob/b24ec544a5b9e02d7331290e845b23a5e99ab0bd/parser/geo-ip.go#L156)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Looks good!
</blockquote></details>

Done.

---

*[parser/geo-ip.go, line 62 at r4](https://reviewable.io:443/reviews/m-lab/annotation-service/28#-KsjICln2PMPTJ5fhMNT:-KsjS678UfHdXnG0TC_1:b-q5qmrk) ([raw file](https://github.com/m-lab/annotation-service/blob/a617d2a8801921080f8ae3d060811971e19ecd4e/parser/geo-ip.go#L62)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Please expand - what does the second line contain?  Should we verify that it has the expected contents?
</blockquote></details>

2nd line contains the labels for each column 
["locID","country","region","postalCode","longitude","latitude","metrocode","areaCode"]

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/28)*

**Comment by yachang** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[parser/geo-ip.go, line 243 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/28#-KseIOfprC2Cxm9c2-4S:-KsjUABjNxEaTnrBNhDd:bb6un1j) ([raw file](https://github.com/m-lab/annotation-service/blob/9cb03da43f7522a172ee5c6cff1bb682589d813d/parser/geo-ip.go#L243)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

This is correct.  Println vs Printf
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/28)*

**Comment by yachang** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[parser/geo-ip.go, line 276 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/28#-KseJLdY4H9lKaufDSes:-KsjUD5H6nEUwJuc5oi1:bb6un1j) ([raw file](https://github.com/m-lab/annotation-service/blob/9cb03da43f7522a172ee5c6cff1bb682589d813d/parser/geo-ip.go#L276)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

typo: if
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/28)*

**Comment by yachang** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[parser/geo-ip_test.go, line 283 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/28#-KseM2MyM-yeQffDsyju:-KsjUGFD4R6ej0vvVBki:bb6un1j) ([raw file](https://github.com/m-lab/annotation-service/blob/9cb03da43f7522a172ee5c6cff1bb682589d813d/parser/geo-ip_test.go#L283)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

Add func documentation
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/28)*

**Comment by gfr10598** [comment]
*[parser/geo-ip.go, line 62 at r4](https://reviewable.io:443/reviews/m-lab/annotation-service/28#-KsjICln2PMPTJ5fhMNT:-KsjUhu0ffURzTIkNqiG:b-belaqj) ([raw file](https://github.com/m-lab/annotation-service/blob/a617d2a8801921080f8ae3d060811971e19ecd4e/parser/geo-ip.go#L62)):*
<details><summary><i>Previously, shelbychen97 (Shelby Chen ) wrote…</i></summary><blockquote>

2nd line contains the labels for each column 
["locID","country","region","postalCode","longitude","latitude","metrocode","areaCode"]


</blockquote></details>

so...
// Skip 2nd line, which contains column labels.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/28)*

**Comment by shelbychen97** [comment]
Review status: 2 of 7 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[parser/geo-ip.go, line 62 at r4](https://reviewable.io:443/reviews/m-lab/annotation-service/28#-KsjICln2PMPTJ5fhMNT:-Ksjd1eU4AB_nOLLIZ0j:b5n1ylc) ([raw file](https://github.com/m-lab/annotation-service/blob/a617d2a8801921080f8ae3d060811971e19ecd4e/parser/geo-ip.go#L62)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

so...
// Skip 2nd line, which contains column labels.
</blockquote></details>

added a check as well

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/28)*

**Pull request merged**
