### PR TITLE
Parse Geolite1 

### PR DESCRIPTION
**Pull request by shelbychen97**
- reads in Geolite 1 
- create Location node and Glite1 helper node with information to be later stored in IP node 
- Populates IP node with info from Glite1 helper node

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/annotation-service/34)

### CODE REVIEW

**Comment by gfr10598** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[parser/geo-ip.go, line 53 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/34#-Kso-0lwd9zy59wkBU7B:-Kso-0lxIB0REXXcvhyE:b-r2xfkx) ([raw file](https://github.com/m-lab/annotation-service/blob/a43ed5af8f1a82e87232c3e483010a95a72e8d7c/parser/geo-ip.go#L53)):*
> ```Go
> // Glite1HelpNode defines IPNode data defined inside
> // GeoLite1 Location files
> type GLite1HelpNode struct {
> ```

Make this lower case so it isn't exported.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/34)*

**Comment by gfr10598** [comment]
Let's sit together this afternoon and do some refactoring.  I'd like to separate the GLite1 and GLite2 into separate files for both prod and test code.  Feel free to start without me if you like.  8-)

---

Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/34#-:-Kso1YlJSeqUES5YwdFY:byglqjd)*

**Comment by gfr10598** [comment]
Looks like you never added the new files to git.  Please add them now.

---

Reviewed 1 of 5 files at r2.
Review status: 1 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/34#-:-KssfT3LtfXUykvLeL-A:b-fy7cv1)*

**Comment by gfr10598** [comment]
Removing geo-ip.go broke the build, so I added it back.
However, something is still broken.  Take a look and see if you can sort it out.  We will want to get travis tests passing before merging this.

I'll do further review later in the day.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/34#-:-Kst-8li5HNKfVs3buxl:b-ppj3f2)*

**Comment by gfr10598** [comment]
Reviewed 1 of 5 files at r1, 2 of 5 files at r2.
Review status: 4 of 10 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[parser/g1_test.go, line 14 at r4](https://reviewable.io:443/reviews/m-lab/annotation-service/34#-KsswK6F1-xjeqrWN-OO:-KsswK6GG8fv47fYnHwS:bufoj8g) ([raw file](https://github.com/m-lab/annotation-service/blob/a3d11b28850e0f8e5b90bc797d417fcbda45fdc0/parser/g1_test.go#L14)):*
> ```Go
> )
> 
> func TestIPGLite1(t *testing.T) {
> ```

Add comment to move this test to g1_whitebox_test.go, or remove it.  This will allow you to make the low level LoadIP function non-exported.

---

*[parser/geo-g1.go, line 27 at r4](https://reviewable.io:443/reviews/m-lab/annotation-service/34#-Ksswpp931qlQLcYNLP3:-Ksswpp931qlQLcYNLP4:b-752cmo) ([raw file](https://github.com/m-lab/annotation-service/blob/a3d11b28850e0f8e5b90bc797d417fcbda45fdc0/parser/geo-g1.go#L27)):*
> ```Go
> 
> // Create Location list, map, and Glite1HelpNode for GLite1 databases
> // GLiteHelpNode contains information that populate fields in IPNode
> ```

... contains information to help populate ...

---

*[parser/geo-g1.go, line 46 at r4](https://reviewable.io:443/reviews/m-lab/annotation-service/34#-KsswvETCEOF9tykCsmi:-KsswvETCEOF9tykCsmj:ba9bfkk) ([raw file](https://github.com/m-lab/annotation-service/blob/a3d11b28850e0f8e5b90bc797d417fcbda45fdc0/parser/geo-g1.go#L46)):*
> ```Go
> 	for {
> 		record, err := r.Read()
> 		if err == io.EOF {
> ```

First check for err != nil, then for EOF, else log and return an error.  Probably same applies to all of the Load... function in both g1 and g2.

---

*[parser/geo-g2.go, line 20 at r4](https://reviewable.io:443/reviews/m-lab/annotation-service/34#-KssvlmsZjl45C9nVdZb:-KssvlmsZjl45C9nVdZc:b-yz10q9) ([raw file](https://github.com/m-lab/annotation-service/blob/a3d11b28850e0f8e5b90bc797d417fcbda45fdc0/parser/geo-g2.go#L20)):*
> ```Go
> 	locationNumColumnsGlite2 = 13
> 	gLite2Prefix             = "GeoLite2-City"
> 	GeoLite2BlocksFilenameIP4 = "GeoLite2-City-Blocks-IPv4.csv"  // Filename of ipv4 blocks file
> ```

These can be lower case now?

---

*[parser/geo-ip.go, line 48 at r4](https://reviewable.io:443/reviews/m-lab/annotation-service/34#-KsszaZuvpxt-JVAHS36:-KsszaZuvpxt-JVAHS37:b8au046) ([raw file](https://github.com/m-lab/annotation-service/blob/a3d11b28850e0f8e5b90bc797d417fcbda45fdc0/parser/geo-ip.go#L48)):*
> ```Go
> 
> // Verify column length
> func checkColumnLength(record []string, size int) error {
> ```

This is poorly named.  checkNumColumns instead

---

*[parser/geo-ip.go, line 63 at r4](https://reviewable.io:443/reviews/m-lab/annotation-service/34#-KssxwogG9PdnhKuzOv9:-KssxwogG9PdnhKuzOvA:b8s0p1e) ([raw file](https://github.com/m-lab/annotation-service/blob/a3d11b28850e0f8e5b90bc797d417fcbda45fdc0/parser/geo-ip.go#L63)):*
> ```Go
> 		return nil, errors.New("Inputed string cannot be converted to a number")
> 	}
> 	ft := float64(num)
> ```

// Add TODO to get rid of the floating point.

---

*[parser/geo-ip.go, line 68 at r4](https://reviewable.io:443/reviews/m-lab/annotation-service/34#-Kssy9B9duGj0-TRHWYL:-Kssy9B9duGj0-TRHWYM:bg5whdv) ([raw file](https://github.com/m-lab/annotation-service/blob/a3d11b28850e0f8e5b90bc797d417fcbda45fdc0/parser/geo-ip.go#L68)):*
> ```Go
> 	}
> 	ip := make(net.IP, 4)
> 	binary.BigEndian.PutUint32(ip, uint32(num))
> ```

This line needs a comment.  What is it doing?

---

*[parser/geo-ip.go, line 112 at r4](https://reviewable.io:443/reviews/m-lab/annotation-service/34#-KsszoSyZAaATrh3mVpo:-KsszoSyZAaATrh3mVpp:b2ar9wq) ([raw file](https://github.com/m-lab/annotation-service/blob/a3d11b28850e0f8e5b90bc797d417fcbda45fdc0/parser/geo-ip.go#L112)):*
> ```Go
> 		return str, nil
> 	} else {
> 		log.Println(field, "should be all capitals and no numbers")
> ```

This says no numbers, but the pattern allows digits.  ??

---

*[search/geo-search_test.go, line 167 at r4](https://reviewable.io:443/reviews/m-lab/annotation-service/34#-Kssw3M29hvy7r5dSCLd:-Kssw3M3qW4ykL9oYqGH:bljjgvk) ([raw file](https://github.com/m-lab/annotation-service/blob/a3d11b28850e0f8e5b90bc797d417fcbda45fdc0/search/geo-search_test.go#L167)):*
> ```Go
> 	defer rcIPv6.Close()
> 
> 	ipv6, err := parser.LoadIPListGLite2(rcIPv6, idMap)
> ```

Add TODO to update these tests to use the high level data loader functions, instead of the low level funcs.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/34)*

**Comment by shelbychen97** [comment]
Review status: 9 of 10 files reviewed at latest revision, 14 unresolved discussions, some commit checks failed.

---

*[parser/geo-ip.go, line 53 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/34#-Kso-0lwd9zy59wkBU7B:-KsuFQ0ncj4e2KKnnh9s:b8q6zb1) ([raw file](https://github.com/m-lab/annotation-service/blob/a43ed5af8f1a82e87232c3e483010a95a72e8d7c/parser/geo-ip.go#L53)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Make this lower case so it isn't exported.
</blockquote></details>

Which line is this comment referring to? 

---

*[parser/geo-ip.go, line 112 at r4](https://reviewable.io:443/reviews/m-lab/annotation-service/34#-KsszoSyZAaATrh3mVpo:-KsuITwt4Yn5H_a1DfXa:bdxefeg) ([raw file](https://github.com/m-lab/annotation-service/blob/a3d11b28850e0f8e5b90bc797d417fcbda45fdc0/parser/geo-ip.go#L112)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

This says no numbers, but the pattern allows digits.  ??
</blockquote></details>

SORRY!!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/34)*

**Comment by gfr10598** [comment]
Review status: 4 of 10 files reviewed at latest revision, 16 unresolved discussions, some commit checks failed.

---

*[parser/geo-g1.go, line 55 at r6](https://reviewable.io:443/reviews/m-lab/annotation-service/34#-KsuNFGK-pw2Yh1NvCgz:-KsuNFGK-pw2Yh1NvCh-:b-yhfdge) ([raw file](https://github.com/m-lab/annotation-service/blob/b0e6ed45731988ed7b6074d61c78ee6cc738effd/parser/geo-g1.go#L55)):*
> ```Go
> 			if err == io.EOF {
> 				break
> 			}
> ```

Should have 
} else {
  log error
  return error
}

---

*[parser/geo-g1.go, line 56 at r6](https://reviewable.io:443/reviews/m-lab/annotation-service/34#-KsuNBmHGrt1N8fuBPyI:-KsuNBmHGrt1N8fuBPyJ:b-cdo0f8) ([raw file](https://github.com/m-lab/annotation-service/blob/b0e6ed45731988ed7b6074d61c78ee6cc738effd/parser/geo-g1.go#L56)):*
> ```Go
> 				break
> 			}
> 			if len(record) != locationNumColumnsGlite1 {
> ```

Here and below should be outside the if err != nil

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/34)*

**Comment by gfr10598** [comment]
Review status: 4 of 10 files reviewed at latest revision, 16 unresolved discussions, some commit checks failed.

---

*[parser/geo-ip.go, line 53 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/34#-Kso-0lwd9zy59wkBU7B:-KsuNep_iOKea4L6rk8-:b8g5ik1) ([raw file](https://github.com/m-lab/annotation-service/blob/a43ed5af8f1a82e87232c3e483010a95a72e8d7c/parser/geo-ip.go#L53)):*
<details><summary><i>Previously, shelbychen97 (Shelby Chen ) wrote…</i></summary><blockquote>

Which line is this comment referring to? 
</blockquote></details>

This is an old comment about GLite1HelpNode.  There is a little tab in upper right corner of the comment indicating which revision it was made on.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/34)*

**Comment by shelbychen97** [comment]
Review status: 2 of 10 files reviewed at latest revision, 17 unresolved discussions, some commit checks failed.

---

*[parser/geo-g1.go, line 56 at r6](https://reviewable.io:443/reviews/m-lab/annotation-service/34#-KsuNBmHGrt1N8fuBPyI:-KsxhrpOJ7tI15VL4sS-:b-dbms12) ([raw file](https://github.com/m-lab/annotation-service/blob/b0e6ed45731988ed7b6074d61c78ee6cc738effd/parser/geo-g1.go#L56)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Here and below should be outside the if err != nil
</blockquote></details>

I did some digging and the Read() function does it's own column length check so it will throw an error if the columns don't match r.FieldsPerRecord

---

*[parser/geo-ip.go, line 61 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/34#-KsxiJ_MDep_ia0x4pVM:-KsxiJ_MDep_ia0x4pVN:b-8dxopa) ([raw file](https://github.com/m-lab/annotation-service/blob/a43ed5af8f1a82e87232c3e483010a95a72e8d7c/parser/geo-ip.go#L61)):*
> 
{

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/34)*

**Comment by gfr10598** [comment]
Reviewed 2 of 6 files at r6, 2 of 5 files at r7.
Review status: 6 of 10 files reviewed at latest revision, 17 unresolved discussions, some commit checks failed.

---

*[parser/geo-g1.go, line 27 at r4](https://reviewable.io:443/reviews/m-lab/annotation-service/34#-Ksswpp931qlQLcYNLP3:-KtMWHiBR0IwcZYVYK65:bb747uk) ([raw file](https://github.com/m-lab/annotation-service/blob/a3d11b28850e0f8e5b90bc797d417fcbda45fdc0/parser/geo-g1.go#L27)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

... contains information to help populate ...
</blockquote></details>

Did you hit Done for this one and next two?

---

*[parser/geo-g1.go, line 25 at r5](https://reviewable.io:443/reviews/m-lab/annotation-service/34#-Ksu0W2ZB0t7_vCDFn6p:-KtMWAHQFCxIegyGHVo4:b2l9ib6) ([raw file](https://github.com/m-lab/annotation-service/blob/5ad70b45e4e45e00900d97bb0bac5d8fd8a51b7e/parser/geo-g1.go#L25)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Add TODO to add equivalent of LoadGeoLite2 that does all the work.
</blockquote></details>

fix small typo?

---

*[parser/geo-g1.go, line 93 at r5](https://reviewable.io:443/reviews/m-lab/annotation-service/34#-Ksu0vOxVitWAMwpinXF:-KtMWsULXa_zXisFT5Pl:b-896fig) ([raw file](https://github.com/m-lab/annotation-service/blob/5ad70b45e4e45e00900d97bb0bac5d8fd8a51b7e/parser/geo-g1.go#L93)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

go fmt.
</blockquote></details>

Done?

---

*[parser/geo-g1.go, line 56 at r6](https://reviewable.io:443/reviews/m-lab/annotation-service/34#-KsuNBmHGrt1N8fuBPyI:-KtMWnCgSvVTU0xqx0PP:bpv8zh9) ([raw file](https://github.com/m-lab/annotation-service/blob/b0e6ed45731988ed7b6074d61c78ee6cc738effd/parser/geo-g1.go#L56)):*
<details><summary><i>Previously, shelbychen97 (Shelby Chen ) wrote…</i></summary><blockquote>

I did some digging and the Read() function does it's own column length check so it will throw an error if the columns don't match r.FieldsPerRecord
</blockquote></details>

So you don't need the len(record) check?  Go ahead and remove it?

---

*[parser/geo-g1.go, line 55 at r7](https://reviewable.io:443/reviews/m-lab/annotation-service/34#-KtMWXUdSN_xgItGqdSt:-KtMWXUdSN_xgItGqdSu:by57jxc) ([raw file](https://github.com/m-lab/annotation-service/blob/cbaca7e2dc005d1a5a883110fb21f648cbc9c9ce/parser/geo-g1.go#L55)):*
> ```Go
> 			if err == io.EOF {
> 				break
> 			}
> ```

The else should be right here, after the break

      break
   } else {
      log
      return
   }
   if len(record) != ...

---

*[parser/geo-g1.go, line 149 at r7](https://reviewable.io:443/reviews/m-lab/annotation-service/34#-KtMX6xx7j-Jo2MDod3M:-KtMX6xy27j6jTPm6jos:bxdnpih) ([raw file](https://github.com/m-lab/annotation-service/blob/cbaca7e2dc005d1a5a883110fb21f648cbc9c9ce/parser/geo-g1.go#L149)):*
> ```Go
> 
> // Converts integer to net.IPv4
> func int2ip(str string) (net.IP, error) {
> ```

intToIPv4 ?

---

*[parser/geo-g2.go, line 20 at r4](https://reviewable.io:443/reviews/m-lab/annotation-service/34#-KssvlmsZjl45C9nVdZb:-KtMXEdNit4ZOiljraky:b-896fig) ([raw file](https://github.com/m-lab/annotation-service/blob/a3d11b28850e0f8e5b90bc797d417fcbda45fdc0/parser/geo-g2.go#L20)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

These can be lower case now?
</blockquote></details>

Done?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/34)*

**Comment by shelbychen97** [comment]
Review status: 6 of 10 files reviewed at latest revision, 17 unresolved discussions, some commit checks failed.

---

*[parser/g1_test.go, line 14 at r4](https://reviewable.io:443/reviews/m-lab/annotation-service/34#-KsswK6F1-xjeqrWN-OO:-KtImvGLxp-ALdBzYaE3:b-896fix) ([raw file](https://github.com/m-lab/annotation-service/blob/a3d11b28850e0f8e5b90bc797d417fcbda45fdc0/parser/g1_test.go#L14)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Add comment to move this test to g1_whitebox_test.go, or remove it.  This will allow you to make the low level LoadIP function non-exported.
</blockquote></details>

Done.

---

*[parser/geo-g1.go, line 27 at r4](https://reviewable.io:443/reviews/m-lab/annotation-service/34#-Ksswpp931qlQLcYNLP3:-KtMYDxLsrOUK_OVefcr:b-896fix) ([raw file](https://github.com/m-lab/annotation-service/blob/a3d11b28850e0f8e5b90bc797d417fcbda45fdc0/parser/geo-g1.go#L27)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Did you hit Done for this one and next two?
</blockquote></details>

Done.

---

*[parser/geo-g1.go, line 46 at r4](https://reviewable.io:443/reviews/m-lab/annotation-service/34#-KsswvETCEOF9tykCsmi:-KtMYGslg_opSZwSh5Dg:b-896fix) ([raw file](https://github.com/m-lab/annotation-service/blob/a3d11b28850e0f8e5b90bc797d417fcbda45fdc0/parser/geo-g1.go#L46)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

First check for err != nil, then for EOF, else log and return an error.  Probably same applies to all of the Load... function in both g1 and g2.
</blockquote></details>

Done.

---

*[parser/geo-g1.go, line 25 at r5](https://reviewable.io:443/reviews/m-lab/annotation-service/34#-Ksu0W2ZB0t7_vCDFn6p:-KtMYEENWrhXwB2RYRcO:b-896fix) ([raw file](https://github.com/m-lab/annotation-service/blob/5ad70b45e4e45e00900d97bb0bac5d8fd8a51b7e/parser/geo-g1.go#L25)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

fix small typo?
</blockquote></details>

Done.

---

*[parser/geo-g1.go, line 93 at r5](https://reviewable.io:443/reviews/m-lab/annotation-service/34#-Ksu0vOxVitWAMwpinXF:-KtMgb1nbOp0nmAsrZYh:b-896fix) ([raw file](https://github.com/m-lab/annotation-service/blob/5ad70b45e4e45e00900d97bb0bac5d8fd8a51b7e/parser/geo-g1.go#L93)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Done?
</blockquote></details>

Done.

---

*[parser/geo-g1.go, line 128 at r5](https://reviewable.io:443/reviews/m-lab/annotation-service/34#-Ksu14OIIPzntm6M_zJV:-KtMh3n2Q8_QNq2D8AkS:b-896fix) ([raw file](https://github.com/m-lab/annotation-service/blob/5ad70b45e4e45e00900d97bb0bac5d8fd8a51b7e/parser/geo-g1.go#L128)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Does this test do anything useful?  I'm guessing it would be fine to just copy the zeros.
</blockquote></details>

Done.

---

*[parser/geo-g1.go, line 56 at r6](https://reviewable.io:443/reviews/m-lab/annotation-service/34#-KsuNBmHGrt1N8fuBPyI:-KtMgZncIzI-Mk8JaYy4:b-896fix) ([raw file](https://github.com/m-lab/annotation-service/blob/b0e6ed45731988ed7b6074d61c78ee6cc738effd/parser/geo-g1.go#L56)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

So you don't need the len(record) check?  Go ahead and remove it?
</blockquote></details>

Done.

---

*[parser/geo-g1.go, line 55 at r7](https://reviewable.io:443/reviews/m-lab/annotation-service/34#-KtMWXUdSN_xgItGqdSt:-KtMZOVETQg0LUDh_JAS:b-896fix) ([raw file](https://github.com/m-lab/annotation-service/blob/cbaca7e2dc005d1a5a883110fb21f648cbc9c9ce/parser/geo-g1.go#L55)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

The else should be right here, after the break

      break
   } else {
      log
      return
   }
   if len(record) != ...
</blockquote></details>

Done.

---

*[parser/geo-g1.go, line 149 at r7](https://reviewable.io:443/reviews/m-lab/annotation-service/34#-KtMX6xx7j-Jo2MDod3M:-KtMhOQwc6oV6AG2kASE:b-896fix) ([raw file](https://github.com/m-lab/annotation-service/blob/cbaca7e2dc005d1a5a883110fb21f648cbc9c9ce/parser/geo-g1.go#L149)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

intToIPv4 ?
</blockquote></details>

Done.

---

*[parser/geo-g2.go, line 20 at r4](https://reviewable.io:443/reviews/m-lab/annotation-service/34#-KssvlmsZjl45C9nVdZb:-KtMhPi8-SudJOODyTAJ:b-896fix) ([raw file](https://github.com/m-lab/annotation-service/blob/a3d11b28850e0f8e5b90bc797d417fcbda45fdc0/parser/geo-g2.go#L20)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Done?
</blockquote></details>

Done.

---

*[parser/geo-g2.go, line 145 at r5](https://reviewable.io:443/reviews/m-lab/annotation-service/34#-Kstzk8ohvHJaQwGeM6b:-KtMhQ_dcmv7bY1C-Snh:b-896fix) ([raw file](https://github.com/m-lab/annotation-service/blob/5ad70b45e4e45e00900d97bb0bac5d8fd8a51b7e/parser/geo-g2.go#L145)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

go fmt.
</blockquote></details>

Done.

---

*[parser/geo-ip.go, line 61 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/34#-KsxiJ_MDep_ia0x4pVM:-KtMhYKqW7RzCbj-jz7F:b-896fix) ([raw file](https://github.com/m-lab/annotation-service/blob/a43ed5af8f1a82e87232c3e483010a95a72e8d7c/parser/geo-ip.go#L61)):*
<details><summary><i>Previously, shelbychen97 (Shelby Chen ) wrote…</i></summary><blockquote>

> 
{

</blockquote></details>

Done.

---

*[parser/geo-ip.go, line 63 at r4](https://reviewable.io:443/reviews/m-lab/annotation-service/34#-KssxwogG9PdnhKuzOv9:-KtMhVyer71sQL5zTbK_:b-896fix) ([raw file](https://github.com/m-lab/annotation-service/blob/a3d11b28850e0f8e5b90bc797d417fcbda45fdc0/parser/geo-ip.go#L63)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

// Add TODO to get rid of the floating point.
</blockquote></details>

Done.

---

*[parser/geo-ip.go, line 68 at r4](https://reviewable.io:443/reviews/m-lab/annotation-service/34#-Kssy9B9duGj0-TRHWYL:-KtMhWEXOFJDnjDmHUWC:b-896fix) ([raw file](https://github.com/m-lab/annotation-service/blob/a3d11b28850e0f8e5b90bc797d417fcbda45fdc0/parser/geo-ip.go#L68)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

This line needs a comment.  What is it doing?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/34)*

**Comment by gfr10598** [comment]
Review status: 6 of 10 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[parser/geo-g1.go, line 49 at r8](https://reviewable.io:443/reviews/m-lab/annotation-service/34#-KtMwKJNq92lwGngtUNg:-KtMwKJNq92lwGngtUNh:bckaz4x) ([raw file](https://github.com/m-lab/annotation-service/blob/58910d8feb891cb7726ba7b93ab4adfad82dabc6/parser/geo-g1.go#L49)):*
> ```Go
> 		return nil, nil, nil, errors.New("Empty input data")
> 	}
> 	r.FieldsPerRecord = locationNumColumnsGlite1
> ```

Add a comment describing FieldsPerRecord

---

*[parser/geo-g1.go, line 55 at r8](https://reviewable.io:443/reviews/m-lab/annotation-service/34#-KtMwUx8jxYVI3DNOvLK:-KtMwUx8jxYVI3DNOvLL:b-czcj1d) ([raw file](https://github.com/m-lab/annotation-service/blob/58910d8feb891cb7726ba7b93ab4adfad82dabc6/parser/geo-g1.go#L55)):*
> ```Go
> 			if err == io.EOF {
> 				break
> 			} else if err != csv.ErrFieldCount {
> ```

err == ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/34)*

**Comment by gfr10598** [comment]
Reviewed 1 of 6 files at r6, 1 of 5 files at r7, 2 of 2 files at r8.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/34)*

**Comment by shelbychen97** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[parser/geo-g1.go, line 49 at r8](https://reviewable.io:443/reviews/m-lab/annotation-service/34#-KtMwKJNq92lwGngtUNg:-KtNO5TYyPAwjXPQSHuc:b-896fix) ([raw file](https://github.com/m-lab/annotation-service/blob/58910d8feb891cb7726ba7b93ab4adfad82dabc6/parser/geo-g1.go#L49)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Add a comment describing FieldsPerRecord
</blockquote></details>

Done.

---

*[parser/geo-g1.go, line 55 at r8](https://reviewable.io:443/reviews/m-lab/annotation-service/34#-KtMwUx8jxYVI3DNOvLK:-KtNO5vbEZPSJe6MY2Oh:b-896fix) ([raw file](https://github.com/m-lab/annotation-service/blob/58910d8feb891cb7726ba7b93ab4adfad82dabc6/parser/geo-g1.go#L55)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

err == ?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/34)*

**Comment by shelbychen97** [comment]
Review status: 7 of 10 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[parser/geo-ip.go, line 48 at r4](https://reviewable.io:443/reviews/m-lab/annotation-service/34#-KsszaZuvpxt-JVAHS36:-KtRdlehB95-yAJzSh08:b-896fix) ([raw file](https://github.com/m-lab/annotation-service/blob/a3d11b28850e0f8e5b90bc797d417fcbda45fdc0/parser/geo-ip.go#L48)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

This is poorly named.  checkNumColumns instead
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/34)*

**Comment by gfr10598** [comment]
:lgtm:  Once you address remaining comments.

---

Reviewed 3 of 3 files at r9.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[parser/geo-g1.go, line 49 at r8](https://reviewable.io:443/reviews/m-lab/annotation-service/34#-KtMwKJNq92lwGngtUNg:-KtRowG0q1zbUUsK-j41:b3qjc9t) ([raw file](https://github.com/m-lab/annotation-service/blob/58910d8feb891cb7726ba7b93ab4adfad82dabc6/parser/geo-g1.go#L49)):*
<details><summary><i>Previously, shelbychen97 (Shelby Chen ) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Did you push the change?

---

*[parser/geo-g1.go, line 55 at r9](https://reviewable.io:443/reviews/m-lab/annotation-service/34#-KtRp6T-u1LbomRcO5p7:-KtRp6T-u1LbomRcO5p8:bcf3p6q) ([raw file](https://github.com/m-lab/annotation-service/blob/bdebfe5e3f8a1dc9b731b021643dcd93d33589df/parser/geo-g1.go#L55)):*
> ```Go
> 			if err == io.EOF {
> 				break
> 			} else if len(record) != r.FieldsPerRecord {
> ```

Now you have me curious.  What does the ErrFieldCount error look like?  I think it reads a little better if you compare the error, rather than the length.  But OK either way.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/34#-:-KtRpSByGQKdPueNZLWI:bjbx8mt)*

**Comment by shelbychen97** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[parser/geo-g1.go, line 55 at r9](https://reviewable.io:443/reviews/m-lab/annotation-service/34#-KtRp6T-u1LbomRcO5p7:-KtS-9KuXzUtCBTasxj1:b-px1hn8) ([raw file](https://github.com/m-lab/annotation-service/blob/bdebfe5e3f8a1dc9b731b021643dcd93d33589df/parser/geo-g1.go#L55)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Now you have me curious.  What does the ErrFieldCount error look like?  I think it reads a little better if you compare the error, rather than the length.  But OK either way.
</blockquote></details>

ErrFieldCount says "wrong number of fields in line" but the error printed also specified the column # which is harder to compare i.e. "column 3: wrong number of fields in line" 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/34)*

**Comment by shelbychen97** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[parser/geo-g1.go, line 49 at r8](https://reviewable.io:443/reviews/m-lab/annotation-service/34#-KtMwKJNq92lwGngtUNg:-KtStSmJ7IElRWFY10lE:b-896fix) ([raw file](https://github.com/m-lab/annotation-service/blob/58910d8feb891cb7726ba7b93ab4adfad82dabc6/parser/geo-g1.go#L49)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Did you push the change?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/34)*

**Pull request merged**
