### PR TITLE
load only ipv4 or ipv6 legacy dataset separately

### PR DESCRIPTION
**Pull request by yachang**
This change is [Reviewable](https://reviewable.io/reviews/m-lab/annotation-service/191)

### CODE REVIEW

**Review by gfr10598 — CHANGES_REQUESTED** [review]
Seems like there should be unit tests that should be broken.  I guess we don't have any IPv6 tests.  Please add an IPv6 test somewhere, or a TODO in filename.go where the legacy datasets have been disabled.  We don't want to re-enable legacy datasets, and then have all the v6 annotations fail.

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/m-lab/annotation-service/191#-:-LXLnuJUEWEoz7a-mKcw:b-hgarwo)* status: 0 of 1 LGTMs obtained

___
*[legacy/legacy-dataset.go, line 125 at r1](https://reviewable.io/reviews/m-lab/annotation-service/191#-LXLkkwN3pNRoS4EeWrn:-LXLkkwN3pNRoS4EeWro:b-g6ma0l) ([raw file](https://github.com/m-lab/annotation-service/blob/622f76c6648ecd215f94748ad3204ae7b58a5331/legacy/legacy-dataset.go#L125)):*
> ```Go
> // Datasets contains pointers to the datasets used to hold and lookup IP data.
> // There is only one IPv4 OR IPv6 dataset per Datasets structure.
> type Datasets struct {
> ```

How about making this singular Dataset?
Or, better yet how about just Annotator, so it will look like legacy.Annotator, which implements the api.Annotator interface?

**Review by yachang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/annotation-service/191)* status: 0 of 1 LGTMs obtained

___
*[legacy/legacy-dataset.go, line 125 at r1](https://reviewable.io/reviews/m-lab/annotation-service/191#-LXLkkwN3pNRoS4EeWrn:-LXPANwE8w62kpxZDhu9:b-896fix) ([raw file](https://github.com/m-lab/annotation-service/blob/622f76c6648ecd215f94748ad3204ae7b58a5331/legacy/legacy-dataset.go#L125)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

How about making this singular Dataset?
Or, better yet how about just Annotator, so it will look like legacy.Annotator, which implements the api.Annotator interface?
</blockquote></details>

Done.

**Review by yachang — COMMENTED** [review]
There is unittest code change to fix the broken test.

We have TestLoadLegacyGeoliteV6Dataset() for IPV6 test.

TestLoadLegacyDataset() use an IPv6 dataset as well.

> *[Reviewable](https://reviewable.io/reviews/m-lab/annotation-service/191#-:-LXPAbB0Cy5NnSApUpqR:b-jry0w4)* status: 0 of 1 LGTMs obtained

**Review by gfr10598 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/m-lab/annotation-service/191#-:-LXPH4az1IGUjYwSMt4B:bnfp4nl)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Review by gfr10598 — COMMENTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/m-lab/annotation-service/191)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Review by gfr10598 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/annotation-service/191)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Pull request merged**
