### PR TITLE
Current data loading

### PR DESCRIPTION
**Pull request by jlm123hi**
This is the code needed to load in the latest geolite2 dataset, for real time annotation.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/annotation-service/30)

### CODE REVIEW

**Comment by gfr10598** [comment]
This is coming together very nicely!!

---

Reviewed 4 of 5 files at r1.
Review status: 4 of 5 files reviewed at latest revision, 6 unresolved discussions.

---

*[start.go, line 1 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/30#-KsjOK9BQcgy_A1jecso:-KsjOK9BQcgy_A1jecsp:bsr85pz) ([raw file](https://github.com/m-lab/annotation-service/blob/4831f71eb7316d531e0182daee400dcddddeb3c3/start.go#L1)):*
> ```Go
> package main
> ```

Could you rename this file main.go, sometime soon?

---

*[handler/data.go, line 21 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/30#-KsjN5LfBvYO2MeXJ0ls:-KsjN5LfBvYO2MeXJ0lt:b-ufrfno) ([raw file](https://github.com/m-lab/annotation-service/blob/4831f71eb7316d531e0182daee400dcddddeb3c3/handler/data.go#L21)):*
> ```Go
> 	IP6Nodes      []parser.IPNode
> 	LocationNodes []parser.LocationNode
> 	GeoidMap      map[int]int
> ```

IIUC, the GeoIdMap (which has a typo) isn't required after loading the IPNodes.  So I would drop that from the GeoDataset, but add a comment in the code explaining.

---

*[handler/data.go, line 76 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/30#-KsjMsSUJU2gNzVu43i_:-KsjMsSUJU2gNzVu43ia:bftfw0h) ([raw file](https://github.com/m-lab/annotation-service/blob/4831f71eb7316d531e0182daee400dcddddeb3c3/handler/data.go#L76)):*
> ```Go
> // LoadLatestGeolite2File will check GCS for the latest file, download
> // it, process it, and load it into memory so that it can be easily
> // searched, then it will return a pointer to that file or an error.
> ```

pointer to that GeoDataset ...

---

*[handler/pubsub.go, line 38 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/30#-KsjNYOkiPOoUjbrV9bQ:-KsjNYOkiPOoUjbrV9bR:b-rez0m6) ([raw file](https://github.com/m-lab/annotation-service/blob/4831f71eb7316d531e0182daee400dcddddeb3c3/handler/pubsub.go#L38)):*
> ```Go
> 	// Block forever to listen for new messages and run the refresh dataset callbacks when a new message arrives
> 	log.Fatal(sub.Receive(context.Background(), func(ctx context.Context, m *pubsub.Message) {
> 		PopulateLatestData()
> ```

Very nice!!

---

*[parser/geo-ip.go, line 104 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/30#-KsjO2nXVRQ0ej3QnpuV:-KsjO2nXVRQ0ej3QnpuW:b-g3pzgv) ([raw file](https://github.com/m-lab/annotation-service/blob/4831f71eb7316d531e0182daee400dcddddeb3c3/parser/geo-ip.go#L104)):*
> ```Go
> 			index, err := validateGeoId(record[1], idMap)
> 			if err != nil {
> 				if backupIndex, err := validateGeoId(record[2], idMap); err == nil {
> ```

Hmm - is this your code or shelby's ?

---

*[parser/geo-ip.go, line 259 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/30#-KsjLywi4e_xJOIeB_ig:-KsjLywi4e_xJOIeB_ih:bo9xjb2) ([raw file](https://github.com/m-lab/annotation-service/blob/4831f71eb7316d531e0182daee400dcddddeb3c3/parser/geo-ip.go#L259)):*
> ```Go
> 			newNode.CountryName = record[5]
> 		} else {
> 			log.Println("Country name should be letters only: %s", record[5])
> ```

Drop the %s or use Printf (and newline)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/30#-:-KsjOQwijVIVaAS1gXPT:bey5504)*

**Comment by jlm123hi** [comment]
Review status: 4 of 5 files reviewed at latest revision, 5 unresolved discussions.

---

*[start.go, line 1 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/30#-KsjOK9BQcgy_A1jecso:-KsjP8ldYE_cLhfvnTD2:b-896fix) ([raw file](https://github.com/m-lab/annotation-service/blob/4831f71eb7316d531e0182daee400dcddddeb3c3/start.go#L1)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Could you rename this file main.go, sometime soon?
</blockquote></details>

Done.

---

*[handler/data.go, line 21 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/30#-KsjN5LfBvYO2MeXJ0ls:-KsjPRNEB4HYpzfILQOL:b-5zmdde) ([raw file](https://github.com/m-lab/annotation-service/blob/4831f71eb7316d531e0182daee400dcddddeb3c3/handler/data.go#L21)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

IIUC, the GeoIdMap (which has a typo) isn't required after loading the IPNodes.  So I would drop that from the GeoDataset, but add a comment in the code explaining.
</blockquote></details>

Wow, that makes so much more sense. I don't know how I got it into my mind that the map was still needed. Done.

---

*[handler/data.go, line 76 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/30#-KsjMsSUJU2gNzVu43i_:-KsjRs8XSB3hP1Ec4nZ6:bak290) ([raw file](https://github.com/m-lab/annotation-service/blob/4831f71eb7316d531e0182daee400dcddddeb3c3/handler/data.go#L76)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

pointer to that GeoDataset ...
</blockquote></details>

Done. My bad.

---

*[parser/geo-ip.go, line 104 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/30#-KsjO2nXVRQ0ej3QnpuV:-KsjS2T6fqJwZgBP3jYk:b-rox892) ([raw file](https://github.com/m-lab/annotation-service/blob/4831f71eb7316d531e0182daee400dcddddeb3c3/parser/geo-ip.go#L104)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Hmm - is this your code or shelby's ?
</blockquote></details>

Sorry, this is just something that I threw in there because the real dataset doesn't necessarily have an ID in that column. It was one of the things you and Shelby discussed yesterday. I put it in because I needed a temporary fix as no solution had been merged into master yet. Should I remove it and just leave code that won't work? Or should I keep it and add an issue for Shelby to address it however she feels is best?

---

*[parser/geo-ip.go, line 259 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/30#-KsjLywi4e_xJOIeB_ig:-KsjSvkfN_GfOcuM4rCx:b-g11017) ([raw file](https://github.com/m-lab/annotation-service/blob/4831f71eb7316d531e0182daee400dcddddeb3c3/parser/geo-ip.go#L259)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Drop the %s or use Printf (and newline)
</blockquote></details>

Done. Sorry, that was a sloppy mistake to miss.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/30)*

**Comment by gfr10598** [comment]
:lgtm:  Once you resolve remaining 2 comments.

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[handler/data.go, line 76 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/30#-KsjMsSUJU2gNzVu43i_:-KsjU0FeqAfsz1FpI6jJ:bw9t561) ([raw file](https://github.com/m-lab/annotation-service/blob/4831f71eb7316d531e0182daee400dcddddeb3c3/handler/data.go#L76)):*
<details><summary><i>Previously, jlm123hi (Joseph Marques) wrote…</i></summary><blockquote>

Done. My bad.
</blockquote></details>

Hmm.  The fix isn't showing up for me.

---

*[parser/geo-ip.go, line 104 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/30#-KsjO2nXVRQ0ej3QnpuV:-KsjUB2SNfPDMzmJSq2Y:b-n6dd1h) ([raw file](https://github.com/m-lab/annotation-service/blob/4831f71eb7316d531e0182daee400dcddddeb3c3/parser/geo-ip.go#L104)):*
<details><summary><i>Previously, jlm123hi (Joseph Marques) wrote…</i></summary><blockquote>

Sorry, this is just something that I threw in there because the real dataset doesn't necessarily have an ID in that column. It was one of the things you and Shelby discussed yesterday. I put it in because I needed a temporary fix as no solution had been merged into master yet. Should I remove it and just leave code that won't work? Or should I keep it and add an issue for Shelby to address it however she feels is best?
</blockquote></details>

Keep and add an issue I think.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/30#-:-KsjULou4hjTM2yjOyEP:b-atid6p)*

**Comment by jlm123hi** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[handler/data.go, line 76 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/30#-KsjMsSUJU2gNzVu43i_:-KsjVObZZ4SkNzQA0Ywd:b-sb3jhw) ([raw file](https://github.com/m-lab/annotation-service/blob/4831f71eb7316d531e0182daee400dcddddeb3c3/handler/data.go#L76)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Hmm.  The fix isn't showing up for me.
</blockquote></details>

Ah, it seems that would be because I'm an idiot who hit switch file rather than save and close. Truly, honest to God, fixed now.

---

*[parser/geo-ip.go, line 104 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/30#-KsjO2nXVRQ0ej3QnpuV:-KsjVaYg-lYqj5bdIjqe:b-896fix) ([raw file](https://github.com/m-lab/annotation-service/blob/4831f71eb7316d531e0182daee400dcddddeb3c3/parser/geo-ip.go#L104)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Keep and add an issue I think.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/30)*

**Pull request merged**
