### PR TITLE
create handler and metrics

### PR DESCRIPTION
**Pull request by shelbychen97**
This change is [Reviewable](https://reviewable.io/reviews/m-lab/annotation-service/15)

### CODE REVIEW

**Comment by jlm123hi** [comment]
:lgtm:

**Comment by yachang** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[handler/handler.go, line 24 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/15#-Krq0DukihlkGn-wjdHf:-Krq0Dulf8M6_YEpTjB_:bei1yrg) ([raw file](https://github.com/m-lab/annotation-service/blob/635ad1c9c432a69158478d810022be20e9d22a90/handler/handler.go#L24)):*
> ```Go
> 	_, _, _, err := validate(w, r)
> 	if err != nil {
> 		fmt.Fprintf(w,"Invalid request")
> ```

use log instead of fmt

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/15)*

**Comment by yachang** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[handler/handler.go, line 24 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/15#-Krq0DukihlkGn-wjdHf:-Krq0KKu5ddTwqiyp_0x:bu5figx) ([raw file](https://github.com/m-lab/annotation-service/blob/635ad1c9c432a69158478d810022be20e9d22a90/handler/handler.go#L24)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

use log instead of fmt
</blockquote></details>

Sorry. please ignore it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/15)*

**Comment by yachang** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[handler/handler.go, line 47 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/15#-Krq0j8XWNoVPl5ld2UI:-Krq0j8YC8XIjnnoUV9b:byvnlof) ([raw file](https://github.com/m-lab/annotation-service/blob/635ad1c9c432a69158478d810022be20e9d22a90/handler/handler.go#L47)):*
> ```Go
> 	query := r.URL.Query()
> 
> 	//PRETEND THAT THIS IS YYYYMMDD
> ```

leave a space between // and words

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/15)*

**Comment by yachang** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[handler/handler.go, line 28 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/15#-Krq108UJ4KgDmR8j5pE:-Krq108UJ4KgDmR8j5pF:b2dr9xf) ([raw file](https://github.com/m-lab/annotation-service/blob/635ad1c9c432a69158478d810022be20e9d22a90/handler/handler.go#L28)):*
> ```Go
> 		// Fake response
> 		fmt.Fprintf(w, "[\n  {\"ip\": \"%s\", \"type\": \"STRING\"},\n  {\"country\": \"%s\", \"type\": \"STRING\"},\n  {\"countryAbrv\": \"%s\", \"type\": \"STRING\"},\n]", "1.4.128.0", "Thailand", "TH")
> 		// Figure out which table to use
> ```

So those are TODO? no code there...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/15)*

**Comment by shelbychen97** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[handler/handler.go, line 28 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/15#-Krq108UJ4KgDmR8j5pE:-Krq7d7_PxyHWg7Ie1ua:b-896fix) ([raw file](https://github.com/m-lab/annotation-service/blob/635ad1c9c432a69158478d810022be20e9d22a90/handler/handler.go#L28)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

So those are TODO? no code there...
</blockquote></details>

Done.

---

*[handler/handler.go, line 47 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/15#-Krq0j8XWNoVPl5ld2UI:-Krq7dzB8lL_fNU15S8S:ba3dfob) ([raw file](https://github.com/m-lab/annotation-service/blob/635ad1c9c432a69158478d810022be20e9d22a90/handler/handler.go#L47)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

leave a space between // and words
</blockquote></details>

Removed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/15)*

**Comment by yachang** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[handler/handler.go, line 34 at r2](https://reviewable.io:443/reviews/m-lab/annotation-service/15#-KrqDe51QVL1itzALv2F:-KrqDe52xCIor-TLMKsv:b-3mimrv) ([raw file](https://github.com/m-lab/annotation-service/blob/3ee82efb4c1c33460a8a4c1bd879cbfc2f9bdbf6/handler/handler.go#L34)):*
> ```Go
> 
> // validates request syntax
> // parses request and returns parameters
> ```

Add documentation: when the returned IPversion is 0, blabla

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/15)*

**Comment by yachang** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/15#-:-KrqDqpkxs4mP6Lrz4KS:bnfp4nl)*

**Pull request merged**
