### PR TITLE
GeoLite2

### PR DESCRIPTION
**Pull request by shelbychen97**
Reads geolite2 city zip files from GCS and parses three different lists (IPV4,IPv6,LocationBlock)

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/annotation-service/13)

### CODE REVIEW

**Comment by yachang** [comment]
Review status: 0 of 27 files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 9 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/13#-Krkjv_RK6FC2JGSlf0N:-Krkjv_RK6FC2JGSlf0O:b65z9xv) ([raw file](https://github.com/m-lab/annotation-service/blob/87204f0b566b5e444cc7ba7608dc3a178b1914ea/README.md#L9)):*
> ```Markdown
> databases. 
> 
> IPv4 and IPv6 Columns 
> ```

Add corresponding  .csv file names here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/13)*

**Comment by yachang** [comment]
Review status: 0 of 27 files reviewed at latest revision, 2 unresolved discussions.

---

*[downloader/downloadGCS.go, line 26 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/13#-Krklw8Q8HVLQJl8xS37:-Krklw8Q8HVLQJl8xS38:b-d27t9r) ([raw file](https://github.com/m-lab/annotation-service/blob/87204f0b566b5e444cc7ba7608dc3a178b1914ea/downloader/downloadGCS.go#L26)):*
> ```Go
> 	zipReader := createReader(GCSFolder, GCSFile, ctx)
> 	if zipReader == nil {
> 		fmt.Println("Failed creating reader")
> ```

log.Printf()

And for all the following cases.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/13)*

**Comment by yachang** [comment]
Review status: 0 of 27 files reviewed at latest revision, 3 unresolved discussions.

---

*[downloader/downloadGCS.go, line 38 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/13#-KrkmBQD6v0xcCYs9htA:-KrkmBQD6v0xcCYs9htB:b-lxcqwb) ([raw file](https://github.com/m-lab/annotation-service/blob/87204f0b566b5e444cc7ba7608dc3a178b1914ea/downloader/downloadGCS.go#L38)):*
> ```Go
> 
> //creates generic reader
> func createReader(bucket string, bucketObj string, ctx context.Context) *zip.Reader {
> ```

return error as well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/13)*

**Comment by yachang** [comment]
Review status: 0 of 27 files reviewed at latest revision, 4 unresolved discussions.

---

*[downloader/downloadGCS.go, line 41 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/13#-KrkmT2Dcsvh-Oo8LCwq:-KrkmT2Dcsvh-Oo8LCwr:bglicn3) ([raw file](https://github.com/m-lab/annotation-service/blob/87204f0b566b5e444cc7ba7608dc3a178b1914ea/downloader/downloadGCS.go#L41)):*
> ```Go
> 	client, err := storage.NewClient(ctx)
> 	if err != nil {
> 		return nil
> ```

return err info 
and all the following cases

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/13)*

**Comment by yachang** [comment]
Review status: 0 of 27 files reviewed at latest revision, 5 unresolved discussions.

---

*[downloader/downloadGCS_test.go, line 19 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/13#-KrkmoGHCy0tt3R6Pr8K:-KrkmoGHCy0tt3R6Pr8L:b-5jey55) ([raw file](https://github.com/m-lab/annotation-service/blob/87204f0b566b5e444cc7ba7608dc3a178b1914ea/downloader/downloadGCS_test.go#L19)):*
> ```Go
> 	err := testFiles("MaxMind/2017/08/15/GeoLite2City.zip", "testdata/GeoLite2City.zip")
> 	if err != nil {
> 		t.Fatal(err)
> ```

if the first Fatal() triggered, there is no change to print the second Fatal()

suggest merge two lines into one.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/13)*

**Comment by yachang** [comment]
Review status: 0 of 27 files reviewed at latest revision, 6 unresolved discussions.

---

*[downloader/downloadGCS_test.go, line 60 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/13#-KrkqMgqInEDqo6ULbjE:-KrkqLBLP0QR7Mxe6W21:btcbk0n) ([raw file](https://github.com/m-lab/annotation-service/blob/87204f0b566b5e444cc7ba7608dc3a178b1914ea/downloader/downloadGCS_test.go#L60)):*
> ```Go
> 		if element.IPAddress != listComp[index].IPAddress {
> 			output := strings.Join([]string{"IPAddress inconsistent\ngot:", element.IPAddress, " \nwanted:", listComp[index].IPAddress}, "")
> 			fmt.Println(output)
> ```

log.Printf() 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/13)*

**Comment by yachang** [comment]
Review status: 0 of 27 files reviewed at latest revision, 7 unresolved discussions.

---

*[downloader/downloadGCS_test.go, line 65 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/13#-KrkqhdPlZ66iicTE3lN:-KrkqhdPlZ66iicTE3lO:bjcy229) ([raw file](https://github.com/m-lab/annotation-service/blob/87204f0b566b5e444cc7ba7608dc3a178b1914ea/downloader/downloadGCS_test.go#L65)):*
> ```Go
> 		if element.Geoname != listComp[index].Geoname {
> 			output := strings.Join([]string{"Geoname inconsistent\ngot:", strconv.Itoa(element.Geoname), " \nwanted:", strconv.Itoa(listComp[index].Geoname)}, "")
> 			fmt.Println(output)
> ```

ditto and all following cases

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/13)*

**Comment by yachang** [comment]
Review status: 0 of 27 files reviewed at latest revision, 8 unresolved discussions.

---

*[downloader/downloadGCS_test.go, line 74 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/13#-Krks1D-C6extzQ_NxXv:-Krks1D-C6extzQ_NxXw:b6v63v6) ([raw file](https://github.com/m-lab/annotation-service/blob/87204f0b566b5e444cc7ba7608dc3a178b1914ea/downloader/downloadGCS_test.go#L74)):*
> ```Go
> 		}
> 		if element.Latitude != listComp[index].Latitude {
> 			output := strings.Join([]string{"Latitude inconsistent\ngot:", strconv.FormatFloat(element.Latitude, 'f', 6, 64), " \nwanted:", strconv.FormatFloat(listComp[index].Latitude, 'f', 6, 64)}, "")
> ```

refactor strconv.FormatFloat(listComp[index].Latitude, 'f', 6, 64) into a func() to reduce dup code.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/13)*

**Comment by yachang** [comment]
Review status: 0 of 27 files reviewed at latest revision, 9 unresolved discussions.

---

*[downloader/downloadGCS.go, line 19 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/13#-KrksQaUt_6b0bgNDv9Y:-KrksQaUt_6b0bgNDv9Z:bs2280f) ([raw file](https://github.com/m-lab/annotation-service/blob/87204f0b566b5e444cc7ba7608dc3a178b1914ea/downloader/downloadGCS.go#L19)):*
> ```Go
> 	var listIPv4 []parser.BlockNode
> 	var listIPv6 []parser.BlockNode
> 	var listLoc []parser.LocNode
> ```

LocNode means LocalNode? Add documentation for the name

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/13)*

**Comment by yachang** [comment]
Review status: 0 of 27 files reviewed at latest revision, 10 unresolved discussions.

---

*[downloader/downloadGCS_test.go, line 24 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/13#-KrlI9eoqfFiKVJ0qgfT:-KrlI9eoqfFiKVJ0qgfU:bw0kwdw) ([raw file](https://github.com/m-lab/annotation-service/blob/87204f0b566b5e444cc7ba7608dc3a178b1914ea/downloader/downloadGCS_test.go#L24)):*
> ```Go
> }
> 
> func testFiles(fileName string, localFile string) error {
> ```

test createReader() instead of rewriting it here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/13)*

**Comment by yachang** [comment]
Review status: 0 of 27 files reviewed at latest revision, 11 unresolved discussions.

---

*[parser/geo-ip.go, line 1 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/13#-KrlJP6des89FNM0UHFa:-KrlJP6des89FNM0UHFb:bs981qv) ([raw file](https://github.com/m-lab/annotation-service/blob/87204f0b566b5e444cc7ba7608dc3a178b1914ea/parser/geo-ip.go#L1)):*
> ```Go
> //Only files including IPv4 IPv6 and Location (in english)
> ```

Leave a space between // and documentation.

And for all following cases.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/13)*

**Comment by yachang** [comment]
Review status: 0 of 27 files reviewed at latest revision, 12 unresolved discussions.

---

*[parser/geo-ip.go, line 25 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/13#-KrlK7RQSBq7oXrmoTNv:-KrlK7RQSBq7oXrmoTNw:bh1xe9r) ([raw file](https://github.com/m-lab/annotation-service/blob/87204f0b566b5e444cc7ba7608dc3a178b1914ea/parser/geo-ip.go#L25)):*
> ```Go
> 
> // LocNode defines Location databases
> type LocNode struct {
> ```

Rename to LocationNode

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/13)*

**Comment by yachang** [comment]
Review status: 0 of 27 files reviewed at latest revision, 13 unresolved discussions.

---

*[parser/geo-ip.go, line 36 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/13#-KrlKKxvBfNiKX6gf47v:-KrlKKxvBfNiKX6gf47w:b-ojv938) ([raw file](https://github.com/m-lab/annotation-service/blob/87204f0b566b5e444cc7ba7608dc3a178b1914ea/parser/geo-ip.go#L36)):*
> ```Go
> 	return BlockNode{ipa, gn, pc, lat, long}
> }
> func NewLocNode(gn int, cc, cn string, mc int64, ctn string) LocNode {
> ```

blank line between funcs

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/13)*

**Comment by yachang** [comment]
Review status: 0 of 27 files reviewed at latest revision, 14 unresolved discussions.

---

*[parser/geo-ip.go, line 67 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/13#-KrlKln58tJetQv5-1E5:-KrlKln58tJetQv5-1E6:b-4ooukl) ([raw file](https://github.com/m-lab/annotation-service/blob/87204f0b566b5e444cc7ba7608dc3a178b1914ea/parser/geo-ip.go#L67)):*
> ```Go
> 			rc, err := f.Open()
> 			if err != nil {
> 				fmt.Println("error opening GeoLite2-Country-Blocks-IPv6.csv")
> ```

log.

ditto

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/13)*

**Comment by yachang** [comment]
Review status: 0 of 27 files reviewed at latest revision, 15 unresolved discussions.

---

*[parser/geo-ip.go, line 101 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/13#-KrlL5gl0N1oL_5neovS:-KrlL5gl0N1oL_5neovT:b3j8a29) ([raw file](https://github.com/m-lab/annotation-service/blob/87204f0b566b5e444cc7ba7608dc3a178b1914ea/parser/geo-ip.go#L101)):*
> ```Go
> 	}
> 
> 	if listIPv4 == nil || listIPv6 == nil || listLoc == nil {
> ```

add 

// TODO: add metrics for those error cases.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/13)*

**Comment by yachang** [comment]
Review status: 0 of 27 files reviewed at latest revision, 16 unresolved discussions.

---

*[parser/geo-ip.go, line 124 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/13#-KrlMITEQbQffxRyBymJ:-KrlMITEQbQffxRyBymK:b174o2p) ([raw file](https://github.com/m-lab/annotation-service/blob/87204f0b566b5e444cc7ba7608dc3a178b1914ea/parser/geo-ip.go#L124)):*
> ```Go
> 			break
> 		}
> 		if len(record) != 10 {
> ```

Define a const for number of columes

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/13)*

**Comment by shelbychen97** [comment]
Review status: 0 of 30 files reviewed at latest revision, 16 unresolved discussions.

---

*[README.md, line 9 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/13#-Krkjv_RK6FC2JGSlf0N:-KrlOMemaqi_qG2kPrBG:b-896fix) ([raw file](https://github.com/m-lab/annotation-service/blob/87204f0b566b5e444cc7ba7608dc3a178b1914ea/README.md#L9)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

Add corresponding  .csv file names here
</blockquote></details>

Done.

---

*[downloader/downloadGCS.go, line 19 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/13#-KrksQaUt_6b0bgNDv9Y:-KrlOLoAwoXtFzE4N7J-:b-r1fd1v) ([raw file](https://github.com/m-lab/annotation-service/blob/87204f0b566b5e444cc7ba7608dc3a178b1914ea/downloader/downloadGCS.go#L19)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

LocNode means LocalNode? Add documentation for the name
</blockquote></details>

I changed the names of all Location related lists to be more specific 

---

*[downloader/downloadGCS.go, line 26 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/13#-Krklw8Q8HVLQJl8xS37:-KrlOLXGPGcme9z-RA9a:b-896fix) ([raw file](https://github.com/m-lab/annotation-service/blob/87204f0b566b5e444cc7ba7608dc3a178b1914ea/downloader/downloadGCS.go#L26)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

log.Printf()

And for all the following cases.
</blockquote></details>

Done.

---

*[downloader/downloadGCS.go, line 38 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/13#-KrkmBQD6v0xcCYs9htA:-KrlOJKLPjpVqTqA60mN:b-896fix) ([raw file](https://github.com/m-lab/annotation-service/blob/87204f0b566b5e444cc7ba7608dc3a178b1914ea/downloader/downloadGCS.go#L38)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

return error as well.
</blockquote></details>

Done.

---

*[downloader/downloadGCS.go, line 41 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/13#-KrkmT2Dcsvh-Oo8LCwq:-KrlOJ71ZFcARzWCXxfI:b-896fix) ([raw file](https://github.com/m-lab/annotation-service/blob/87204f0b566b5e444cc7ba7608dc3a178b1914ea/downloader/downloadGCS.go#L41)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

return err info 
and all the following cases
</blockquote></details>

Done.

---

*[downloader/downloadGCS_test.go, line 19 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/13#-KrkmoGHCy0tt3R6Pr8K:-KrlOIha-sYhTpD5E7XS:b-896fix) ([raw file](https://github.com/m-lab/annotation-service/blob/87204f0b566b5e444cc7ba7608dc3a178b1914ea/downloader/downloadGCS_test.go#L19)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

if the first Fatal() triggered, there is no change to print the second Fatal()

suggest merge two lines into one.
</blockquote></details>

Done.

---

*[downloader/downloadGCS_test.go, line 24 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/13#-KrlI9eoqfFiKVJ0qgfT:-KrlOPkFCeJEfYa900Ja:by0wpk6) ([raw file](https://github.com/m-lab/annotation-service/blob/87204f0b566b5e444cc7ba7608dc3a178b1914ea/downloader/downloadGCS_test.go#L24)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

test createReader() instead of rewriting it here.
</blockquote></details>

For testing purposes, I created an app engineering context vs a google storage context (which is created inside createReader)
 

---

*[parser/geo-ip.go, line 101 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/13#-KrlL5gl0N1oL_5neovS:-KrlhYU-RAdgjtZc1K2n:b-dsowlr) ([raw file](https://github.com/m-lab/annotation-service/blob/87204f0b566b5e444cc7ba7608dc3a178b1914ea/parser/geo-ip.go#L101)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

add 

// TODO: add metrics for those error cases.
</blockquote></details>

Ive added tests with missing files 

---

*[parser/geo-ip.go, line 124 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/13#-KrlMITEQbQffxRyBymJ:-KrlgBD_BuAGlxOjH0cK:b-896fix) ([raw file](https://github.com/m-lab/annotation-service/blob/87204f0b566b5e444cc7ba7608dc3a178b1914ea/parser/geo-ip.go#L124)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

Define a const for number of columes
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/13)*

**Comment by gfr10598** [comment]
Please create an issue suggesting we look into MaxMindDB alternative to csv files.

This is actually looking pretty good.  I have some more suggestions that I think would be easiest to do together tomorrow morning.  Go ahead and address these comments, then we'll pick up from there tomorrow.

---

Reviewed 20 of 27 files at r1, 4 of 8 files at r2.
Review status: 24 of 30 files reviewed at latest revision, 27 unresolved discussions.

---

*[downloader/downloadGCS.go, line 41 at r2](https://reviewable.io:443/reviews/m-lab/annotation-service/13#-Krlx031l-igUBDGhujL:-Krlx031l-igUBDGhujM:bc9gisj) ([raw file](https://github.com/m-lab/annotation-service/blob/8e0add82f9f4e352888ccadd29c1cfe19fbfcefb/downloader/downloadGCS.go#L41)):*
> ```Go
> 
> // Creates generic reader
> func createReader(bucket string, bucketObj string, ctx context.Context) (*zip.Reader, error) {
> ```

Creating a zip.Reader from a GCS file.

---

*[parser/geo-ip.go, line 1 at r2](https://reviewable.io:443/reviews/m-lab/annotation-service/13#-Krm0uPqMus0zVdJCREM:-Krm0uPqMus0zVdJCREN:bb0erb) ([raw file](https://github.com/m-lab/annotation-service/blob/8e0add82f9f4e352888ccadd29c1cfe19fbfcefb/parser/geo-ip.go#L1)):*
> ```Go
> // Only files including IPv4 IPv6 and Location (in english)
> ```

... IPv4, IPv6, and Location ...

---

*[parser/geo-ip.go, line 14 at r2](https://reviewable.io:443/reviews/m-lab/annotation-service/13#-Krm1GHRcgg3UcdVkXhi:-Krm1GHRcgg3UcdVkXhj:b-szun8f) ([raw file](https://github.com/m-lab/annotation-service/blob/8e0add82f9f4e352888ccadd29c1cfe19fbfcefb/parser/geo-ip.go#L14)):*
> ```Go
> )
> 
> const IPColumnNum = 10
> ```

IPNumColumns.  Otherwise it sounds like the number of the column containing the IP address.

---

*[parser/geo-ip.go, line 15 at r2](https://reviewable.io:443/reviews/m-lab/annotation-service/13#-Krm1L_Yrr7ZO_ppTEBB:-Krm1L_Yrr7ZO_ppTEBC:b-9cekyg) ([raw file](https://github.com/m-lab/annotation-service/blob/8e0add82f9f4e352888ccadd29c1cfe19fbfcefb/parser/geo-ip.go#L15)):*
> ```Go
> 
> const IPColumnNum = 10
> const LocationColumnNum = 13
> ```

LocationNumColumns (or LocationRecordNumColumns)

---

*[parser/geo-ip.go, line 17 at r2](https://reviewable.io:443/reviews/m-lab/annotation-service/13#-Krm0U2f7OwpUikXtDm9:-Krm0U2f7OwpUikXtDmA:b-xd7jj0) ([raw file](https://github.com/m-lab/annotation-service/blob/8e0add82f9f4e352888ccadd29c1cfe19fbfcefb/parser/geo-ip.go#L17)):*
> ```Go
> const LocationColumnNum = 13
> 
> // BlockNode defintes Block IPv4 and Block IPv6 databases
> ```

Why is this called Block...?

---

*[parser/geo-ip.go, line 35 at r2](https://reviewable.io:443/reviews/m-lab/annotation-service/13#-KrlulAaWst-Gj-C2asD:-KrlulAaWst-Gj-C2asE:bqc4fcq) ([raw file](https://github.com/m-lab/annotation-service/blob/8e0add82f9f4e352888ccadd29c1cfe19fbfcefb/parser/geo-ip.go#L35)):*
> ```Go
> }
> 
> func NewBlockNode(ipa string, gn int, pc string, lat, long float64) BlockNode {
> ```

Probably should just use the struct initializer in place, and remove these two New functions.  No longer needed largely because all the fields are exported now.

---

*[parser/geo-ip.go, line 44 at r2](https://reviewable.io:443/reviews/m-lab/annotation-service/13#-Krlw8Sd7qKrqkZOh6Fh:-Krlw8Sd7qKrqkZOh6Fi:b-5ypwqa) ([raw file](https://github.com/m-lab/annotation-service/blob/8e0add82f9f4e352888ccadd29c1cfe19fbfcefb/parser/geo-ip.go#L44)):*
> ```Go
> 
> // Unzips file and calls functions to create IPv4 IPv6 and LocLists
> func Unzip(r *zip.Reader) ([]BlockNode, []BlockNode, []LocationNode, error) {
> ```

Maybe pass in []*zip.File here?
Also choose a more informative name.  ProcessAllFiles ?

---

*[parser/geo-ip.go, line 50 at r2](https://reviewable.io:443/reviews/m-lab/annotation-service/13#-Krm-YnYsPaeHMDbw4zP:-Krm-YnYsPaeHMDbw4zQ:b32uvjr) ([raw file](https://github.com/m-lab/annotation-service/blob/8e0add82f9f4e352888ccadd29c1cfe19fbfcefb/parser/geo-ip.go#L50)):*
> ```Go
> 	// Add metricsIPv4List, IPv6List, LocationList
> 	for _, f := range r.File {
> 		if len(f.Name) >= len("GeoLite2-City-Blocks-IPv4.csv") && f.Name[len(f.Name)-len("GeoLite2-City-Blocks-IPv4.csv"):] == "GeoLite2-City-Blocks-IPv4.csv" {
> ```

Is this checking for prefix equality?  If so, use strings.HasPrefix.

---

*[parser/geo-ip.go, line 50 at r2](https://reviewable.io:443/reviews/m-lab/annotation-service/13#-Krm2UyPDttRNKNERV2h:-Krm2UyPDttRNKNERV2i:bcktdxq) ([raw file](https://github.com/m-lab/annotation-service/blob/8e0add82f9f4e352888ccadd29c1cfe19fbfcefb/parser/geo-ip.go#L50)):*
> ```Go
> 	// Add metricsIPv4List, IPv6List, LocationList
> 	for _, f := range r.File {
> 		if len(f.Name) >= len("GeoLite2-City-Blocks-IPv4.csv") && f.Name[len(f.Name)-len("GeoLite2-City-Blocks-IPv4.csv"):] == "GeoLite2-City-Blocks-IPv4.csv" {
> ```

For a list of exclusive if statements like this, I think a switch statement is more readable.

---

*[parser/geo-ip.go, line 123 at r2](https://reviewable.io:443/reviews/m-lab/annotation-service/13#-Krm21igbN-ShKp7gcSw:-Krm21igbN-ShKp7gcSx:btv3ifz) ([raw file](https://github.com/m-lab/annotation-service/blob/8e0add82f9f4e352888ccadd29c1cfe19fbfcefb/parser/geo-ip.go#L123)):*
> ```Go
> 			if len(record[0]) > 0 {
> 				log.Println("Geoname was not a number") 
> 				return list, errors.New("Corrupted Data")
> ```

Add TODO for prometheus metrics for each of these errors.

---

*[parser/geo-ip_test.go, line 20 at r2](https://reviewable.io:443/reviews/m-lab/annotation-service/13#-Krm3l3pWQpxYK8ELNoU:-Krm3l3qx8FWZA1BcBYz:b52o22u) ([raw file](https://github.com/m-lab/annotation-service/blob/8e0add82f9f4e352888ccadd29c1cfe19fbfcefb/parser/geo-ip_test.go#L20)):*
> ```Go
> 		t.Errorf("Error opening zip file")
> 	}
> 	IPv4Test, IPv6Test, LocListTest, err := parser.Unzip(&(reader.Reader))
> ```

Lower case for variable names throughout these test functions.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/13#-:-KrlxYD3uI2a_vO6jUYQ:b-i3wpjy)*

**Comment by yachang** [comment]
Review status: 24 of 30 files reviewed at latest revision, 27 unresolved discussions.

---

*[README.md, line 9 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/13#-Krkjv_RK6FC2JGSlf0N:-KrpeEcFBz688IRh58KA:bpmg1he) ([raw file](https://github.com/m-lab/annotation-service/blob/87204f0b566b5e444cc7ba7608dc3a178b1914ea/README.md#L9)):*
<details><summary><i>Previously, shelbychen97 (Shelby Chen ) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

So this is format for GeoLite2?

Add column definition for GeoLite1 as well. And briefly state their difference.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/13)*

**Comment by yachang** [comment]
Review status: 24 of 30 files reviewed at latest revision, 24 unresolved discussions.

---

*[downloader/downloadGCS_test.go, line 19 at r2](https://reviewable.io:443/reviews/m-lab/annotation-service/13#-KrpfH-1BNzQ_9a0NUuy:-KrpfH-1BNzQ_9a0NUuz:bdtykm) ([raw file](https://github.com/m-lab/annotation-service/blob/8e0add82f9f4e352888ccadd29c1cfe19fbfcefb/downloader/downloadGCS_test.go#L19)):*
> ```Go
> 	err := testFiles("MaxMind/2017/08/15/GeoLite2City.zip", "testdata/GeoLite2City.zip")
> 	if err != nil {
> 		t.Fatal("Failed initializing IPv4 table")
> ```

you can log.Printf(err) before triggering t.Fatal.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/13)*

**Comment by yachang** [comment]
Review status: 24 of 30 files reviewed at latest revision, 25 unresolved discussions.

---

*[downloader/downloadGCS_test.go, line 39 at r2](https://reviewable.io:443/reviews/m-lab/annotation-service/13#-Krpfd1gVsKbYTVnsxKq:-Krpfd1gVsKbYTVnsxKr:b-a4iavx) ([raw file](https://github.com/m-lab/annotation-service/blob/8e0add82f9f4e352888ccadd29c1cfe19fbfcefb/downloader/downloadGCS_test.go#L39)):*
> ```Go
> 	if err != nil {
> 		log.Println("Failed unzipping local file") 
> 		return errors.New("Failed unzipping local file")
> ```

return the err directly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/13)*

**Comment by yachang** [comment]
Review status: 24 of 30 files reviewed at latest revision, 26 unresolved discussions.

---

*[downloader/downloadGCS_test.go, line 46 at r2](https://reviewable.io:443/reviews/m-lab/annotation-service/13#-KrpghABfl9qaQEyATCV:-KrpghACuvpDCzOk4Kfe:b-7ropln) ([raw file](https://github.com/m-lab/annotation-service/blob/8e0add82f9f4e352888ccadd29c1cfe19fbfcefb/downloader/downloadGCS_test.go#L46)):*
> ```Go
> 	if err != nil {
> 		log.Println("IPv4 lists are unequal") 
> 		return errors.New("IPv4 lists are unequal")
> ```

ditto

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/13)*

**Pull request closed without merging**
