### PR TITLE
New binary

### PR DESCRIPTION
**Pull request by shelbychen97**
New parser for geolite1 and geolite2. Removes all nested ranges.
Eliminates use of linear search. Only binary search is required. 
New tests for search.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/annotation-service/38)

### CODE REVIEW

**Comment by gfr10598** [comment]
Reviewed 1 of 3 files at r2, 3 of 10 files at r3.
Review status: 4 of 11 files reviewed at latest revision, 2 unresolved discussions.

---

*[parser/testdata/GeoLiteLatestNested.zip, line 0 at r3](https://reviewable.io:443/reviews/m-lab/annotation-service/38#-KtTIWoYW1fSkjBdyEQK:-KtTIWoYW1fSkjBdyEQL:b-gvcfsd) ([raw file](https://github.com/m-lab/annotation-service/blob/5c28a37a0c1a8baf10546dca26d33fec3a419857/parser/testdata/GeoLiteLatestNested.zip#L0)):*
This file doesn't seem to be used.  Is it needed?

---

*[parser/testdata/GeoLite2CityCORRUPT/lol.c, line 1 at r3](https://reviewable.io:443/reviews/m-lab/annotation-service/38#-KtTIbDum2Q9G9wnC-Ls:-KtTIInlhpghPmEzgzla:b4h0f6t) ([raw file](https://github.com/m-lab/annotation-service/blob/5c28a37a0c1a8baf10546dca26d33fec3a419857/parser/testdata/GeoLite2CityCORRUPT/lol.c#L1)):*
> ```C
> jkjk
> ```

Can this file be removed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/38)*

**Comment by shelbychen97** [comment]
Review status: 4 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[parser/testdata/GeoLiteLatestNested.zip, line  at r3](https://reviewable.io:443/reviews/m-lab/annotation-service/38#-KtTIWoYW1fSkjBdyEQK:-KtTRSZb2pS71TJQDLD7:b-896fix) ([raw file](https://github.com/m-lab/annotation-service/blob/5c28a37a0c1a8baf10546dca26d33fec3a419857/parser/testdata/GeoLiteLatestNested.zip#L)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

This file doesn't seem to be used.  Is it needed?
</blockquote></details>

Done.

---

*[parser/testdata/GeoLite2CityCORRUPT/lol.c, line 1 at r3](https://reviewable.io:443/reviews/m-lab/annotation-service/38#-KtTIbDum2Q9G9wnC-Ls:-KtTRTTeDv_wQgY_kAil:b-896fix) ([raw file](https://github.com/m-lab/annotation-service/blob/5c28a37a0c1a8baf10546dca26d33fec3a419857/parser/testdata/GeoLite2CityCORRUPT/lol.c#L1)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Can this file be removed?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/38)*

**Comment by gfr10598** [comment]
Review status: 4 of 10 files reviewed at latest revision, 8 unresolved discussions.

---

*[parser/geo-g1.go, line 93 at r3](https://reviewable.io:443/reviews/m-lab/annotation-service/38#-KtX4Y2hsblMcF6R5vZ7:-KtX4Y2hsblMcF6R5vZ8:b-epgdgw) ([raw file](https://github.com/m-lab/annotation-service/blob/5c28a37a0c1a8baf10546dca26d33fec3a419857/parser/geo-g1.go#L93)):*
> ```Go
> }
> 
> // Creates a List of IPNodes
> ```

Please add a comment here and in the package header that GeoLite1 is IPv4 only.

---

*[parser/geo-g1.go, line 96 at r3](https://reviewable.io:443/reviews/m-lab/annotation-service/38#-KtX0-6FRuDeAeVU2YLz:-KtX0-6FRuDeAeVU2YM-:bne5lot) ([raw file](https://github.com/m-lab/annotation-service/blob/5c28a37a0c1a8baf10546dca26d33fec3a419857/parser/geo-g1.go#L96)):*
> ```Go
> func LoadIPListGLite1(reader io.Reader, idMap map[int]int, glite1 []gLite1HelpNode) ([]IPNode, error) {
> 	g1IP := []string{"startIpNum", "endIpNum", "locId"}
> 	list := []IPNode{}
> ```

Add good comments for list and stack.

---

*[parser/geo-g1.go, line 159 at r3](https://reviewable.io:443/reviews/m-lab/annotation-service/38#-KtX1cAzUrxGxbNqbyJD:-KtX1cAzUrxGxbNqbyJE:b-cydjh5) ([raw file](https://github.com/m-lab/annotation-service/blob/5c28a37a0c1a8baf10546dca26d33fec3a419857/parser/geo-g1.go#L159)):*
> ```Go
> 					peek := stack[len(stack)-1]
> 					if lessThan(newNode.IPAddressLow, peek.IPAddressHigh) {
> 						// if theres a gap inbetween imediately nested IP's
> ```

three typos.
// if there's a gap in between immediately nested IP's

---

*[parser/geo-g1.go, line 185 at r3](https://reviewable.io:443/reviews/m-lab/annotation-service/38#-KtX0iCHyOnmg2HlcZog:-KtX0iCHyOnmg2HlcZoh:by9brd2) ([raw file](https://github.com/m-lab/annotation-service/blob/5c28a37a0c1a8baf10546dca26d33fec3a419857/parser/geo-g1.go#L185)):*
> ```Go
> 
> 	}
> 	log.Println(stack)
> ```

Remove this log?

---

*[parser/geo-g2.go, line 210 at r3](https://reviewable.io:443/reviews/m-lab/annotation-service/38#-KtX1xokRoCkHvSTXlnN:-KtX1xokRoCkHvSTXlnO:bevi6eh) ([raw file](https://github.com/m-lab/annotation-service/blob/5c28a37a0c1a8baf10546dca26d33fec3a419857/parser/geo-g2.go#L210)):*
> ```Go
> 							//log.Println("current stack: ",stack)
> 							//complete the gap
> 							peek.IPAddressLow = PlusOne(pop.IPAddressHigh)
> ```

PlusOne should actually be lower case, because it is in the parser package.

---

*[parser/geo-g2.go, line 230 at r3](https://reviewable.io:443/reviews/m-lab/annotation-service/38#-KtX4Oc7g9rBMrhifT5Z:-KtX4Oc7g9rBMrhifT5_:b4qruy6) ([raw file](https://github.com/m-lab/annotation-service/blob/5c28a37a0c1a8baf10546dca26d33fec3a419857/parser/geo-g2.go#L230)):*
> net.IPv4(255, 255, 255, 255)
How is IPv6 handled?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/38)*

**Comment by gfr10598** [comment]
Review status: 4 of 10 files reviewed at latest revision, 9 unresolved discussions.

---

*[parser/geo-g2.go, line 194 at r3](https://reviewable.io:443/reviews/m-lab/annotation-service/38#-KtX6-bGbUTqh8eTo8ib:-KtX6-bI9zReQIgI5A4A:b-7tpcw3) ([raw file](https://github.com/m-lab/annotation-service/blob/5c28a37a0c1a8baf10546dca26d33fec3a419857/parser/geo-g2.go#L194)):*
> ```Go
> 		}
> 		// Stack is not empty aka we're in a nested IP
> 		if len(stack) != 0 {
> ```

I believe this if len(stack) block is common between geo1 and geo2.  If that is correct, please pull it out into a common function.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/38)*

**Comment by gfr10598** [comment]
Reviewed 1 of 10 files at r3.
Review status: 5 of 10 files reviewed at latest revision, 10 unresolved discussions.

---

*[search/geo-search_test.go, line 117 at r4](https://reviewable.io:443/reviews/m-lab/annotation-service/38#-KtXagEUPn94hTSU6Ekf:-KtXagEUPn94hTSU6Ekg:b-lm866x) ([raw file](https://github.com/m-lab/annotation-service/blob/fd3264609e2d5a504b12a07ec0d4ca442e48bb63/search/geo-search_test.go#L117)):*
> ```Go
> 	i := 0
> 	for i < len(ipv6) {
> 		ipMiddle := findMiddle(ipv6[i].IPAddressLow, ipv6[i].IPAddressHigh)
> ```

Can you start the linear search at item i (in other words, pass ipv6[i:] to SearchList?  This should be way faster and still produce the right result. 

---

*[search/geo-search_test.go, line 147 at r4](https://reviewable.io:443/reviews/m-lab/annotation-service/38#-KtXb9pwHk4Fhdld9GSZ:-KtXb9pwHk4Fhdld9GS_:bt3ixlk) ([raw file](https://github.com/m-lab/annotation-service/blob/fd3264609e2d5a504b12a07ec0d4ca442e48bb63/search/geo-search_test.go#L147)):*
> ```Go
> 		ipMiddle := findMiddle(ipv4[i].IPAddressLow, ipv4[i].IPAddressHigh)
> 		ipBin, errBin := search.SearchBinary(ipv4, ipMiddle.String())
> 		ipLin, errLin := search.SearchList(ipv4, ipMiddle.String())
> ```

Same ipv4[i:] suggestion as above.

---

*[search/geo-search_test.go, line 160 at r4](https://reviewable.io:443/reviews/m-lab/annotation-service/38#-KtXbN6KmvQ0gec_7vZp:-KtXbN6LlqDjQYkKxm5e:btnt1my) ([raw file](https://github.com/m-lab/annotation-service/blob/fd3264609e2d5a504b12a07ec0d4ca442e48bb63/search/geo-search_test.go#L160)):*
> ```Go
> 
> }
> func findMiddle(low, high net.IP) net.IP {
> ```

This is doing something non-obvious, so it needs a comment.  Could it be easily adapted to split for ANY ip address including IPv6?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/38)*

**Comment by gfr10598** [comment]
Review status: 5 of 10 files reviewed at latest revision, 10 unresolved discussions.

---

*[parser/geo-g2.go, line 230 at r3](https://reviewable.io:443/reviews/m-lab/annotation-service/38#-KtX4Oc7g9rBMrhifT5Z:-KtXbtRlDCV0TcRxoZ7B:b-4kicnj) ([raw file](https://github.com/m-lab/annotation-service/blob/5c28a37a0c1a8baf10546dca26d33fec3a419857/parser/geo-g2.go#L230)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

> net.IPv4(255, 255, 255, 255)
How is IPv6 handled?
</blockquote></details>

Or perhaps I should ask if this correctly handles IPv6 case.  If so, add a comment?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/38)*

**Comment by yachang** [comment]
:lgtm:

---

Review status: 5 of 10 files reviewed at latest revision, 10 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/38#-:-KuVE820Y5ZEHZWGDA2u:bnfp4nl)*

**Comment by gfr10598** [comment]
Submitting with unresolved comments, since internship ended.
Will followup with additional PRs to address issues.

**Comment by gfr10598** [comment]
Review status: 5 of 10 files reviewed at latest revision, 10 unresolved discussions.

---

*[parser/geo-g1.go, line 93 at r3](https://reviewable.io:443/reviews/m-lab/annotation-service/38#-KtX4Y2hsblMcF6R5vZ7:-Ku_xDrzY4OraQ96y6oH:buetk1i) ([raw file](https://github.com/m-lab/annotation-service/blob/5c28a37a0c1a8baf10546dca26d33fec3a419857/parser/geo-g1.go#L93)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Please add a comment here and in the package header that GeoLite1 is IPv4 only.
</blockquote></details>

Done in finish-comments branch

---

*[parser/geo-g1.go, line 96 at r3](https://reviewable.io:443/reviews/m-lab/annotation-service/38#-KtX0-6FRuDeAeVU2YLz:-Kua9Ri0n3xqs_NSMGPv:bjczjnc) ([raw file](https://github.com/m-lab/annotation-service/blob/5c28a37a0c1a8baf10546dca26d33fec3a419857/parser/geo-g1.go#L96)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Add good comments for list and stack.
</blockquote></details>

Done in finish-comments branch.

---

*[parser/geo-g1.go, line 159 at r3](https://reviewable.io:443/reviews/m-lab/annotation-service/38#-KtX1cAzUrxGxbNqbyJD:-Kua7j1gGell2LP63KvB:buetk1i) ([raw file](https://github.com/m-lab/annotation-service/blob/5c28a37a0c1a8baf10546dca26d33fec3a419857/parser/geo-g1.go#L159)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

three typos.
// if there's a gap in between immediately nested IP's
</blockquote></details>

Done in finish-comments branch

---

*[parser/geo-g1.go, line 185 at r3](https://reviewable.io:443/reviews/m-lab/annotation-service/38#-KtX0iCHyOnmg2HlcZog:-Kua7Mgr4Ko2lZTkQckz:b-hhsixh) ([raw file](https://github.com/m-lab/annotation-service/blob/5c28a37a0c1a8baf10546dca26d33fec3a419857/parser/geo-g1.go#L185)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Remove this log?
</blockquote></details>

Done by Shelby.

---

*[parser/geo-g2.go, line 194 at r3](https://reviewable.io:443/reviews/m-lab/annotation-service/38#-KtX6-bGbUTqh8eTo8ib:-Kua1K834e7WOAkAnbwX:buetk1i) ([raw file](https://github.com/m-lab/annotation-service/blob/5c28a37a0c1a8baf10546dca26d33fec3a419857/parser/geo-g2.go#L194)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

I believe this if len(stack) block is common between geo1 and geo2.  If that is correct, please pull it out into a common function.
</blockquote></details>

Done in finish-comments branch

---

*[parser/geo-g2.go, line 210 at r3](https://reviewable.io:443/reviews/m-lab/annotation-service/38#-KtX1xokRoCkHvSTXlnN:-Kua3SaxEBymuLVgNCfF:b2udc7b) ([raw file](https://github.com/m-lab/annotation-service/blob/5c28a37a0c1a8baf10546dca26d33fec3a419857/parser/geo-g2.go#L210)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

PlusOne should actually be lower case, because it is in the parser package.
</blockquote></details>

Leaving as is because also called from search package.

---

*[parser/geo-g2.go, line 230 at r3](https://reviewable.io:443/reviews/m-lab/annotation-service/38#-KtX4Oc7g9rBMrhifT5Z:-Kua3tRrrpBymMVbvZMK:b-sx84ma) ([raw file](https://github.com/m-lab/annotation-service/blob/5c28a37a0c1a8baf10546dca26d33fec3a419857/parser/geo-g2.go#L230)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Or perhaps I should ask if this correctly handles IPv6 case.  If so, add a comment?
</blockquote></details>

obsolete

---

*[search/geo-search_test.go, line 117 at r4](https://reviewable.io:443/reviews/m-lab/annotation-service/38#-KtXagEUPn94hTSU6Ekf:-Kua9WzFqqWbEjIcd8Hk:b-e0img0) ([raw file](https://github.com/m-lab/annotation-service/blob/fd3264609e2d5a504b12a07ec0d4ca442e48bb63/search/geo-search_test.go#L117)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Can you start the linear search at item i (in other words, pass ipv6[i:] to SearchList?  This should be way faster and still produce the right result. 
</blockquote></details>

Done in finish-comments branch (PR #39)

---

*[search/geo-search_test.go, line 147 at r4](https://reviewable.io:443/reviews/m-lab/annotation-service/38#-KtXb9pwHk4Fhdld9GSZ:-Kua9fZP_1FmEXJLJnkE:b-e0img0) ([raw file](https://github.com/m-lab/annotation-service/blob/fd3264609e2d5a504b12a07ec0d4ca442e48bb63/search/geo-search_test.go#L147)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Same ipv4[i:] suggestion as above.
</blockquote></details>

Done in finish-comments branch (PR #39)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/38)*

**Pull request merged**
