### PR TITLE
Fix annotator to populate region field

### PR DESCRIPTION
**Pull request by gfr10598**
This adds code and tests to populate the geolocation "region" field, which is needed for the viz pipeline.

It appears that we also are not populating area_code or country3.  I have added placeholders for these, but they are still not populated.  I will add an issue.

This is now running in staging and verified.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/annotation-service/55)

### CODE REVIEW

**Comment by stephen-soltesz** [comment]
:lgtm:

---

Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[parser/g2_test.go, line 10 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/55#-L1rRfGtxtDAQW7Xo7m6:-L1rRfGtxtDAQW7Xo7m7:bm4vgkv) ([raw file](https://github.com/m-lab/annotation-service/blob/0637b66acf07a61cfe78ac2d1d06dd719cf96722/parser/g2_test.go#L10)):*
> github.com/go-test/deep

This looks handy!

---

*[parser/g2_test.go, line 173 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/55#-L1rRvRcq2iS355nZpbz:-L1rRvRdWB_42SEhnVa8:b-vsjtef) ([raw file](https://github.com/m-lab/annotation-service/blob/0637b66acf07a61cfe78ac2d1d06dd719cf96722/parser/g2_test.go#L173)):*
> ```Go
> 	}
> 
> 	if diff := deep.Equal(locationList, locList); diff != nil {
> ```

These names are ambiguously similar. Please prefer something with a prefix like "expectedLocList" or "actualLocList" to distinguish between expected pre-defined values and actual calculated values.

---

*[parser/geo-g2.go, line 80 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/55#-L1rTOZeAqLZ4zvo_Bxh:-L1rTOZeAqLZ4zvo_Bxi:bs1r3b5) ([raw file](https://github.com/m-lab/annotation-service/blob/0637b66acf07a61cfe78ac2d1d06dd719cf96722/parser/geo-g2.go#L80)):*
> ```Go
> // Create Location list for GLite2 databases
> // TODO This code is a bit fragile.  Should probably parse the header and
> // use that to guide the parsing of the rows.
> ```

Yikes. Please create an issue if there is not already one. A go package for reading CSV as a map would be a valuable contribution in general.

---

*[parser/geo-g2.go, line 132 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/55#-L1rTtQi8gPVleYE3EW0:-L1rTtQi8gPVleYE3EW1:b9zhtkq) ([raw file](https://github.com/m-lab/annotation-service/blob/0637b66acf07a61cfe78ac2d1d06dd719cf96722/parser/geo-g2.go#L132)):*
> ```Go
> 			return nil, nil, errors.New("Corrupted Data: country name should be letters")
> 		}
> 		// TODO - should probably do some validation.
> ```

Is there any evidence of problems with these values so far?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/55#-:-L1rUZyEqpoHdsd7KCSr:bnfp4nl)*

**Comment by gfr10598** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[parser/g2_test.go, line 173 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/55#-L1rRvRcq2iS355nZpbz:-L1sudM2QyMMG6qSXWT8:b-896fix) ([raw file](https://github.com/m-lab/annotation-service/blob/0637b66acf07a61cfe78ac2d1d06dd719cf96722/parser/g2_test.go#L173)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

These names are ambiguously similar. Please prefer something with a prefix like "expectedLocList" or "actualLocList" to distinguish between expected pre-defined values and actual calculated values.
</blockquote></details>

Done.

---

*[parser/geo-g2.go, line 80 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/55#-L1rTOZeAqLZ4zvo_Bxh:-L1svHJxz_wnqvw0frke:b-896fix) ([raw file](https://github.com/m-lab/annotation-service/blob/0637b66acf07a61cfe78ac2d1d06dd719cf96722/parser/geo-g2.go#L80)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Yikes. Please create an issue if there is not already one. A go package for reading CSV as a map would be a valuable contribution in general.
</blockquote></details>

Done.

---

*[parser/geo-g2.go, line 132 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/55#-L1rTtQi8gPVleYE3EW0:-L1svIUazkEZja3YyK00:b54jyc) ([raw file](https://github.com/m-lab/annotation-service/blob/0637b66acf07a61cfe78ac2d1d06dd719cf96722/parser/geo-g2.go#L132)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Is there any evidence of problems with these values so far?
</blockquote></details>

Nope.  Would be better to implement the header parsing, then this would be less of an issue.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/55)*

**Comment by gfr10598** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[parser/g2_test.go, line 10 at r1](https://reviewable.io:443/reviews/m-lab/annotation-service/55#-L1rRfGtxtDAQW7Xo7m6:-L1svS67Kw1Zmb1Wf9Wk:b-896fix) ([raw file](https://github.com/m-lab/annotation-service/blob/0637b66acf07a61cfe78ac2d1d06dd719cf96722/parser/g2_test.go#L10)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

> github.com/go-test/deep

This looks handy!
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/55)*

**Comment by gfr10598** [comment]
Reviewed 11 of 12 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/55)*

**Pull request merged**
