### PR TITLE
Add missing fields to /annotate's response

### PR DESCRIPTION
**Pull request by robertodauria**
This PR adds the following fields to the JSON response returned by the API:
- CIDR
- ASNumber
- ASName
- Missing

It also adds the data/asnames.ipinfo.csv file to retrieve AS names from numbers.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/annotation-service/277)

### CODE REVIEW

**Review by stephen-soltesz — CHANGES_REQUESTED** [review]
Excellent! A few comments.

> Reviewed 8 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/m-lab/annotation-service/277#-:-MX2wHh7CbT1_1_fgIFw:b-2kz1fh)* status: 0 of 1 LGTMs obtained

___
*[asn/asn-loader.go, line 28 at r1](https://reviewable.io/reviews/m-lab/annotation-service/277#-MX2vCNf4objIedoyvT6:-MX2vCNf4objIedoyvT7:b-pcyd4m) ([raw file](https://github.com/m-lab/annotation-service/blob/e9616152d761bfc1c2ab8edde10865e278ddf6cc/asn/asn-loader.go#L28)):*
> ```Go
> 	errExtractDateFromFilename = errors.New("cannot extract date from input filename")
> 
> 	ASNamesFile = "data/asnames.ipinfo.csv"
> ```

Please add comments explaining this is a global package variable and why it's needed.
___
*[asn/asn-loader.go, line 146 at r1](https://reviewable.io/reviews/m-lab/annotation-service/277#-MX2vxul0NLcMmmPMeGf:-MX2vxul0NLcMmmPMeGg:bypfe64) ([raw file](https://github.com/m-lab/annotation-service/blob/e9616152d761bfc1c2ab8edde10865e278ddf6cc/asn/asn-loader.go#L146)):*
> ```Go
> 		content, err := ioutil.ReadFile(ASNamesFile)
> 		rtx.Must(err, "Cannot load asnames files")
> 		asnames, err = ipinfo.Parse(content)
> ```

Excellent reuse!
___
*[iputils/iputils.go, line 292 at r1](https://reviewable.io/reviews/m-lab/annotation-service/277#-MX2tfMcBgpgrqFTxKJG:-MX2tfMcBgpgrqFTxKJH:byxkp46) ([raw file](https://github.com/m-lab/annotation-service/blob/e9616152d761bfc1c2ab8edde10865e278ddf6cc/iputils/iputils.go#L292)):*
> ```Go
> }
> 
> func CIDRRange(lowIP, highIP net.IP) string {
> ```

Please add docstring. Please include requirements on lowIP and highIP input.

Please add direct unit tests.

(you are right to feel a tension between doing things "right" and the reality that we plan to retire this service. *Because* we are retiring this service the data it exports will be frozen in time, so we want to be (reasonably) as sure as possible that things are as intended).

**Review by stephen-soltesz — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/annotation-service/277)* status: 0 of 1 LGTMs obtained

___
*[asn/asn-loader.go, line 28 at r1](https://reviewable.io/reviews/m-lab/annotation-service/277#-MX2vCNf4objIedoyvT6:-MX4XwXa8Y4kcTj6ZaIy:bmd07tb) ([raw file](https://github.com/m-lab/annotation-service/blob/e9616152d761bfc1c2ab8edde10865e278ddf6cc/asn/asn-loader.go#L28)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Please add comments explaining this is a global package variable and why it's needed.
</blockquote></details>

( meant to put this on the variable below this comment)

**Review by robertodauria — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/annotation-service/277)* status: 0 of 1 LGTMs obtained

___
*[asn/asn-loader.go, line 28 at r1](https://reviewable.io/reviews/m-lab/annotation-service/277#-MX2vCNf4objIedoyvT6:-MX6rIfB4SzWxbNaBcGm:b-896fix) ([raw file](https://github.com/m-lab/annotation-service/blob/e9616152d761bfc1c2ab8edde10865e278ddf6cc/asn/asn-loader.go#L28)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

( meant to put this on the variable below this comment)
</blockquote></details>

Done.
___
*[iputils/iputils.go, line 292 at r1](https://reviewable.io/reviews/m-lab/annotation-service/277#-MX2tfMcBgpgrqFTxKJG:-MX7399j0fnDOCLrUcBQ:b-896fix) ([raw file](https://github.com/m-lab/annotation-service/blob/e9616152d761bfc1c2ab8edde10865e278ddf6cc/iputils/iputils.go#L292)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Please add docstring. Please include requirements on lowIP and highIP input.

Please add direct unit tests.

(you are right to feel a tension between doing things "right" and the reality that we plan to retire this service. *Because* we are retiring this service the data it exports will be frozen in time, so we want to be (reasonably) as sure as possible that things are as intended).
</blockquote></details>

Done.

**Review by stephen-soltesz — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/m-lab/annotation-service/277#-:-MX773CX1ubMOCsFhu1l:bnfp4nl)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Review by stephen-soltesz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/annotation-service/277)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[asn/asn-loader.go, line 147 at r2](https://reviewable.io/reviews/m-lab/annotation-service/277#-MXAIBEW3Dv-RHqr9TC7:-MXAIBEW3Dv-RHqr9TC8:bwklnyw) ([raw file](https://github.com/m-lab/annotation-service/blob/ed6f7230f86e3a2bf7030b55db809f9dceae7e4e/asn/asn-loader.go#L147)):*
> ```Go
> 
> 	// Note: this is not concurrency-safe.
> 	if asnames == nil {
> ```

Perhaps this could use `sync.Once.Do()`? (doesn't have to be this PR)

**Review by robertodauria — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/annotation-service/277)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[asn/asn-loader.go, line 147 at r2](https://reviewable.io/reviews/m-lab/annotation-service/277#-MXAIBEW3Dv-RHqr9TC7:-MXCJ6b-COs4YIFl_rox:b-rsqjph) ([raw file](https://github.com/m-lab/annotation-service/blob/ed6f7230f86e3a2bf7030b55db809f9dceae7e4e/asn/asn-loader.go#L147)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Perhaps this could use `sync.Once.Do()`? (doesn't have to be this PR)
</blockquote></details>

I changed it to use `sync.Once.Do()` as I discovered yesterday that the loading of these files happens concurrently. Any thoughts before I merge?

**Review by stephen-soltesz — APPROVED** [review]
I think the build is failing due to RAM -- updating that could be in this pr or a separate one.

> *[Reviewable](https://reviewable.io/reviews/m-lab/annotation-service/277#-:-MXCVQJMCAqMJBeXYk_N:b-11c7n)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[asn/asn-loader.go, line 147 at r2](https://reviewable.io/reviews/m-lab/annotation-service/277#-MXAIBEW3Dv-RHqr9TC7:-MXCVO1Q9b_gyyvy5GSH:beb9xy7) ([raw file](https://github.com/m-lab/annotation-service/blob/ed6f7230f86e3a2bf7030b55db809f9dceae7e4e/asn/asn-loader.go#L147)):*
<details><summary><i>Previously, robertodauria (Roberto D'Auria) wrote…</i></summary><blockquote>

I changed it to use `sync.Once.Do()` as I discovered yesterday that the loading of these files happens concurrently. Any thoughts before I merge?
</blockquote></details>

lgtm :+1:

**Pull request merged**
