### PR TITLE
Add time-based dataset selection logic

### PR DESCRIPTION
**Pull request by yachang**
This change is [Reviewable](https://reviewable.io/reviews/m-lab/annotation-service/89)

### CODE REVIEW

**Review by gfr10598 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/annotation-service/89)* status: 0 of 1 LGTMs obtained

___
*[handler/dataset/legacy-data.go, line 1 at r6](https://reviewable.io/reviews/m-lab/annotation-service/89#-LOz7cs712ZNwPDafIZR:-LOz7cs712ZNwPDafIZS:bcaedjk) ([raw file](https://github.com/m-lab/annotation-service/blob/bc39f2d32789cf3430a0e88b4f42577695307c55/handler/dataset/legacy-data.go#L1)):*
> ```Go
> package dataset
> ```

What is the reason for combining this package into handler?  Was there a new dependency cycle?

**Review by yachang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/annotation-service/89)* status: 0 of 1 LGTMs obtained

___
*[handler/dataset/legacy-data.go, line 1 at r6](https://reviewable.io/reviews/m-lab/annotation-service/89#-LOz7cs712ZNwPDafIZR:-LP1BNry58cN9hkTX_F7:b-rd9rxs) ([raw file](https://github.com/m-lab/annotation-service/blob/bc39f2d32789cf3430a0e88b4f42577695307c55/handler/dataset/legacy-data.go#L1)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

What is the reason for combining this package into handler?  Was there a new dependency cycle?
</blockquote></details>

I feel it is not necessary to create a new package for legacy datasets. Essentially, it is all about the logic to handle the annotation requests. Putting them together make the maintenance easier.

**Review by gfr10598 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/annotation-service/89)* status: 0 of 1 LGTMs obtained

___
*[handler/handler_test.go, line 1 at r6](https://reviewable.io/reviews/m-lab/annotation-service/89#-LP1ad5s-ntiZtI_ba_x:-LP1ad5s-ntiZtI_ba_y:b-enr54t) ([raw file](https://github.com/m-lab/annotation-service/blob/3f5c2a6254ffa0efb34cb0929f5cec03030e73dc/handler/handler_test.go#L1)):*
> ```Go
> package handler_test
> ```

Since you are adding integration tests, this should now include line at the top
// build +integration
You will then need to add -tags=integration in the test lines in .travis.yml

Ideally, you should separate the tests that touch external services into a separate _int_test file.  Then the other tests can be run without using the integration tag.

An even better option would be to use an stiface fake to provide the test files.  I'd suggest adding a TODO to convert the tests sometime soon.

**Review by gfr10598 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, 1 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/m-lab/annotation-service/89)* status: 0 of 1 LGTMs obtained

___
*[handler/handler.go, line 39 at r6](https://reviewable.io/reviews/m-lab/annotation-service/89#-LP1dBCiDqIBjw2riiiG:-LP1dBCiDqIBjw2riiiH:b-3ixze1) ([raw file](https://github.com/m-lab/annotation-service/blob/3f5c2a6254ffa0efb34cb0929f5cec03030e73dc/handler/handler.go#L39)):*
> ```Go
> 	// A mutex to make sure that we are not reading from a dataset
> 	// pointer while trying to update it
> 	Geolite2DatasetMutex = &sync.RWMutex{}
> ```

Please put the mutex declaration next to the object it protects.
___
*[handler/handler.go, line 246 at r6](https://reviewable.io/reviews/m-lab/annotation-service/89#-LP1eGYr8I_-s2PvWqR2:-LP1eGYr8I_-s2PvWqR3:bqd6ecc) ([raw file](https://github.com/m-lab/annotation-service/blob/3f5c2a6254ffa0efb34cb0929f5cec03030e73dc/handler/handler.go#L246)):*
> ```Go
> 	if request.Timestamp.After(LatestDatasetDate) {
> 		log.Println("Use latest dataset")
> 		return UseGeoLite2Dataset(request, CurrentGeoDataset, currentDataMutex)
> ```

Pretty sure you need to take the lock, copy the pointer, release the lock, and pass the pointer into this function.  I think this is causing the pointer to be copied without holding the lock, and then the lock it taken inside the function, where it isn't needed.

Let's make this cleaner and easier to understand by using local variable for currentGeoDataset, and providing SetCurrent() and GetCurrentDataset() that do all the lock handling.  Should probably do the same for the maps.
___
*[handler/legacy-data.go, line 228 at r6](https://reviewable.io/reviews/m-lab/annotation-service/89#-LP1cENTEmzxStNgS1uw:-LP1cENTEmzxStNgS1ux:b-ss0bb5) ([raw file](https://github.com/m-lab/annotation-service/blob/3f5c2a6254ffa0efb34cb0929f5cec03030e73dc/handler/legacy-data.go#L228)):*
> ```Go
> 	}
> 	record := gi.GetRecord(ip)
> 	fmt.Printf("%v\n", record)
> ```

I don't think we should be using fmt.Print* in production code.  Please search for all uses of fmt, and either remove, or if they are important for debugging, use log.
___
*[handler/dataset/legacy-data.go, line 1 at r6](https://reviewable.io/reviews/m-lab/annotation-service/89#-LOz7cs712ZNwPDafIZR:-LP1biRJCFsgA5QgtKDN:bsruljq) ([raw file](https://github.com/m-lab/annotation-service/blob/bc39f2d32789cf3430a0e88b4f42577695307c55/handler/dataset/legacy-data.go#L1)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

I feel it is not necessary to create a new package for legacy datasets. Essentially, it is all about the logic to handle the annotation requests. Putting them together make the maintenance easier. 
</blockquote></details>

Let's discuss offline.  In the long run it is important to strike a good balance between managing dependencies and keeping packages from getting too big and doing too many things.

**Review by gfr10598 — COMMENTED** [review]
BTW, when working on code that was written by interns (or at least this code), you should generally anticipate that there is technical debt that we need to pay off.  Anticipate spending time refactoring and generally improving the code.

> *[Reviewable](https://reviewable.io/reviews/m-lab/annotation-service/89#-:-LP1fDMgAteD8-pvg9A0:brbqbxc)* status: 0 of 1 LGTMs obtained

**Review by yachang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/annotation-service/89)* status: 0 of 1 LGTMs obtained

___
*[handler/handler.go, line 39 at r6](https://reviewable.io/reviews/m-lab/annotation-service/89#-LP1dBCiDqIBjw2riiiG:-LP6YDhF1MEekoDNzdQB:b-896fix) ([raw file](https://github.com/m-lab/annotation-service/blob/3f5c2a6254ffa0efb34cb0929f5cec03030e73dc/handler/handler.go#L39)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Please put the mutex declaration next to the object it protects.
</blockquote></details>

Done.
___
*[handler/handler.go, line 246 at r6](https://reviewable.io/reviews/m-lab/annotation-service/89#-LP1eGYr8I_-s2PvWqR2:-LP6e0p6AkWIl1hIYUML:b-2hlyih) ([raw file](https://github.com/m-lab/annotation-service/blob/3f5c2a6254ffa0efb34cb0929f5cec03030e73dc/handler/handler.go#L246)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Pretty sure you need to take the lock, copy the pointer, release the lock, and pass the pointer into this function.  I think this is causing the pointer to be copied without holding the lock, and then the lock it taken inside the function, where it isn't needed.

Let's make this cleaner and easier to understand by using local variable for currentGeoDataset, and providing SetCurrent() and GetCurrentDataset() that do all the lock handling.  Should probably do the same for the maps.
</blockquote></details>

func UseGeoLite2Dataset(request *common.RequestData, dataset *parser.GeoDataset, mutex *sync.RWMutex)

Both dataset and mutex are pointer, and passed by pointer to UseGeoLite2Dataset() 

I will add a unittest to verify that the lock is working here.

**Review by yachang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/annotation-service/89)* status: 0 of 1 LGTMs obtained

___
*[handler/handler_test.go, line 1 at r6](https://reviewable.io/reviews/m-lab/annotation-service/89#-LP1ad5s-ntiZtI_ba_x:-LPS-tXK4UoRC6qgMVc8:b-j1vdsl) ([raw file](https://github.com/m-lab/annotation-service/blob/3f5c2a6254ffa0efb34cb0929f5cec03030e73dc/handler/handler_test.go#L1)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Since you are adding integration tests, this should now include line at the top
// build +integration
You will then need to add -tags=integration in the test lines in .travis.yml

Ideally, you should separate the tests that touch external services into a separate _int_test file.  Then the other tests can be run without using the integration tag.

An even better option would be to use an stiface fake to provide the test files.  I'd suggest adding a TODO to convert the tests sometime soon.

</blockquote></details>

TODO added

**Review by yachang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/annotation-service/89)* status: 0 of 1 LGTMs obtained

___
*[handler/dataset/legacy-data.go, line 1 at r6](https://reviewable.io/reviews/m-lab/annotation-service/89#-LOz7cs712ZNwPDafIZR:-LPS0BWeCVM2lVWDx_x8:b647i5t) ([raw file](https://github.com/m-lab/annotation-service/blob/bc39f2d32789cf3430a0e88b4f42577695307c55/handler/dataset/legacy-data.go#L1)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Let's discuss offline.  In the long run it is important to strike a good balance between managing dependencies and keeping packages from getting too big and doing too many things.
</blockquote></details>

offline discussed.

**Review by yachang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/annotation-service/89)* status: 0 of 1 LGTMs obtained

___
*[handler/legacy-data.go, line 228 at r6](https://reviewable.io/reviews/m-lab/annotation-service/89#-LP1cENTEmzxStNgS1uw:-LPS0HxQ4Bho7nUEsukR:b-896fix) ([raw file](https://github.com/m-lab/annotation-service/blob/3f5c2a6254ffa0efb34cb0929f5cec03030e73dc/handler/legacy-data.go#L228)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

I don't think we should be using fmt.Print* in production code.  Please search for all uses of fmt, and either remove, or if they are important for debugging, use log.
</blockquote></details>

Done.

**Review by gfr10598 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/annotation-service/89)* status: 0 of 1 LGTMs obtained

___
*[handler/handler.go, line 35 at r10](https://reviewable.io/reviews/m-lab/annotation-service/89#-LPS4itOCjdXmbJfmTJj:-LPS4itOCjdXmbJfmTJk:bcub26) ([raw file](https://github.com/m-lab/annotation-service/blob/da58ddbf635dd2990146eed9bea0d0c040ce4b1e/handler/handler.go#L35)):*
> ```Go
> }
> 
> func (d *DatasetInMemory) Init() {
> ```

Suggest you put this init code in NewDatasetInMemory() function.
___
*[handler/handler.go, line 80 at r10](https://reviewable.io/reviews/m-lab/annotation-service/89#-LPS58fe62bC9dN8cQcY:-LPS58fe62bC9dN8cQcZ:b-5mezhv) ([raw file](https://github.com/m-lab/annotation-service/blob/da58ddbf635dd2990146eed9bea0d0c040ce4b1e/handler/handler.go#L80)):*
> ```Go
> var (
> 	// This is a struct containing the latest data for the annotator to search
> 	// and reply with. The size of data map inside is 1.
> ```

Here and above, not sure what the references to data map size mean.
___
*[handler/handler_test.go, line 1 at r6](https://reviewable.io/reviews/m-lab/annotation-service/89#-LP1ad5s-ntiZtI_ba_x:-LPS7c9GAIvaoCXdFsg8:bqkleoq) ([raw file](https://github.com/m-lab/annotation-service/blob/3f5c2a6254ffa0efb34cb0929f5cec03030e73dc/handler/handler_test.go#L1)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

TODO added
</blockquote></details>

Please also add the // build +integration at the top.
___
*[handler/legacy-data.go, line 221 at r10](https://reviewable.io/reviews/m-lab/annotation-service/89#-LPS8EV55PFThImSApcU:-LPS8EV55PFThImSApcV:b9ip0xl) ([raw file](https://github.com/m-lab/annotation-service/blob/da58ddbf635dd2990146eed9bea0d0c040ce4b1e/handler/legacy-data.go#L221)):*
> ```Go
> 
> func Round(x float32) float64 {
> 	i, _ := strconv.ParseFloat(fmt.Sprintf("%.3f", x), 64)
> ```

Don't understand what this is.  It is very inefficient, so prefer you use a cast or a library function.

**Review by yachang — COMMENTED** [review]
Multiple improvements over last week:

- fd leak when loading the new dataset
- memory leak
- 3rd-party go wrapper for legacy API: always kick out loaded binary and have to load it again immediately
- Add IPv6 support for legacy dataset
- perf tuning, reduce response time from almost 1s to 30ms.

> *[Reviewable](https://reviewable.io/reviews/m-lab/annotation-service/89#-:-LQZMnjQ0w0Dtsrv685N:bqeppah)* status: 0 of 1 LGTMs obtained

**Review by gfr10598 — CHANGES_REQUESTED** [review]
There are a number of comments I made earlier that don't seem to have been addressed. 

> *[Reviewable](https://reviewable.io/reviews/m-lab/annotation-service/89#-:-LQ_GfdUBwHDK_dCZXT3:bbcylxj)* status: 0 of 1 LGTMs obtained

___
*[main.go, line 24 at r11](https://reviewable.io/reviews/m-lab/annotation-service/89#-LQ_Fcc03DV8mK5ztHps:-LQ_Fcc03DV8mK5ztHpt:bpcmejc) ([raw file](https://github.com/m-lab/annotation-service/blob/e5834b9fae70490db06d4c4faf6204d5e526f668/main.go#L24)):*
> ```Go
> 		return
> 	}
> 	handler.PopulateLatestData()
> ```

This discards all of the loaded datasets, which doesn't seem like the right thing to do.  Also, I believe you would need to hold the appropriate locks, because this overwrites the maps.
___
*[handler/handler.go, line 35 at r10](https://reviewable.io/reviews/m-lab/annotation-service/89#-LPS4itOCjdXmbJfmTJj:-LQ_FyA3Ekj0MB4oOPaA:br0tnu0) ([raw file](https://github.com/m-lab/annotation-service/blob/da58ddbf635dd2990146eed9bea0d0c040ce4b1e/handler/handler.go#L35)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Suggest you put this init code in NewDatasetInMemory() function.
</blockquote></details>

Suggest again to add a NewDatasetInMemory function, and eliminate the Init function.

**Review by gfr10598 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/annotation-service/89)* status: 0 of 1 LGTMs obtained

___
*[handler/handler.go, line 29 at r11](https://reviewable.io/reviews/m-lab/annotation-service/89#-LQ_H8V6-O-zNTpdWFmD:-LQ_H8V6-O-zNTpdWFmE:bqzxgxd) ([raw file](https://github.com/m-lab/annotation-service/blob/e5834b9fae70490db06d4c4faf6204d5e526f668/handler/handler.go#L29)):*
> ```Go
> 	// Maximum number of legacy datasets in memory.
> 	// IPv4 and IPv6 are separated for legacy datasets.
> 	MaxHistoricalLegacyDataset = 6
> ```

Why 3 for Geolite, and 6 for legacy?  Seems like there should be a single limit that applies to all of them.  Because we have 4 data types, and the gardener for each of them is independent, I expect we will need a minimum of 8 concurrent datasets at any given time, and possibly as many as 12.  But whether they will be older or newer is not under our control.

I think this needs to be managed as a cache, and you need to keep track of the time last used to determine which one to kick out if you run out of space.
___
*[handler/handler.go, line 31 at r11](https://reviewable.io/reviews/m-lab/annotation-service/89#-LQ_H4bz9j4T8RjwfSiw:-LQ_H4bz9j4T8RjwfSix:b40m22y) ([raw file](https://github.com/m-lab/annotation-service/blob/e5834b9fae70490db06d4c4faf6204d5e526f668/handler/handler.go#L31)):*
> ```Go
> 	MaxHistoricalLegacyDataset = 6
> 
> 	// Maximum number of pending datasets that can be loaded at the same time.
> ```

What is the reason for limiting this to two?
___
*[handler/handler.go, line 121 at r11](https://reviewable.io/reviews/m-lab/annotation-service/89#-LQ_Hq6vCogk0MZ16g0V:-LQ_Hq6w8Dr2yGzquJ3Q:b7js5fu) ([raw file](https://github.com/m-lab/annotation-service/blob/e5834b9fae70490db06d4c4faf6204d5e526f668/handler/handler.go#L121)):*
> ```Go
> 	LegacyDatasetInMemory DatasetInMemory
> 
> 	// The list of dataset that was loading right now.
> ```

I would recommend tracking whether a dataset is loading, or active, within the same map as the pointer to the dataset.

All of this code would be a lot easier to follow if you have a single object that can contain one dataset of any kind.  Then a single map from date range to that container object. 

To load a dataset:
  Take the reader lock
   Discover the dataset is missing,
  Take the writer lock
  Ensure there is memory space, possibly evicting another dataset container
  Add empty container (indicating that the dataset is being loaded)
  Unlock
  Load the dataset
  Take the writer lock
  update the container to point to the new dataset.
  Unlock.

**Pull request closed without merging**
