### PR TITLE
More refactor version

### PR DESCRIPTION
**Pull request by yachang**
This change is [Reviewable](https://reviewable.io/reviews/m-lab/annotation-service/106)

### CODE REVIEW

**Review by gfr10598 — CHANGES_REQUESTED** [review]
> Reviewed 8 of 20 files at r5, 2 of 10 files at r7.
> *[Reviewable](https://reviewable.io/reviews/m-lab/annotation-service/106)* status: 0 of 1 LGTMs obtained

___
*[dataset/dataset-in-memory.go, line 46 at r8](https://reviewable.io/reviews/m-lab/annotation-service/106#-LSGbeb0D0nHq1wGo_0j:-LSGbeb0D0nHq1wGo_0k:bhctllz) ([raw file](https://github.com/m-lab/annotation-service/blob/5620de14a36c71a72947e87d37cedf0b0b36439e/dataset/dataset-in-memory.go#L46)):*
> ```Go
> }
> 
> func Deletes(a []string, x string) []string {
> ```

Not crazy about this function.  Suggest instead you use a map[string]struct{} to store the pending loads.  Then you can just use golang delete().

Also, this looks like new functionality, so it would be better to avoid it in a large refactoring.
___
*[handler/init.go, line 1 at r8](https://reviewable.io/reviews/m-lab/annotation-service/106#-LSG_4we4gpRun5fwyLw:-LSG_4we4gpRun5fwyLx:bwbb1im) ([raw file](https://github.com/m-lab/annotation-service/blob/5620de14a36c71a72947e87d37cedf0b0b36439e/handler/init.go#L1)):*
> ```Go
> package handler
> ```

Please add a TODO - most of this code should move to the dataset package, or a maybe 
datasetloader package.

**Review by gfr10598 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/annotation-service/106)* status: 0 of 1 LGTMs obtained

___
*[dataset/dataset-in-memory.go, line 1 at r8](https://reviewable.io/reviews/m-lab/annotation-service/106#-LSGcESkE6nT_4ejBwzq:-LSGcESkE6nT_4ejBwzr:b-rd1gw4) ([raw file](https://github.com/m-lab/annotation-service/blob/5620de14a36c71a72947e87d37cedf0b0b36439e/dataset/dataset-in-memory.go#L1)):*
> ```Go
> package dataset
> ```

Is this all new functionality?  Should defer to the next PR.

**Review by gfr10598 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 20 files at r5, 1 of 10 files at r7.
> *[Reviewable](https://reviewable.io/reviews/m-lab/annotation-service/106)* status: 0 of 1 LGTMs obtained

___
*[dataset/dataset-in-memory.go, line 59 at r8](https://reviewable.io/reviews/m-lab/annotation-service/106#-LSGcP_UBs2TQfIbH97P:-LSGcP_UBs2TQfIbH97Q:b-gm9hfb) ([raw file](https://github.com/m-lab/annotation-service/blob/5620de14a36c71a72947e87d37cedf0b0b36439e/dataset/dataset-in-memory.go#L59)):*
> ```Go
> 
> // searchGeoLocation is interface that handle the dataset related operations
> type searchGeoLocation interface {
> ```

Generally, interfaces should be exported.

**Review by yachang — COMMENTED** [review]
More refactoring according to offline discussion:

1. main.go only talk with handler package
2. handler only depends on cache package, which hold the object of datasets in memory
3. cache package only depends on dataset package
4. dataset package implements the operations that handles the legacy/Geolite2 datasets access.

handler is simplified as just sending requests (IP & timestamp) and get GeoAnnotation back w/o knowing any details

cache works between handler and dataset, doing chores like initialize the dataset filename list, select the correct dataset given a request, etc.

dataset does the dataset loading/handling and all dirty mutex jobs.

In main.go, it only need functions in handler, which simplify the previous implementation as well. 

> *[Reviewable](https://reviewable.io/reviews/m-lab/annotation-service/106#-:-LSL4u-F916OqP3C5iGo:b-zc5nfs)* status: 0 of 1 LGTMs obtained

**Review by yachang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/annotation-service/106)* status: 0 of 1 LGTMs obtained

___
*[dataset/dataset-in-memory.go, line 59 at r8](https://reviewable.io/reviews/m-lab/annotation-service/106#-LSGcP_UBs2TQfIbH97P:-LSL6p7N428kKYD1jeDA:b-896fix) ([raw file](https://github.com/m-lab/annotation-service/blob/5620de14a36c71a72947e87d37cedf0b0b36439e/dataset/dataset-in-memory.go#L59)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Generally, interfaces should be exported.
</blockquote></details>

Done.

**Review by yachang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/annotation-service/106)* status: 0 of 1 LGTMs obtained

___
*[handler/init.go, line 1 at r8](https://reviewable.io/reviews/m-lab/annotation-service/106#-LSG_4we4gpRun5fwyLw:-LSL73jwAIsq4OdIDU6r:by4r21m) ([raw file](https://github.com/m-lab/annotation-service/blob/5620de14a36c71a72947e87d37cedf0b0b36439e/handler/init.go#L1)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Please add a TODO - most of this code should move to the dataset package, or a maybe 
datasetloader package.
</blockquote></details>

File deleted

**Review by gfr10598 — COMMENTED** [review]
So, this PR is definitely too big now, and its doing three different things - refactoring, introducing new code (cache) and adding new functionality to existing code.

Please break out cache*.go into its own PR.  Then another PR that just moves the geo_ip code.  Then we'll see what is left in this PR.

> *[Reviewable](https://reviewable.io/reviews/m-lab/annotation-service/106#-:-LSL6zq08N3J0bPkExRv:blnofcp)* status: 0 of 1 LGTMs obtained

**Review by gfr10598 — COMMENTED** [review]
> dataset
BTW, the PR comment is excellent and very helpful.

> *[Reviewable](https://reviewable.io/reviews/m-lab/annotation-service/106#-:-LSL8bMr8Tsij5GMTja_:b7sditf)* status: 0 of 1 LGTMs obtained

**Review by yachang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/annotation-service/106)* status: 0 of 1 LGTMs obtained

___
*[dataset/dataset-in-memory.go, line 46 at r8](https://reviewable.io/reviews/m-lab/annotation-service/106#-LSGbeb0D0nHq1wGo_0j:-LSLOMA_3ANhqRQjZkD0:b-896fix) ([raw file](https://github.com/m-lab/annotation-service/blob/5620de14a36c71a72947e87d37cedf0b0b36439e/dataset/dataset-in-memory.go#L46)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Not crazy about this function.  Suggest instead you use a map[string]struct{} to store the pending loads.  Then you can just use golang delete().

Also, this looks like new functionality, so it would be better to avoid it in a large refactoring.
</blockquote></details>

Done.

**Pull request closed without merging**
