### PR TITLE
use binary search

### PR DESCRIPTION
**Pull request by gfr10598**
Somehow, the change to use binary search never made it into the master branch.  It appears to be in use in sandbox, but not clear whether there was ever a branch in the repo that reflected that version of the code.  May have been local on joseph's machine.

Do not remove the Sept1 sandbox deployment until we are satisfied that this deployment is good.
 

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/annotation-service/48)

### CODE REVIEW

**Comment by yachang** [comment]
Add a benchmark test for running time?

**Comment by gfr10598** [comment]
The dashboards already have monitoring of the response time, both internal and external.  This is what we actually care about, so I would prefer to not worry about a benchmark.

Do you know what happened to the benchmark that Shelby wrote?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/48#-:-KwB5gcBP7n_aIewq6gL:b-thpkz7)*

**Comment by gfr10598** [comment]
Added a benchmark.  Still tweaking details to make it efficient, but please review.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/48#-:-KwC368wDeKLQaJjcKaJ:b-df90ex)*

**Comment by gfr10598** [comment]
Reviewed 1 of 1 files at r1, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/48)*

**Comment by gfr10598** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/48)*

**Comment by yachang** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/annotation-service/48#-:-KwC9xvEwqHrr5aH9PsJ:bnfp4nl)*

**Pull request merged**
